---
node_exporter_port: 9100
node_exporter_listen_address: "0.0.0.0:{{ node_exporter_port }}"
node_exporter_telemetry_path: "/metrics"
node_exporter_options:
  - '--web.listen-address={{ node_exporter_listen_address }}'
  - '--web.telemetry-path={{ node_exporter_telemetry_path }}'
  - '--collector.systemd'
