---
galaxy_info:
  author: t_deployment
  description: called by other roles to request firewall rule installation later
  company: ataccama

  license: internal

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - focal
    - name: CentOS
      versions:
        - 8
  galaxy_tags: []

dependencies: []
