---
- name: Configure FluentBit
  include_role:
    name: fluentbit
    tasks_from: config_d.yml
  vars:
    fluentbit_conf_d:
      - name: frontend.conf
        template: one-webapp.fluentbit.conf.j2
      - name: console-filter.conf
        template: fluentbit/filters/console-filter.conf.j2
      - name: accesslog-rm-filter.conf
        template: fluentbit/filters/accesslog-rm-filter.conf.j2
    fluentbit_parsers_d:
      - name: one-webapp-parser.conf
        template: one-webapp-parser.fluentbit.conf.j2
