{
 "title": "Traefik 2.2",
 "description": "Traefik dashboard (data from prometheus) (based on Traefik by Thomas Cheronneau https://grafana.com/grafana/dashboards/4475)",
 "tags": [
  "prometheus",
  "traefik"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(traefik_config_reloads_total, environment)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traefik_service_open_connections{environment=~\"$environment\"}, exported_service)"
    }
   },
   {
    "name": "entrypoint",
    "query": {
     "query": "label_values(traefik_entrypoint_open_connections{environment=~\"$environment\"}, entrypoint)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average response time by service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{environment=\"$environment\"}) by (exported_service) / sum(traefik_service_request_duration_seconds_count{environment=\"$environment\"}) by (exported_service)",
     "legendFormat": " {{ exported_service }}"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{environment=\"$environment\"}[5m])) by (exported_service) ",
     "legendFormat": "{{ exported_service }}"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{environment=\"$environment\",entrypoint =~ \"$entrypoint\"}[5m])) by (entrypoint) ",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  },
  {
   "title": "Status code 200 over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{environment=\"$environment\",entrypoint=~\"$entrypoint\",code=\"200\"}[5m])",
     "legendFormat": "{{method}} : {{code}} ( {{ entrypoint }} )"
    }
   ]
  },
  {
   "title": "Others status code over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{environment=\"$environment\",entrypoint=~\"$entrypoint\",code!=\"200\"}[5m])",
     "legendFormat": "{{ method }} : {{code}} ( {{ entrypoint }} )"
    }
   ]
  },
  { "title": "$service stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$service response time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{environment=\"$environment\",exported_service=\"$service@kubernetes\"}) / sum(traefik_service_requests_total{environment=\"$environment\",exported_service=\"$service@kubernetes\"}) * 1000"
    }
   ]
  },
  {
   "title": "$service return code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "traefik_service_requests_total{environment=\"$environment\", exported_service=\"$service@kubernetes\"}",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Total requests over 5min $service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{environment=\"$environment\", exported_service=\"$service@kubernetes\"}[5m]))",
     "legendFormat": "Total requests $service"
    }
   ]
  }
 ]
}