---
prometheus_exporter_name: postgres_exporter
prometheus_exporter_user: "{{ postgres_exporter_user }}"
prometheus_exporter_group: "{{ postgres_exporter_group }}"

prometheus_exporter_dist: "postgres_exporter-{{ postgres_exporter_version }}.linux-amd64"
prometheus_exporter_download_url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ postgres_exporter_version }}/{{ prometheus_exporter_dist }}.tar.gz"

prometheus_exporter_bin: "{{ prometheus_exporter_name }}"
prometheus_exporter_home: "{{ postgres_exporter_home }}"
prometheus_exporter_home_manage: false

prometheus_exporter_config_file: "/etc/default/{{ prometheus_exporter_name }}"
prometheus_exporter_service_name: "{{ prometheus_exporter_name }}"
prometheus_exporter_log_path: "/var/log/{{ prometheus_exporter_service_name }}"
prometheus_exporter_service_execstart: "{{ prometheus_exporters_dir }}/{{ prometheus_exporter_name }}/{{ prometheus_exporter_bin }} $FLAGS"
prometheus_exporter_service_description: "{{ prometheus_exporter_name }} - Exporter for PostgreSQL metrics."
prometheus_exporter_env_variables:
  DATA_SOURCE_NAME: "{{ postgres_exporter_datasource }}"
  FLAGS: "{{ postgres_exporter_flags | join(' ') }}"
