---
- name: Configure FluentBit
  include_role:
    name: fluentbit
    tasks_from: config_d.yml
  vars:
    fluentbit_conf_d:
      - name: mde-lineage.conf
        template: mde-lineage.fluentbit.conf.j2
      - name: console-filter.conf
        template: fluentbit/filters/console-filter.conf.j2
    fluentbit_parsers_d:
      - name: mde-lineage-parser.conf
        template: mde-lineage-parser.fluentbit.conf.j2
