---
- name: Debian - Install virtualenv and Anomaly Detector dependencies
  apt:
    pkg:
      - libssl1.1
      - sqlite3
      - libgomp1
    update_cache: yes
    state: present

# NOTE: we must fix Ubuntu focal until team AI provides better builds
- name: Install libffi6 for Anomaly Detection Anomaly Detector
  apt:
    deb: "{{ anomaly_detection_anomaly_detector_focal_libffi6_repo }}/{{ anomaly_detection_anomaly_detector_focal_libffi6_path }}"
  when: ansible_facts['distribution_release'] == 'focal'
