---
- name: Configure FluentBit
  include_role:
    name: fluentbit
    tasks_from: config_d.yml
  vars:
    fluentbit_conf_d:
      - name: anomaly-detection-anomaly-detector.conf
        template: anomaly-detection-anomaly-detector.fluentbit.conf.j2
      - name: console-filter.conf
        template: fluentbit/filters/console-filter.conf.j2
      - name: accesslog-rm-filter.conf
        template: fluentbit/filters/accesslog-rm-filter.conf.j2
    fluentbit_parsers_d:
      - name: anomaly-detection-anomaly-detector-parser.conf
        template: anomaly-detection-anomaly-detector-parser.fluentbit.conf.j2
