---
- name: set monitoring rules
  include_role:
    name: monitoring_rules
  tags: monitoring
  vars:
    monitoring_ruleset:
      job_name: anomaly-detection-anomaly-detector
      metrics_path: /actuator/prometheus
      basic_auth:
        username: "{{ keycloak_monitoring_user.username }}"
        password: "{{ keycloak_monitoring_user.password }}"
      scheme: http
      port: "{{ anomaly_detection_anomaly_detector_http_port }}"
      static_configs:
        - labels:
            namespace: onprem
            clusterName: onprem
            app_kubernetes_io_component: anomaly-detection-anomaly-detector
