---
# variables for RHEL 7 & CentOS 7

epel_repo:
  name: epel
  description: "Extra Packages for Enterprise Linux $releasever - $basearch"
  metalink: "https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir"
  gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
