{
 "title": "Thanos / Clusters - Overview",
 "tags": [ "thanos-custom" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "dev, test, prod" },
   {
    "name": "clusterName",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info, clusterName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU and Memory Usage - Sum per Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Core Usage (vCPU time) - Sum per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{environment=~\"$environment\", clusterName=~\"$clusterName\"}) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Memory Usage (MWS) - Sum per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max(container_memory_working_set_bytes{container!=\"\", environment=~\"$environment\", clusterName=~\"$clusterName\"}) by (clusterName, pod)) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "MMM DB - Complexity per Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Sources Max per Cluster",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "max(mmm_db_statistics_data_sources{environment=~\"$environment\"} > 0) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      }
     ]
    },
    {
     "title": "Catalog Items Max per Cluster",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "max(mmm_db_statistics_catalog_items{environment=~\"$environment\"} > 0) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      }
     ]
    },
    {
     "title": "Terms Max per Cluster",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "max(mmm_db_statistics_number_of_terms{environment=~\"$environment\"} > 0) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      }
     ]
    },
    {
     "title": "Attributes Max per Cluster",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "max(mmm_db_statistics_attributes{environment=~\"$environment\"} > 0) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      }
     ]
    },
    {
     "title": "Rules Amount Max per Cluster",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "max(mmm_db_statistics_rules_amount{environment=~\"$environment\"} > 0) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      }
     ]
    },
    {
     "title": "Profiled tables % per Cluster",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "max(mmm_db_statistics_profiled_tables_percentage{environment=~\"$environment\"} > 0) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      }
     ]
    }
   ]
  }
 ]
}