{
 "title": "Thanos / Cluster's Node Sizes",
 "tags": [ "thanos-custom" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "environment", "label": "Environment", "query": "dev, test, prod" }
  ]
 },
 "panels": [
  {
   "title": "Cluster's Node Sizes and CPU Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster's Node Count",
   "type": "bargauge",
   "description": "Shows latest current (max) number of nodes on each cluster. Largest clusters are marked red as possible candidates for reduction.",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(kube_node_info{environment=~\"$environment\"}) by (clusterName, node)) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Cluster's CPU (vCores)",
   "type": "bargauge",
   "description": "Shows latest (max) CPU capacity on each cluster. Largest clusters are marked red as possible candidates for reduction.",
   "gridPos": { "h": 18, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(instance:node_num_cpu:sum{environment=~\"$environment\"}) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Avg CPU per Node Size",
   "type": "bargauge",
   "description": "Shows latest (avg) CPU cores per node.",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(instance:node_num_cpu:sum{environment=~\"$environment\"}) by (clusterName) / sum(kube_node_info{environment=~\"$environment\"}) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Requested CPU and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requested out of Total Cluster CPU (vCores)",
     "type": "bargauge",
     "description": "Percentage of cluster's total CPU capacity being allocated by pods Requests. More is better, hence green color.",
     "gridPos": { "h": 26, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{environment=~\"$environment\"} < 1000) by (clusterName)\r\n/sum(instance:node_num_cpu:sum{environment=~\"$environment\"}) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      }
     ]
    },
    {
     "title": "Unused Cluster CPU (vCores)",
     "type": "bargauge",
     "description": "Absolute value of total CPU not being Requested by pods. Generally higher values are candidates for review.",
     "gridPos": { "h": 26, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-(sum(kube_pod_container_resource_requests{environment=~\"$environment\"} < 1000) by (clusterName)\r\n/sum(instance:node_num_cpu:sum{environment=~\"$environment\"}) by (clusterName))) * (sum(instance:node_num_cpu:sum{environment=~\"$environment\"}) by (clusterName))",
       "legendFormat": "{{clusterName}}"
      }
     ]
    },
    {
     "title": "Requested out of Total Cluster Memory",
     "type": "bargauge",
     "description": "Percentage of cluster's total Memory capacity being allocated by pods Requests. More is better, hence green color.",
     "gridPos": { "h": 26, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{environment=~\"$environment\"} > 1000) by (clusterName)\r\n/sum(node_memory_MemTotal_bytes{environment=~\"$environment\"}) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      }
     ]
    },
    {
     "title": "Unused Cluster Memory",
     "type": "bargauge",
     "description": "Absolute value of total Memory not being Requested by pods. Generally higher values are candidates for review.",
     "gridPos": { "h": 26, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-(sum(kube_pod_container_resource_requests{environment=~\"$environment\"} > 1000) by (clusterName)\r\n/sum(node_memory_MemTotal_bytes{environment=~\"$environment\"}) by (clusterName))) * (sum(node_memory_MemTotal_bytes{environment=~\"$environment\"}) by (clusterName))",
       "legendFormat": "{{clusterName}}"
      }
     ]
    }
   ]
  }
 ]
}