{
 "title": "Datastories dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(clusterName)" } },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "container", "query": { "query": "label_values(container)" } },
   { "name": "be_job", "label": "backend job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Kubernetes stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers ready",
   "type": "status-history",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (container) (kube_pod_container_status_ready{clusterName=~\"$cluster\", namespace=~\"$namespace\", container=~\"datastories.*\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", container=~\"datastories.*\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mcpu" } },
   "targets": [
    {
     "expr": "sum by(container) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\"$container\"}[$__rate_interval])) * 1000",
     "legendFormat": "Actual usage {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{clusterName=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\", resource=\"cpu\"} * 1000",
     "legendFormat": "Requests {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{clusterName=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\", resource=\"cpu\"} * 1000",
     "legendFormat": "Limits {{container}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"$namespace\", container=~\"$container\"} / 1024 / 1024",
     "legendFormat": "Actual usage {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{clusterName=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\", resource=\"memory\"} / 1024 / 1024",
     "legendFormat": "Requests {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{clusterName=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\", resource=\"memory\"} / 1024 / 1024",
     "legendFormat": "Limits {{container}}"
    }
   ]
  },
  { "title": "Prefect & Dask", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Flows in progress",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (agent) (ataccama_datastories_agent_flows_in_progress{clusterName=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dask workers (from all schedulers)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (ataccama_datastories_dask_scheduler_workers{clusterName=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Task count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "ataccama_datastories_dask_scheduler_tasks{clusterName=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total process memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum by (agent) (ataccama_datastories_agent_total_process_memory{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dask scheduler tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  # Metric was increased in the selected $__range\n  (increase(ataccama_datastories_dask_scheduler_tasks_forgotten_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__range])) > 0\n  or\n  # Metric was created for the first time inside the $__range, if it's created with 42 errors in the first scrape,\n  # those would be missed by increase()\n  (\n    ataccama_datastories_dask_scheduler_tasks_forgotten_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}\n    and\n    ataccama_datastories_dask_scheduler_tasks_forgotten_created{clusterName=~\"$cluster\", namespace=~\"$namespace\"} > ${__from:date:seconds}\n  )\n)\nor vector(0)",
     "legendFormat": "Forgotten tasks"
    },
    {
     "expr": "sum(\n  # Metric was increased in the selected $__range\n  (increase(ataccama_datastories_dask_scheduler_tasks_suspicious_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__range])) > 0\n  or\n  # Metric was created for the first time inside the $__range, if it's created with 42 errors in the first scrape,\n  # those would be missed by increase()\n  (\n    ataccama_datastories_dask_scheduler_tasks_suspicious_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}\n    and\n    ataccama_datastories_dask_scheduler_tasks_suspicious_created{clusterName=~\"$cluster\", namespace=~\"$namespace\"} > ${__from:date:seconds}\n  )\n)\nor vector(0)",
     "legendFormat": "Suspicious tasks"
    }
   ]
  },
  {
   "title": "Dask scheduler clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (ataccama_datastories_dask_scheduler_clients{clusterName=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Clients"
    }
   ]
  },
  { "title": "HTTP Requests Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  # Metric was increased in the selected $__range\n  (increase(ataccama_datastories_platform_responses_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=~\"$be_job\", status_code=~\"5..\"}[$__range])) > 0\n  or\n  # Metric was created for the first time inside the $__range, if it's created with 42 errors in the first scrape,\n  # those would be missed by increase()\n  (\n    ataccama_datastories_platform_responses_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=~\"$be_job\", status_code=~\"5..\"}\n    and\n    ataccama_datastories_platform_responses_created{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=~\"$be_job\", status_code=~\"5..\"} > ${__from:date:seconds}\n  )\n)\nor vector(0)",
     "legendFormat": "5XX errors"
    },
    {
     "expr": "sum(\n  # Metric was increased in the selected $__range\n  (increase(ataccama_datastories_platform_responses_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\", status_code=~\"4..\"}[$__range])) > 0\n  or\n  # Metric was created for the first time inside the $__range, if it's created with 42 errors in the first scrape,\n  # those would be missed by increase()\n  (\n    ataccama_datastories_platform_responses_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\", status_code=~\"4..\"}\n    and\n    ataccama_datastories_platform_responses_created{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\", status_code=~\"4..\"} > ${__from:date:seconds}\n  )\n)\nor vector(0)",
     "legendFormat": "4XX errors"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 4, "y": 28 },
   "targets": [
    {
     "expr": "(\n  # Metric was increased in the selected $__range\n  sum by (method, path_template) (increase(ataccama_datastories_platform_responses_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\", status_code=~\"4..|5..\"}[$__range])) > 0\n  or\n  # Metric was created for the first time inside the $__range, if it's created with 42 errors in the first scrape,\n  # those would be missed by increase()\n  sum by (method, path_template) (\n    ataccama_datastories_platform_responses_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\", status_code=~\"4..|5..\"}\n    and\n    ataccama_datastories_platform_responses_created{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"} > ${__from:date:seconds}\n  )\n) > 0\n",
     "legendFormat": "{{method}} {{path_template}}"
    }
   ]
  },
  {
   "title": "Total HTTP requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 9, "y": 28 },
   "targets": [
    {
     "expr": "sum by(job, instance) (rate(ataccama_datastories_platform_requests_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__rate_interval])) * 60",
     "legendFormat": "Number of requests ({{job}}, {{instance}})"
    }
   ]
  },
  {
   "title": "Number of HTTP requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 13, "y": 28 },
   "targets": [
    {
     "expr": "sum by(method, path_template) (rate(ataccama_datastories_platform_requests_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__rate_interval])) * 60",
     "legendFormat": "{{method}} {{path_template}}"
    }
   ]
  },
  {
   "title": "Slowest HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk (5,\n    (\n        sum by (method, path_template) (\n            increase(ataccama_datastories_platform_requests_processing_time_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__rate_interval])\n            /\n            increase(ataccama_datastories_platform_requests_processing_time_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__rate_interval])\n        ) >= 0\n    ) * 1000\n)",
     "legendFormat": "{{method}} {{path_template}}"
    }
   ]
  },
  {
   "title": "Slowest HTTP requests 95 quantiles",
   "type": "table",
   "description": "Decay time 1 hour. Accuracy depends on the specified buckets.",
   "gridPos": { "h": 10, "w": 4, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, sum(rate(ataccama_datastories_platform_requests_processing_time_seconds_bucket{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[1h])) by (le, path_template, method)) > 0) * 1000",
     "legendFormat": "{{method}} {{path_template}}"
    }
   ]
  },
  {
   "title": "Request duration distribution over time",
   "type": "heatmap",
   "description": "Each column represents distribution aggregated over the last hour.",
   "gridPos": { "h": 10, "w": 8, "x": 13, "y": 38 },
   "targets": [
    {
     "expr": "(\n    sum by(le) (increase(ataccama_datastories_platform_requests_processing_time_seconds_bucket{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[1h])) \n    / \n    scalar(\n        sum(\n            increase(ataccama_datastories_platform_requests_processing_time_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[1h])\n        )\n    )\n) * 100",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Query Builder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Query builder errors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  # Metric was increased in the selected $__range\n  (increase(ataccama_datastories_platform_responses_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\", status_code=~\"5..\", path_template=~\"/v0/queries/fetch-data.*|/v0/story-token/.*\"}[$__range])) > 0\n  or\n  # Metric was created for the first time inside the $__range, if it's created with 42 errors in the first scrape,\n  # those would be missed by increase()\n  (\n    ataccama_datastories_platform_responses_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\", status_code=~\"5..\", path_template=~\"/v0/queries/fetch-data.*|/v0/story-token/.*\"}\n    and\n    ataccama_datastories_platform_grpc_client_query_errors_created{status_code=~\"5..\", path_template=~\"/v0/queries/fetch-data.*|/v0/story-token/.*\"} > ${__from:date:seconds}\n  )\n)\nor vector(0)",
     "legendFormat": "5XX errors"
    },
    {
     "expr": "sum(\n  # Metric was increased in the selected $__range\n  (increase(ataccama_datastories_platform_responses_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\", status_code=~\"4..\", path_template=~\"/v0/queries/fetch-data.*|/v0/story-token/.*\"}[$__range])) > 0\n  or\n  # Metric was created for the first time inside the $__range, if it's created with 42 errors in the first scrape,\n  # those would be missed by increase()\n  (\n    ataccama_datastories_platform_responses_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\", status_code=~\"4..\", path_template=~\"/v0/queries/fetch-data.*|/v0/story-token/.*\"}\n    and\n    ataccama_datastories_platform_grpc_client_query_errors_created{status_code=~\"4..\", path_template=~\"/v0/queries/fetch-data.*|/v0/story-token/.*\"} > ${__from:date:seconds}\n  )\n)\nor vector(0)",
     "legendFormat": "4XX errors"
    },
    {
     "expr": "sum(\n  # Metric was increased in the selected $__range\n  (increase(ataccama_datastories_platform_query_builder_sql_errors_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__range])) > 0\n  or\n  # Metric was created for the first time inside the $__range, if it's created with 42 errors in the first scrape,\n  # those would be missed by increase()\n  (\n    ataccama_datastories_platform_query_builder_sql_errors_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}\n    and\n    ataccama_datastories_platform_query_builder_sql_errors_created{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"} > ${__from:date:seconds}\n  )\n)\nor vector(0)",
     "legendFormat": "SQL execution errors"
    }
   ]
  },
  {
   "title": "Average SQL query duration over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 4, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n    sum by (data_source) (\n        increase(ataccama_datastories_platform_query_builder_sql_execution_time_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__rate_interval])\n        /\n        increase(ataccama_datastories_platform_query_builder_sql_execution_time_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__rate_interval])\n    ) >= 0\n) * 1000",
     "legendFormat": "{{data_source}}"
    }
   ]
  },
  {
   "title": "Query duration distribution over time",
   "type": "heatmap",
   "description": "Each column represents distribution aggregated over the last hour.",
   "gridPos": { "h": 10, "w": 8, "x": 13, "y": 49 },
   "targets": [
    {
     "expr": "(\n    sum by(le) (increase(ataccama_datastories_platform_query_builder_sql_execution_time_bucket{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[1h])) \n    / \n    scalar(\n        sum(\n            increase(ataccama_datastories_platform_query_builder_sql_execution_time_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[1h])\n        )\n    )\n) * 100",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Graphql client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "GraphQL client errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "(\n  # Metric was increased in the selected $__range\n  sum by (exception_type) (increase(ataccama_datastories_platform_gql_client_query_errors_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__range])) > 0\n  or\n  # Metric was created for the first time inside the $__range, if it's created with 42 errors in the first scrape,\n  # those would be missed by increase()\n  sum by(exception_type) (\n    ataccama_datastories_platform_gql_client_query_errors_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}\n    and\n    ataccama_datastories_platform_gql_client_query_errors_created{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"} > ${__from:date:seconds}\n  )\n) > 0\n",
     "legendFormat": "{{exception_type}}"
    }
   ]
  },
  {
   "title": "Average graphQL client query duration over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 4, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n    sum by (operation_name) (\n        increase(ataccama_datastories_platform_gql_client_query_execution_time_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__rate_interval])\n        /\n        increase(ataccama_datastories_platform_gql_client_query_execution_time_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__rate_interval])\n    ) >= 0\n) * 1000",
     "legendFormat": "{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request duration distribution over time",
   "type": "heatmap",
   "description": "Each column represents distribution aggregated over the last hour.",
   "gridPos": { "h": 10, "w": 8, "x": 13, "y": 60 },
   "targets": [
    {
     "expr": "(\n    sum by(le) (increase(ataccama_datastories_platform_gql_client_query_execution_time_bucket{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[1h])) \n    / \n    scalar(\n        sum(\n            increase(ataccama_datastories_platform_gql_client_query_execution_time_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[1h])\n        )\n    )\n) * 100",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "GRPC client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "GRPC client errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "(\n  # Metric was increased in the selected $__range\n  sum by (exception_type) (increase(ataccama_datastories_platform_grpc_client_query_errors_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__range])) > 0\n  or\n  # Metric was created for the first time inside the $__range, if it's created with 42 errors in the first scrape,\n  # those would be missed by increase()\n  sum by(exception_type) (\n    ataccama_datastories_platform_grpc_client_query_errors_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}\n    and\n    ataccama_datastories_platform_grpc_client_query_errors_created{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"} > ${__from:date:seconds}\n  )\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average GRPC client query duration over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 4, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n    sum by (service_name, method_name) (\n        increase(ataccama_datastories_platform_grpc_client_query_execution_time_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__rate_interval])\n        /\n        increase(ataccama_datastories_platform_grpc_client_query_execution_time_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__rate_interval])\n    ) >= 0\n) * 1000",
     "legendFormat": "{{service_name}}.{{method_name}}"
    }
   ]
  },
  {
   "title": "Request duration distribution over time",
   "type": "heatmap",
   "description": "Each column represents distribution aggregated over the last hour.",
   "gridPos": { "h": 10, "w": 8, "x": 13, "y": 71 },
   "targets": [
    {
     "expr": "(\n    sum by(le) (increase(ataccama_datastories_platform_grpc_client_query_execution_time_bucket{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[1h])) \n    / \n    scalar(\n        sum(\n            increase(ataccama_datastories_platform_grpc_client_query_execution_time_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[1h])\n        )\n    )\n) * 100",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "DMM client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "DMM client errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "(\n  # Metric was increased in the selected $__range\n  sum by (exception_type) (increase(ataccama_datastories_platform_dmm_client_query_errors_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__range])) > 0\n  or\n  # Metric was created for the first time inside the $__range, if it's created with 42 errors in the first scrape,\n  # those would be missed by increase()\n  sum by(exception_type) (\n    ataccama_datastories_platform_dmm_client_query_errors_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}\n    and\n    ataccama_datastories_platform_dmm_client_query_errors_created{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"} > ${__from:date:seconds}\n  )\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average DMM client query duration over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 4, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n    sum by (operation_name) (\n        increase(ataccama_datastories_platform_dmm_client_query_execution_time_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__rate_interval])\n        /\n        increase(ataccama_datastories_platform_dmm_client_query_execution_time_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[$__rate_interval])\n    ) >= 0\n) * 1000",
     "legendFormat": "{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request duration distribution over time",
   "type": "heatmap",
   "description": "Each column represents distribution aggregated over the last hour.",
   "gridPos": { "h": 10, "w": 8, "x": 13, "y": 82 },
   "targets": [
    {
     "expr": "(\n    sum by(le) (increase(ataccama_datastories_platform_dmm_client_query_execution_time_bucket{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[1h])) \n    / \n    scalar(\n        sum(\n            increase(ataccama_datastories_platform_dmm_client_query_execution_time_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", job=\"$be_job\"}[1h])\n        )\n    )\n) * 100",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}