{
 "title": "DQ - MP",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DQ Dashboards", "type": "dashlist", "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 } },
  { "title": "Monitoring Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Monitoring project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (phase)(ataccama_one_mmm_monitoringproject_time_seconds_max{phase=~\".+\", namespace=~\"$namespace\"}) ",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": " DQ Operations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation)(ataccama_one_mmm_mdoperations_time_seconds_max{operation=~\".*plugin\\\\.monitoringproject\\\\.flow\\\\.operation.*\", namespace=~\"$namespace\"})",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum by (operation)(ataccama_one_mmm_mdoperations_time_seconds_max{operation=~\".*plugin\\\\.dqeval\\\\.operation.*\", namespace=~\"$namespace\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "DQ jobs volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (parameter)(increase(ataccama_one_mmm_dq_eval_volume_total{parameter=~\".+\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{parameter}}"
    }
   ]
  },
  {
   "title": "Updates amount",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (type)(increase(ataccama_one_mmm_monitoringproject_counter_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Overall DQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Failed DQ jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ataccama_one_mmm_jobs_duration_total_seconds_count{type =~\"DQ.*\", exitStatus=\"FAILED\", namespace=~\"$namespace\"}[$__range])) by (type)\n",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(increase(ataccama_one_mmm_jobs_duration_total_seconds_count{type =\"STRUCTURE-CHECK\", exitStatus=\"FAILED\", namespace=~\"$namespace\"}[$__range])) by (type)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Successful DQ jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ataccama_one_mmm_jobs_duration_total_seconds_count{type =~\"DQ.*\", exitStatus=\"FINISHED\", namespace=~\"$namespace\"}[$__range])) by (type)\n",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(increase(ataccama_one_mmm_jobs_duration_total_seconds_count{type =\"STRUCTURE-CHECK\", exitStatus=\"FINISHED\", namespace=~\"$namespace\"}[$__range])) by (type)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Failed DQ jobs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(ataccama_one_mmm_jobs_duration_total_seconds_count{type =~\"DQ.*\", exitStatus=\"FAILED\", namespace=~\"$namespace\"}[1h])) by (type)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Number of executed DQ jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(ataccama_one_mmm_jobs_duration_total_seconds_count{type=~\"DQ.*\", namespace=~\"$namespace\"}[1m]) * 60) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Successful DQ jobs duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (type) (ataccama_one_mmm_jobs_duration_partial_seconds_max{type=~\"DQ.*\", status=\"RUNNING\", exitStatus=\"FINISHED\", namespace=~\"$namespace\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "DPM preprocess",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ataccama_one_dpm_plugin_executor_job_preprocess_plugin_seconds_max{name=~\"DQ.*\", namespace=~\"$namespace\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Partial Job Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (status) (ataccama_one_mmm_jobs_duration_partial_seconds_max{namespace=~\"$namespace\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "DPM postprocess",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ataccama_one_dpm_plugin_executor_job_postprocess_plugin_seconds_max{name=~\"DQ.*\", namespace=~\"$namespace\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Result saving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "MMM Results handler time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (type)(ataccama_one_mmm_dpm_result_handler_time_seconds_max{type=~\"DQ.*\", namespace=~\"$namespace\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Results saving time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (phase)(ataccama_one_mmm_monitoringproject_results_time_seconds_max{phase!=\"\", namespace=~\"$namespace\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "New records in result tables",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (type)\n(increase(ataccama_one_mmm_monitoringproject_results_counter_total{namespace=~\"$namespace\"}[$__rate_interval]) )",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Storage GraphQL Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operationName)(graphql_timer_query_seconds_max{operationName=~\".*ProjectDq.*\", namespace=~\"$namespace\"})",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  {
   "title": "Query time breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (phase)(ataccama_one_mmm_monitoringproject_results_query_time_seconds_max{namespace=~\"$namespace\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum by (phase)(ataccama_one_mmm_monitoringproject_results_query_time_seconds_sum{namespace=~\"$namespace\"}) / sum by (phase)(ataccama_one_mmm_monitoringproject_results_query_time_seconds_count{namespace=~\"$namespace\"}) ",
     "legendFormat": "average {{phase}}"
    }
   ]
  },
  {
   "title": "Max - Results operations times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (operation) (ataccama_one_mmm_mdoperations_time_seconds_max{operation=~\".*monitoringproject\\\\.storage\\\\.operation\\\\.results(.*)\", namespace=~\"$namespace\"})",
     "legendFormat": "max {{operation}}"
    }
   ]
  },
  {
   "title": "DQ Storage cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cache)(cache_size{cache=\"dqStorageCache\", namespace=~\"$namespace\"})",
     "legendFormat": "size"
    },
    {
     "expr": "sum by (result)(increase(cache_gets_total{cache=\"dqStorageCache\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "sum by (cause)(increase(cache_evictions_count{cache=\"dqStorageCache\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "eviction - {{cause}}"
    },
    {
     "expr": "sum by (result)(cache_loads_seconds_max{cache=\"dqStorageCache\", namespace=~\"$namespace\"})",
     "legendFormat": "load - {{result}}"
    }
   ]
  },
  {
   "title": "Average - Results operations times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (operation) (ataccama_one_mmm_mdoperations_time_seconds_sum{operation=~\".*monitoringproject\\\\.storage\\\\.operation\\\\.results(.*)\", namespace=~\"$namespace\"}) / sum by (operation) (ataccama_one_mmm_mdoperations_time_seconds_count{operation=~\".*monitoringproject\\\\.storage\\\\.operation\\\\.results(.*)\", namespace=~\"$namespace\"})",
     "legendFormat": "average {{operation}}"
    }
   ]
  },
  { "title": "Data retention", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Data retention job duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (action)(increase(ataccama_one_mmm_monitoringproject_retention_job_time_seconds_sum{action=~\".+\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Removed objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "sum(rate(ataccama_one_mmm_monitoringproject_retention_deleted_counter_total{type=~\".+\", namespace=~\"$namespace\"}[1m]) * 60) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Result objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by ()(mmm_db_statistics_monitoring_project_processings_amount{namespace=~\"$namespace\"})",
     "legendFormat": "processings"
    },
    {
     "expr": "sum by ()(mmm_db_statistics_monitoring_project_agg_results_rows{namespace=~\"$namespace\"})",
     "legendFormat": "aggregations"
    },
    {
     "expr": "sum(mmm_db_statistics_monitoring_project_check_results_rows{namespace=~\"$namespace\"})",
     "legendFormat": "checks"
    }
   ]
  },
  { "title": "Drillthrough", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Max - Drillthrough operations times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (operation) (ataccama_one_mmm_mdoperations_time_seconds_max{operation=~\".*monitoringproject\\\\.flow\\\\.operation\\\\.drillthrough(.*)\", namespace=~\"$namespace\"})",
     "legendFormat": "max {{operation}}"
    }
   ]
  },
  {
   "title": "Drillthrough cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cache)(cache_size{cache=\"drillthroughCache\", namespace=~\"$namespace\"})",
     "legendFormat": "size"
    },
    {
     "expr": "sum by (result)(increase(cache_gets_total{cache=\"drillthroughCache\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "sum by (cause)(increase(cache_evictions_count{cache=\"drillthroughCache\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "eviction - {{cause}}"
    },
    {
     "expr": "sum by(result)(cache_loads_seconds_max{cache=\"drillthroughCache\", namespace=~\"$namespace\"})",
     "legendFormat": "load - {{result}}"
    }
   ]
  },
  {
   "title": "Drillthrough services time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(class, method)(ataccama_one_mmm_dq_eval_drillthrough_seconds_max{namespace=~\"$namespace\"})",
     "legendFormat": "{{class}}.{{method}}"
    }
   ]
  },
  {
   "title": "GQL Timer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operationName)(graphql_timer_query_seconds_max{operationName=\"InvalidSamples\", namespace=~\"$namespace\"})",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  {
   "title": "Drillthrough services calls count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(class, method)(increase(ataccama_one_mmm_dq_eval_drillthrough_seconds_count{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{class}}.{{method}}"
    }
   ]
  }
 ]
}