{
 "title": "DQ - Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DQ Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "DQ db stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mmm_db_statistics_rules_amount{namespace=~\"$namespace\"})",
     "legendFormat": "Rules (detection & validation)"
    },
    {
     "expr": "sum(mmm_db_statistics_monitoring_project_amount{namespace=~\"$namespace\"})",
     "legendFormat": "Monitoring Projects"
    },
    {
     "expr": "sum(mmm_db_statistics_monitoring_project_processings_amount{namespace=~\"$namespace\"})",
     "legendFormat": "Processings"
    },
    {
     "expr": "sum(mmm_db_statistics_monitoring_project_check_results_rows{namespace=~\"$namespace\"})",
     "legendFormat": "Check results"
    },
    {
     "expr": "sum(mmm_db_statistics_monitoring_project_agg_results_rows{namespace=~\"$namespace\"})",
     "legendFormat": "Aggregation results"
    },
    {
     "expr": "sum(mmm_db_statistics_monitoring_project_filter_values_rows{namespace=~\"$namespace\"})",
     "legendFormat": "Filter values"
    },
    {
     "expr": "sum(mmm_db_statistics_monitoring_project_average_processings_number{namespace=~\"$namespace\"})",
     "legendFormat": "Average number of procesings"
    },
    {
     "expr": "sum(mmm_db_statistics_monitoring_project_max_processings_number{namespace=~\"$namespace\"})",
     "legendFormat": "Max number of procesings"
    },
    {
     "expr": "sum(mmm_db_statistics_monitoring_project_max_items_number{namespace=~\"$namespace\"})",
     "legendFormat": "Max number of catalog items in project"
    }
   ]
  },
  {
   "title": "Failed DQ jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ataccama_one_mmm_jobs_duration_total_seconds_count{type =~\"DQ.*\", exitStatus=\"FAILED\", namespace=~\"$namespace\"}[$__range])) by (type)\n",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(increase(ataccama_one_mmm_jobs_duration_total_seconds_count{type =\"STRUCTURE-CHECK\", exitStatus=\"FAILED\", namespace=~\"$namespace\"}[$__range])) by (type)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Successful DQ jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ataccama_one_mmm_jobs_duration_total_seconds_count{type =~\"DQ.*\", exitStatus=\"FINISHED\", namespace=~\"$namespace\"}[$__range])) by (type)\n",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(increase(ataccama_one_mmm_jobs_duration_total_seconds_count{type =\"STRUCTURE-CHECK\", exitStatus=\"FINISHED\", namespace=~\"$namespace\"}[$__range])) by (type)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Successful DQ jobs duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (type) (ataccama_one_mmm_jobs_duration_partial_seconds_max{type=~\"DQ.*\", status=\"RUNNING\", exitStatus=\"FINISHED\", namespace=~\"$namespace\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Failed DQ jobs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(ataccama_one_mmm_jobs_duration_total_seconds_count{type =~\"DQ.*\", exitStatus=\"FAILED\", namespace=~\"$namespace\"}[1h])) by (type)\n",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(increase(ataccama_one_mmm_jobs_duration_total_seconds_count{type =\"STRUCTURE-CHECK\", exitStatus=\"FAILED\", namespace=~\"$namespace\"}[1h])) by (type)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Scheduled jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (type)(increase(ataccama_one_mmm_scheduled_job_seconds_count{type=~\".+\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{type}} - rate"
    },
    {
     "expr": "sum by (type)(ataccama_one_mmm_scheduled_job_seconds_max{type=~\".+\", namespace=~\"$namespace\"})",
     "legendFormat": "{{type}} - max time"
    }
   ]
  }
 ]
}