{
 "title": "DQ - Processing",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "DQ Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 } },
  { "title": "DPM Pre-process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "DPM preprocess",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ataccama_one_dpm_plugin_executor_job_preprocess_plugin_seconds_max{name=~\"DQ.*\", namespace=~\"$namespace\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DQ Volume on DPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (name)(increase(ataccama_one_dpm_plugin_dq_volume_total{name=~\".+\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "DPM Post-process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "DPM postprocess",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ataccama_one_dpm_plugin_executor_job_postprocess_plugin_seconds_max{name=~\"DQ.*\", namespace=~\"$namespace\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DPM post-processing breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(ataccama_one_dpm_plugin_dq_postprocess_seconds_sum{namespace=~\"$namespace\"}[3m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}