{
 "title": "Ataccama / Gen 2 - Manta",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   { "name": "scrape_interval", "label": "scrape_interval", "query": "15s,30s,1m,2m,3,5m,10m,15m,30m" },
   {
    "name": "rate_interval",
    "label": "rate interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d,7d"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes / Compute Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", pod=~\"manta.*\", namespace=\"$namespace\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"manta.*\", type=\"hard\",resource=\"requests.cpu\"})",
       "legendFormat": "quota - requests"
      },
      {
       "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"manta.*\", type=\"hard\",resource=\"limits.cpu\"})",
       "legendFormat": "quota - limits"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"manta.*\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (container) /sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"manta.*\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage (w/o cache)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"manta.*\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"manta.*\", type=\"hard\",resource=\"requests.memory\"})",
       "legendFormat": "quota - requests"
      },
      {
       "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"manta.*\", type=\"hard\",resource=\"limits.memory\"})",
       "legendFormat": "quota - limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": " Inaccessible manta per minute",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "ataccama_one_dpe_plugin_mantaintegration_readiness_gauge{namespace=~\"$namespace\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Run manta processing [$rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(ataccama_one_mmm_plugin_mantaintegration_processing_job_seconds_count{namespace=~\"$namespace\"}[$rate_interval])) * 60",
       "legendFormat": "executed"
      }
     ]
    },
    {
     "title": "Processing job types duration  [$rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ataccama_one_mmm_jobs_duration_partial_seconds_sum{namespace=~\"$namespace\", type=\"MANTA-INTEGRATION\"}[$__rate_interval])/rate(ataccama_one_mmm_jobs_duration_partial_seconds_count{namespace=~\"$namespace\", type=\"MANTA-INTEGRATION\"}[$__rate_interval])",
       "legendFormat": "{{ status }} -> {{ exitStatus }}"
      }
     ]
    },
    {
     "title": "Lineage import duration  [$rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ataccama_one_mmm_plugin_mantaintegration_lineage_import_job_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_plugin_mantaintegration_lineage_import_job_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "method:{{method}}, Exception:{{exception}}, {{job}}"
      },
      {
       "expr": "rate(ataccama_one_dpe_plugin_mantaintegration_processing_service_read_output_files_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_dpe_plugin_mantaintegration_processing_service_read_output_files_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "method:readOutputFiles, dpe"
      },
      {
       "expr": "rate(ataccama_one_dpm_plugin_executor_job_postprocess_plugin_seconds_sum{namespace=~\"$namespace\", name=~\"MANTA-INTEGRATION\"}[$__rate_interval])/rate(ataccama_one_dpm_plugin_executor_job_postprocess_plugin_seconds_count{namespace=~\"$namespace\", name=~\"MANTA-INTEGRATION\"}[$__rate_interval])",
       "legendFormat": "method: postProcess, dpm"
      }
     ]
    },
    {
     "title": "Finish by status per rate interval  [$rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "increase (ataccama_one_mmm_jobs_duration_partial_seconds_count{namespace=~\"$namespace\",type=\"MANTA-INTEGRATION\", status=\"RUNNING\", exitStatus=~\"FAILED|FINISHED\"}[$__rate_interval])",
       "legendFormat": "{{type}}-{{exitStatus}}"
      }
     ]
    },
    {
     "title": "Manta integration job duration [$rate_interval]",
     "type": "timeseries",
     "description": "How long take the processing of job type from the user perspective",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (rate(ataccama_one_mmm_jobs_duration_total_seconds_sum{namespace=~\"$namespace\", type=\"MANTA-INTEGRATION\"}[$__rate_interval]) / rate(ataccama_one_mmm_jobs_duration_total_seconds_count{namespace=~\"$namespace\", type=\"MANTA-INTEGRATION\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection update",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connection operations counter - mmm [$rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "increase(ataccama_one_mmm_plugin_mantaintegration_connection_update_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{ method }}, state: {{state }}, exception:{{ exception }}"
      }
     ]
    },
    {
     "title": "Connection operations duration [$rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ataccama_one_mmm_plugin_mantaintegration_connection_update_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_plugin_mantaintegration_connection_update_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{ method }}, state: {{state }}, exception:{{ exception }}"
      }
     ]
    },
    {
     "title": "Connection operations counter - dpe, dpm [$rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "increase(ataccama_one_grpc_server_request_seconds_count{namespace=~\"$namespace\", method=~\"GetConnectionServerName\"}[$__rate_interval])",
       "legendFormat": "{{method}}, status: {{ status }}, job: {{ job }}"
      },
      {
       "expr": "increase(ataccama_one_grpc_server_request_seconds_count{namespace=~\"$namespace\", method=~\"UpdateMantaConnection\"}[$__rate_interval])",
       "legendFormat": "{{method}}, status: {{ status }}, job: {{ job }}"
      },
      {
       "expr": "increase(ataccama_one_grpc_server_request_seconds_count{namespace=~\"$namespace\", method=~\"CreateMantaConnection\"}[$__rate_interval])",
       "legendFormat": "{{method}}, status: {{ status }}, job: {{ job }}"
      },
      {
       "expr": "increase(ataccama_one_grpc_server_request_seconds_count{namespace=~\"$namespace\", method=~\"DeleteMantaConnection\"}[$__rate_interval])",
       "legendFormat": "{{method}}, status: {{ status }}, job: {{ job }}"
      },
      {
       "expr": "increase(ataccama_one_dpe_plugin_mantaintegration_workflow_terminate_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "terminateWorkflow, job: dpe"
      }
     ]
    },
    {
     "title": "Connection operations duration- dpe, dpm [$rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ataccama_one_grpc_server_request_seconds_sum{namespace=~\"$namespace\", method=~\"GetConnectionServerName\"}[$__rate_interval])/rate(ataccama_one_grpc_server_request_seconds_count{namespace=~\"$namespace\", method=~\"GetConnectionServerName\"}[$__rate_interval])",
       "legendFormat": "{{method}}, status: {{ status }},  job: {{ job }}"
      },
      {
       "expr": "rate(ataccama_one_grpc_server_request_seconds_sum{namespace=~\"$namespace\", method=~\"UpdateMantaConnection\"}[$__rate_interval])/rate(ataccama_one_grpc_server_request_seconds_count{namespace=~\"$namespace\", method=~\"UpdateMantaConnection\"}[$__rate_interval])",
       "legendFormat": "{{method}}, status: {{ status }},  job: {{ job }}"
      },
      {
       "expr": "rate(ataccama_one_grpc_server_request_seconds_sum{namespace=~\"$namespace\", method=~\"CreateMantaConnection\"}[$__rate_interval])/rate(ataccama_one_grpc_server_request_seconds_count{namespace=~\"$namespace\", method=~\"CreateMantaConnection\"}[$__rate_interval])",
       "legendFormat": "{{method}}, status: {{ status }},  job: {{ job }}"
      },
      {
       "expr": "rate(ataccama_one_grpc_server_request_seconds_sum{namespace=~\"$namespace\", method=~\"DeleteMantaConnection\"}[$__rate_interval])/rate(ataccama_one_grpc_server_request_seconds_count{namespace=~\"$namespace\", method=~\"DeleteMantaConnection\"}[$__rate_interval])",
       "legendFormat": "{{method}}, status: {{ status }},  job: {{ job }}"
      },
      {
       "expr": "rate(ataccama_one_dpe_plugin_mantaintegration_workflow_terminate_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_dpe_plugin_mantaintegration_workflow_terminate_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "terminateWorkflow, job: dpe"
      }
     ]
    }
   ]
  }
 ]
}