{
 "title": "Ataccama / Gen 2 - Anomaly Detector",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Anomaly Detector Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stream requests count - overall",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ataccama_one_anomaly_detection_anomaly_detector__n_ad_stream_requests_total[$__range])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Processed categories count - overall",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ataccama_one_anomaly_detection_anomaly_detector__duration_of_ad_per_model_on_one_category_seconds_count[$__range])) OR on() vector(0)",
     "legendFormat": "ADs performed"
    }
   ]
  },
  {
   "title": "AD unary requests count - overall",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ataccama_one_anomaly_detection_anomaly_detector__n_ad_unary_requests_total[$__range])) OR on() vector(0)",
     "legendFormat": "ADs performed"
    }
   ]
  },
  {
   "title": "AD service stream requests (rpm)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(ataccama_one_anomaly_detection_anomaly_detector__n_ad_stream_requests_total[1m])",
     "legendFormat": "instance={{instance}}, ns={{namespace}}"
    }
   ]
  },
  {
   "title": "AD service unary requests (rpm)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(ataccama_one_anomaly_detection_anomaly_detector__n_ad_unary_requests_total[1m])",
     "legendFormat": "instance={{instance}}, ns={{namespace}}"
    }
   ]
  },
  {
   "title": "AD service processed categories count - average per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(ataccama_one_anomaly_detection_anomaly_detector__duration_of_ad_per_model_on_one_category_seconds_count[1m]) * 60",
     "legendFormat": "full_detection={{detection_on_full_history}}, model_type={{model_type}}, category_type={{category_type}}"
    }
   ]
  },
  {
   "title": "AD service model duration - average per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "(rate(ataccama_one_anomaly_detection_anomaly_detector__duration_of_ad_per_model_on_one_category_seconds_sum[1m]) / rate(ataccama_one_anomaly_detection_anomaly_detector__duration_of_ad_per_model_on_one_category_seconds_count[1m]))",
     "legendFormat": "type={{model_type}}, category={{category_type}}, full history={{detection_on_full_history}}"
    }
   ]
  },
  {
   "title": "Number of points processed in 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "increase(ataccama_one_anomaly_detection_anomaly_detector__n_data_points_total_sum[1m])",
     "legendFormat": "instance={{instance}}, ns={{namespace}}"
    }
   ]
  },
  {
   "title": "Number of detected anomalous points in 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "increase(ataccama_one_anomaly_detection_anomaly_detector__n_detected_anomalous_data_points_total_sum[1m])",
     "legendFormat": "model={{model_type}}, full_detection={{detection_on_full_history}}"
    }
   ]
  },
  {
   "title": "Anomaly Detection MMM Plugin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ADP requests queue size - latest",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ataccama_one_mmm_anomaly_detection_job_queue_size"
    }
   ]
  },
  {
   "title": "ADP results queue size - latest",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ataccama_one_mmm_anomaly_detection_job_result_queue"
    }
   ]
  },
  {
   "title": "AD plugin queues sizes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "ataccama_one_mmm_anomaly_detection_job_queue_size",
     "legendFormat": "Requests"
    },
    {
     "expr": "ataccama_one_mmm_anomaly_detection_job_result_queue",
     "legendFormat": "Responses"
    }
   ]
  },
  {
   "title": "Profiling execution - max per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(max_over_time(ataccama_one_mmm_profiling_duration_seconds_max[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Profiling execution - average per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "(sum(rate(ataccama_one_mmm_profiling_duration_seconds_sum[1m])) / sum(rate(ataccama_one_mmm_profiling_duration_seconds_count[1m])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "AD plugin job execution - max per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "max_over_time(ataccama_one_mmm_anomaly_detection_job_execute_seconds_max[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}