{
 "title": "Ataccama / Gen 2 - AI - Term Suggestions",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(clusterName)" } },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "scrape_interval",
    "query": "15s,30s,1m,5m,10m,15m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "neighbor", "query": "1, 2, 3, 4, 5" }
  ]
 },
 "panels": [
  { "title": "MMM general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sucessful gRPC call rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(ataccama_one_grpc_client_call_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", method=~\"ProcessEvents|GetTermSuggestions|GetRestorationState|SetThreshold|GetThreshold|SetAdaptiveLearning|GetAdaptiveLearning\", status=\"OK\"}[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Failed gRPC call rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(ataccama_one_grpc_client_call_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", method=~\"ProcessEvents|GetTermSuggestions|GetRestorationState|SetThreshold|GetThreshold|SetAdaptiveLearning|GetAdaptiveLearning\", status!=\"OK\"}[$__rate_interval])",
     "legendFormat": "{{method}} ({{status}})"
    }
   ]
  },
  {
   "title": "Succesfull gRPC calls duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ataccama_one_grpc_client_call_seconds_max{clusterName=~\"$cluster\", namespace=~\"$namespace\", method=~\"ProcessEvents|GetTermSuggestions|GetRestorationState|SetThreshold|GetThreshold|SetAdaptiveLearning|GetAdaptiveLearning\", status=\"OK\"}",
     "legendFormat": "Max {{method}} "
    },
    {
     "expr": "rate(ataccama_one_grpc_client_call_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\", method=~\"ProcessEvents|GetTermSuggestions|GetRestorationState|SetThreshold|GetThreshold|SetAdaptiveLearning|GetAdaptiveLearning\", status=\"OK\"}[$__rate_interval])/rate(ataccama_one_grpc_client_call_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", method=~\"ProcessEvents|GetTermSuggestions|GetRestorationState|SetThreshold|GetThreshold|SetAdaptiveLearning|GetAdaptiveLearning\", status=\"OK\"}[$__rate_interval])",
     "legendFormat": "Avg {{method}}"
    }
   ]
  },
  {
   "title": "Resynchronization initialization status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "ataccama_one_mmm_term_suggestions_resynchronization_status{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Resynchronizations initialization time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ataccama_one_mmm_term_suggestions_resynchronization_setup_seconds_max{clusterName=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "Maximal"
    },
    {
     "expr": "rate(ataccama_one_mmm_term_suggestions_resynchronization_setup_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_term_suggestions_resynchronization_setup_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "MMM term suggestions update",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Term suggestions update rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_updated_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Received update data rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_update_received_attributes_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "Total received attributes"
      },
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_update_received_attributes_with_terms_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])  ",
       "legendFormat": "Attributes with terms"
      },
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_update_received_batches_non_empty_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "Non empty batches"
      },
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_update_received_terms_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "Total received suggested terms"
      }
     ]
    },
    {
     "title": "Term suggestions update time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ataccama_one_mmm_term_suggestions_update_seconds_max{clusterName=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "Maximal"
      },
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_update_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) / rate(ataccama_one_mmm_term_suggestions_update_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Nonexistent entities for update",
     "type": "timeseries",
     "description": "Note: number of terms isn't unique - one term can be counted multiple times if suggested on multiple attributes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_update_attributes_non_existent_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "Attributes"
      },
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_update_terms_non_existent_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "Terms"
      }
     ]
    }
   ]
  },
  {
   "title": "MMM outbox",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of outbox item save from core events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_outbox_save_items_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Unsent outbox items",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "ataccama_one_mmm_term_suggestions_outbox_unsent_items{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Outbox item dispatch rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_outbox_dispatch_items_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Failed dispatch rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_outbox_dispatch_failed_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Overall dispatch time",
     "type": "timeseries",
     "description": "The time consists of fetching outbox items, processing those items (fetching needed data + mapping) and sending to ai service",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_outbox_dispatch_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) / rate(ataccama_one_mmm_term_suggestions_outbox_dispatch_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "Average"
      },
      {
       "expr": "ataccama_one_mmm_term_suggestions_outbox_dispatch_seconds_max{clusterName=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "Maximal"
      }
     ]
    },
    {
     "title": "Processed outbox items rate per entity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_outbox_dispatch_processing_entity_updated_items_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{entity}}"
      }
     ]
    },
    {
     "title": "Outbox item processing time per entity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ataccama_one_mmm_term_suggestions_outbox_dispatch_processing_entity_updated_seconds_max{clusterName=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{entity}} max"
      },
      {
       "expr": "rate(ataccama_one_mmm_term_suggestions_outbox_dispatch_processing_entity_updated_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_term_suggestions_outbox_dispatch_processing_entity_updated_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{entity}} average"
      }
     ]
    }
   ]
  },
  {
   "title": "Overall statistics - not for specific cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distribution of metrics versions in all clusters",
     "type": "piechart",
     "description": "How much are different versions of the metrics used (number of clusters having at least microservice with that version).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg(ataccama_one_aicore_microservice_info) by(clusterName))",
       "legendFormat": "13.1"
      },
      {
       "expr": "count(avg(ataccama_one_aicore_microservice_microservice_info) by(clusterName))",
       "legendFormat": "13.3 \"local\""
      },
      {
       "expr": "count(avg(ataccama_one_aicore_recommender_microservice_microservice_info) by(clusterName))",
       "legendFormat": "13.4"
      },
      {
       "expr": "count(avg(ataccama_one_term_suggestions_recommender_microservice_microservice_info) by(clusterName))",
       "legendFormat": "13.6"
      }
     ]
    },
    {
     "title": "Distribution of microservices versions in all clusters",
     "type": "piechart",
     "description": "How many clusters operate on which version of the Term Suggestions services.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg(ataccama_one_aicore_microservice_info) by (clusterName, version)) by(version)",
       "legendFormat": "{{version}}"
      },
      {
       "expr": "count(avg(ataccama_one_aicore_microservice_microservice_info) by (clusterName, version)) by(version)",
       "legendFormat": "{{version}}"
      },
      {
       "expr": "count(avg(ataccama_one_aicore_recommender_microservice_microservice_info) by (clusterName, version)) by(version)",
       "legendFormat": "{{version}}"
      },
      {
       "expr": "count(avg(ataccama_one_term_suggestions_recommender_microservice_microservice_info) by (clusterName, version)) by(version)"
      }
     ]
    },
    {
     "title": "Clusters with metrics version - 13.1",
     "type": "piechart",
     "description": "Distribution of versions of microservices among clusters",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg(ataccama_one_aicore_microservice_info) by (clusterName, version)) by(clusterName, version)",
       "legendFormat": "{{clusterName}} - {{version}}"
      }
     ]
    },
    {
     "title": "Clusters with metrics version - 13.3 \"local\"",
     "type": "piechart",
     "description": "Distribution of versions of microservices among clusters",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg(ataccama_one_aicore_microservice_microservice_info) by (clusterName, version)) by(clusterName, version)",
       "legendFormat": "{{clusterName}} - {{version}}"
      }
     ]
    },
    {
     "title": "Clusters with metrics version - 13.4",
     "type": "piechart",
     "description": "Distribution of versions of microservices among clusters",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg(ataccama_one_aicore_recommender_microservice_microservice_info) by (clusterName, version)) by(clusterName, version)",
       "legendFormat": "{{clusterName}} - {{version}}"
      }
     ]
    },
    {
     "title": "Clusters with metrics version - 13.6",
     "type": "piechart",
     "description": "Distribution of versions of microservices among clusters",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg(ataccama_one_term_suggestions_recommender_microservice_microservice_info) by (clusterName, version)) by(clusterName, version)",
       "legendFormat": "{{clusterName}} - {{version}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Term Suggestions - General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attributes in AI DBs per namespace",
     "type": "bargauge",
     "description": "Number of profiled attributes (with fingerprints) in the AI DB for each namespace. (It can have non-integer values, probably due to Thanos compression of past measurements)",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ataccama_one_aicore_ai_ts_neighbors_database_attributes_present{clusterName=~\"$cluster\"}) without(instance, pod)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(ataccama_one_aicore_neighbors_database_attributes_present{clusterName=~\"$cluster\"}) without(instance, pod)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(ataccama_one_term_suggestions_neighbors__database_attributes_present{clusterName=~\"$cluster\"}) without(instance, pod)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Feedbacks processed in total per namespace",
     "type": "bargauge",
     "description": "Number of feedback from users processed in total for each namespace.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ataccama_one_aicore_ai_ts_feedback_feedbacks_total{clusterName=~\"$cluster\"}) without(instance, pod, type)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(ataccama_one_aicore_feedback_feedbacks_total{clusterName=~\"$cluster\"}) without(instance, pod, type)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(ataccama_one_term_suggestions_feedback__feedbacks_total{clusterName=~\"$cluster\"}) without(instance, pod, type)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Number of instances of each microservice running at given time",
     "type": "timeseries",
     "description": "Number of instances of each microservice running at given time for a given cluster and namespace. BEWARE: The dashboards are not prepared for multiple instances of the same microservice running in parallel!",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "count(ataccama_one_aicore_microservice_info{clusterName=~\"$cluster\", namespace=~\"$namespace\"})without(instance, pod)",
       "legendFormat": "{{name}} - {{version}}"
      },
      {
       "expr": "count(ataccama_one_aicore_microservice_microservice_info{clusterName=~\"$cluster\", namespace=~\"$namespace\"})without(instance, pod)",
       "legendFormat": "{{name}} - {{version}}"
      },
      {
       "expr": "count(ataccama_one_aicore_recommender_microservice_microservice_info{clusterName=~\"$cluster\", namespace=~\"$namespace\"})without(instance, pod)",
       "legendFormat": "{{name}} - {{version}}"
      },
      {
       "expr": "count(ataccama_one_aicore_neighbors_microservice_microservice_info{clusterName=~\"$cluster\", namespace=~\"$namespace\"})without(instance, pod)",
       "legendFormat": "{{name}} - {{version}}"
      },
      {
       "expr": "count(ataccama_one_aicore_feedback_microservice_microservice_info{clusterName=~\"$cluster\", namespace=~\"$namespace\"})without(instance, pod)",
       "legendFormat": "{{name}} - {{version}}"
      },
      {
       "expr": "count(ataccama_one_term_suggestions_recommender_microservice_microservice_info{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(instance, pod)",
       "legendFormat": "{{name}} - {{version}}"
      },
      {
       "expr": "count(ataccama_one_term_suggestions_neighbors_microservice_microservice_info{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(instance, pod)",
       "legendFormat": "{{name}} - {{version}}"
      },
      {
       "expr": "count(ataccama_one_term_suggestions_feedback_microservice_microservice_info{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(instance, pod)",
       "legendFormat": "{{name}} - {{version}}"
      }
     ]
    },
    {
     "title": "Distribution of microservices versions in current cluster",
     "type": "piechart",
     "description": "What versions of services are used at given cluster.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ataccama_one_aicore_microservice_info{clusterName=~\"$cluster\"})by(version)",
       "legendFormat": "{{version}}"
      },
      {
       "expr": "count(ataccama_one_aicore_microservice_microservice_info{clusterName=~\"$cluster\"})by(version)",
       "legendFormat": "{{version}}"
      },
      {
       "expr": "count(ataccama_one_aicore_recommender_microservice_microservice_info{clusterName=~\"$cluster\"})by(version)",
       "legendFormat": "{{version}}"
      },
      {
       "expr": "count(ataccama_one_term_suggestions_recommender_microservice_microservice_info{clusterName=~\"$cluster\"}) by(version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Services versions in cluster and namespace",
     "type": "piechart",
     "description": "What versions of services are used at given cluster and namespace.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ataccama_one_aicore_microservice_info{clusterName=~\"$cluster\", namespace=~\"$namespace\"})by(version, name)"
      },
      {
       "expr": "count(ataccama_one_aicore_microservice_microservice_info{clusterName=~\"$cluster\", namespace=~\"$namespace\"})by(version, name)"
      },
      {
       "expr": "count(ataccama_one_aicore_recommender_microservice_microservice_info{clusterName=~\"$cluster\", namespace=~\"$namespace\"})by(version, name)"
      },
      {
       "expr": "count(ataccama_one_term_suggestions_recommender_microservice_microservice_info{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) by(version, name)"
      }
     ]
    },
    {
     "title": "Attributes in AI DB",
     "type": "stat",
     "description": "Number of profiled attributes (with fingerprints) in the AI DB.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ataccama_one_aicore_ai_ts_neighbors_database_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(instance, pod)"
      },
      {
       "expr": "sum(ataccama_one_aicore_neighbors_database_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(instance, pod)"
      },
      {
       "expr": "sum(ataccama_one_term_suggestions_neighbors__database_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(instance, pod)"
      }
     ]
    },
    {
     "title": "Index fill",
     "type": "gauge",
     "description": "How much filled is the Neighbors index (relative to its  configured capacity). If it reaches 100%, the microservice stop working and the capacity will need to be increased (together with memory requirements of the service).",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ataccama_one_aicore_ai_ts_neighbors_index_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(pod, instance) ataccama_one_aicore_ai_ts_neighbors_index_attributes_limit{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "ataccama_one_aicore_neighbors_index_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(pod, instance) ataccama_one_aicore_neighbors_index_attributes_limit{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "ataccama_one_term_suggestions_neighbors__index_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(pod, instance) ataccama_one_term_suggestions_neighbors__index_attributes_limit{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Percentage of disabled terms",
     "type": "gauge",
     "description": "Number of terms for which AI suggestions are disabled / number of terms we could theoretically provide suggestions for. ",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ataccama_one_aicore_ai_ts_recommender_terms_disabled{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(instance, pod) (ataccama_one_aicore_ai_ts_recommender_terms_known{clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ataccama_one_aicore_ai_ts_recommender_terms_disabled{clusterName=~\"$cluster\", namespace=~\"$namespace\"})"
      },
      {
       "expr": "ataccama_one_aicore_recommender_terms_disabled{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(instance, pod) (ataccama_one_aicore_recommender_terms_known{clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ataccama_one_aicore_recommender_terms_disabled{clusterName=~\"$cluster\", namespace=~\"$namespace\"})"
      },
      {
       "expr": "ataccama_one_term_suggestions_recommender__terms_disabled{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(instance, pod) (ataccama_one_term_suggestions_recommender__terms_known{clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ataccama_one_term_suggestions_recommender__terms_disabled{clusterName=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Percentage of attributes with assignments",
     "type": "gauge",
     "description": "How many profiled attributes do have at least one term assigned.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ataccama_one_aicore_ai_ts_recommender_recommendation_progress_with_ground_truth{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(instance, pod)ataccama_one_aicore_ai_ts_recommender_recommendation_progress{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "ataccama_one_aicore_recommender_recommendation_progress_with_ground_truth{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(instance, pod)ataccama_one_aicore_recommender_recommendation_progress{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "ataccama_one_term_suggestions_recommender__recommendation_progress_with_ground_truth{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(instance, pod)ataccama_one_term_suggestions_recommender__recommendation_progress{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "DB operations durations",
     "type": "timeseries",
     "description": "Durations of various DB queries.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "rate(ataccama_one_aicore_database_query_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) / on(operation, component, instance) rate(ataccama_one_aicore_database_query_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{operation}}, {{component}}"
      },
      {
       "expr": "rate(ataccama_one_aicore_neighbors_database_query_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) / on(operation, component, instance) rate(ataccama_one_aicore_neighbors_database_query_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{operation}}, {{component}}"
      },
      {
       "expr": "rate(ataccama_one_aicore_recommender_database_query_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) / on(operation, component, instance) rate(ataccama_one_aicore_recommender_database_query_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{operation}}, {{component}}"
      },
      {
       "expr": "rate(ataccama_one_aicore_feedback_database_query_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) / on(operation, component, instance) rate(ataccama_one_aicore_feedback_database_query_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{operation}}, {{component}}"
      },
      {
       "expr": "rate(ataccama_one_term_suggestions_neighbors_database_query_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) / on(operation, component, instance) rate(ataccama_one_term_suggestions_neighbors_database_query_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{operation}}, {{component}}"
      },
      {
       "expr": "rate(ataccama_one_term_suggestions_recommender_database_query_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) / on(operation, component, instance) rate(ataccama_one_term_suggestions_recommender_database_query_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{operation}}, {{component}}"
      },
      {
       "expr": "rate(ataccama_one_term_suggestions_feedback_database_query_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) / on(operation, component, instance) rate(ataccama_one_term_suggestions_feedback_database_query_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{operation}}, {{component}}"
      },
      {
       "expr": "rate(ataccama_one_term_suggestions_api_database_query_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) / on(operation, component, instance) rate(ataccama_one_term_suggestions_api_database_query_seconds_count{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{operation}}, {{component}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Term Suggestions - API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "TS API call rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "rate(ataccama_one_term_suggestions_api_grpc_server_commands_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Restoration state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "ataccama_one_term_suggestions_api__restoration_is_running{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Term Suggestions - Recommender",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recommendation starts per hour",
     "type": "timeseries",
     "description": "How often is the recommendation process restarted, per hour (i.e. all the suggestions need to be recomputed because there is some change in underlying data).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "rate(ataccama_one_aicore_ai_ts_recommender_recommendation_starts_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) * 3600"
      },
      {
       "expr": "rate(ataccama_one_aicore_recommender_recommendation_starts_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) * 3600"
      },
      {
       "expr": "rate(ataccama_one_term_suggestions_recommender__recommendation_starts_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) * 3600"
      }
     ]
    },
    {
     "title": "Attributes with outdated suggestions",
     "type": "timeseries",
     "description": "How many attributes do not have up-to-date suggestions - they should be eventually recomputed. [There is currently a bug in this metric so this number does not have to go to 0] ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "ataccama_one_aicore_ai_ts_neighbors_index_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"} - on(clusterName) ataccama_one_aicore_ai_ts_recommender_recommendation_progress{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "ataccama_one_aicore_neighbors_index_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"} - on(clusterName) ataccama_one_aicore_recommender_recommendation_progress{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "ataccama_one_term_suggestions_neighbors__index_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"} - on(clusterName) ataccama_one_term_suggestions_recommender__recommendation_progress{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Rate of neighbors calculation",
     "type": "timeseries",
     "description": "Number of attributes for which neighbors were calculated per second spent in the query.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "increase(ataccama_one_aicore_ai_ts_neighbors_neighbors_distances_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", k=\"1\"}[$__rate_interval]) / on(instance)increase(ataccama_one_aicore_grpc_server_processing_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\", service=\"aicore-neighbors-svc\", stage=\"processing\"}[$__rate_interval])"
      },
      {
       "expr": "increase(ataccama_one_aicore_neighbors_neighbors_distances_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", k=\"1\"}[$__rate_interval]) / on(instance)increase(ataccama_one_aicore_neighbors_grpc_server_processing_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\", service=\"aicore-neighbors-svc\", stage=\"processing\"}[$__rate_interval])"
      },
      {
       "expr": "increase(ataccama_one_term_suggestions_neighbors__neighbors_distances_count{clusterName=~\"$cluster\", namespace=~\"$namespace\", k=\"1\"}[$__rate_interval]) / on(instance)increase(ataccama_one_term_suggestions_neighbors_grpc_server_processing_seconds_sum{clusterName=~\"$cluster\", namespace=~\"$namespace\", stage=\"processing\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Rate of attribute processing",
     "type": "timeseries",
     "description": "Number of processed attributes (i.e. their suggestions are recomputed) per second (of real time). Note: This is an underestimation because the processing might not run all the time, but the time is still taken into account.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ataccama_one_aicore_ai_ts_recommender_attributes_processed_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])"
      },
      {
       "expr": "rate(ataccama_one_aicore_recommender_attributes_processed_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])"
      },
      {
       "expr": "rate(ataccama_one_term_suggestions_recommender__attributes_processed_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Suggestions per attribute",
     "type": "stat",
     "description": "Average number of suggestions suggested per attribute.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ataccama_one_aicore_ai_ts_recommender_suggestions_created_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(instance, pod)ataccama_one_aicore_ai_ts_recommender_attributes_processed_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "ataccama_one_aicore_recommender_suggestions_created_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(instance, pod)ataccama_one_aicore_recommender_attributes_processed_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "ataccama_one_term_suggestions_recommender__suggestions_created_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(instance, pod)ataccama_one_term_suggestions_recommender__attributes_processed_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Database and index fill",
     "type": "timeseries",
     "description": "How many attributes are in the database (including deleted), index and what is the index limit.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(ataccama_one_aicore_ai_ts_neighbors_database_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance) ",
       "legendFormat": "database"
      },
      {
       "expr": "sum(ataccama_one_aicore_ai_ts_neighbors_index_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance) ",
       "legendFormat": "index"
      },
      {
       "expr": "sum(ataccama_one_aicore_ai_ts_neighbors_index_attributes_limit{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance) ",
       "legendFormat": "limit"
      },
      {
       "expr": "sum(ataccama_one_aicore_neighbors_database_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance) ",
       "legendFormat": "database"
      },
      {
       "expr": "sum(ataccama_one_aicore_neighbors_index_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance) ",
       "legendFormat": "index"
      },
      {
       "expr": "sum(ataccama_one_aicore_neighbors_index_attributes_limit{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance) ",
       "legendFormat": "limit"
      },
      {
       "expr": "sum(ataccama_one_term_suggestions_neighbors__database_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance) ",
       "legendFormat": "database"
      },
      {
       "expr": "sum(ataccama_one_term_suggestions_neighbors__index_attributes_present{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance) ",
       "legendFormat": "index"
      },
      {
       "expr": "sum(ataccama_one_term_suggestions_neighbors__index_attributes_limit{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance) ",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Confusion matrix derivations",
     "type": "timeseries",
     "description": "Statistics derived from the confusion matrix.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(2 * ataccama_one_aicore_ai_ts_recommender_suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"}) / ignoring(entry) (2 * ataccama_one_aicore_ai_ts_recommender_suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ignoring(entry) ataccama_one_aicore_ai_ts_recommender_suggestions_confusion_matrix{entry=\"false_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ignoring(entry) ataccama_one_aicore_ai_ts_recommender_suggestions_confusion_matrix{entry=\"false_negative\", clusterName=~\"$cluster\", namespace=~\"$namespace\"})",
       "legendFormat": "F1 score"
      },
      {
       "expr": "ataccama_one_aicore_ai_ts_recommender_suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(entry) (ataccama_one_aicore_ai_ts_recommender_suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ignoring(entry) ataccama_one_aicore_ai_ts_recommender_suggestions_confusion_matrix{entry=\"false_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"})",
       "legendFormat": "Precision"
      },
      {
       "expr": "ataccama_one_aicore_ai_ts_recommender_suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(entry) (ataccama_one_aicore_ai_ts_recommender_suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ignoring(entry) ataccama_one_aicore_ai_ts_recommender_suggestions_confusion_matrix{entry=\"false_negative\", clusterName=~\"$cluster\", namespace=~\"$namespace\"})",
       "legendFormat": "Recall"
      },
      {
       "expr": "(2 * ataccama_one_aicore_recommender_suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"}) / ignoring(entry) (2 * ataccama_one_aicore_recommender_suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ignoring(entry) ataccama_one_aicore_recommender_suggestions_confusion_matrix{entry=\"false_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ignoring(entry) ataccama_one_aicore_recommender_suggestions_confusion_matrix{entry=\"false_negative\", clusterName=~\"$cluster\", namespace=~\"$namespace\"})",
       "legendFormat": "F1 score"
      },
      {
       "expr": "ataccama_one_aicore_recommender_suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(entry) (ataccama_one_aicore_recommender_suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ignoring(entry) ataccama_one_aicore_recommender_suggestions_confusion_matrix{entry=\"false_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"})",
       "legendFormat": "Precision"
      },
      {
       "expr": "ataccama_one_aicore_recommender_suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(entry) (ataccama_one_aicore_recommender_suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ignoring(entry) ataccama_one_aicore_recommender_suggestions_confusion_matrix{entry=\"false_negative\", clusterName=~\"$cluster\", namespace=~\"$namespace\"})",
       "legendFormat": "Recall"
      },
      {
       "expr": "(2 * ataccama_one_term_suggestions_recommender__suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"}) / ignoring(entry) (2 * ataccama_one_term_suggestions_recommender__suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ignoring(entry) ataccama_one_term_suggestions_recommender__suggestions_confusion_matrix{entry=\"false_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ignoring(entry) ataccama_one_term_suggestions_recommender__suggestions_confusion_matrix{entry=\"false_negative\", clusterName=~\"$cluster\", namespace=~\"$namespace\"})",
       "legendFormat": "F1 score"
      },
      {
       "expr": "ataccama_one_term_suggestions_recommender__suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(entry) (ataccama_one_term_suggestions_recommender__suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ignoring(entry) ataccama_one_term_suggestions_recommender__suggestions_confusion_matrix{entry=\"false_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"})",
       "legendFormat": "Precision"
      },
      {
       "expr": "ataccama_one_term_suggestions_recommender__suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(entry) (ataccama_one_term_suggestions_recommender__suggestions_confusion_matrix{entry=\"true_positive\", clusterName=~\"$cluster\", namespace=~\"$namespace\"} + ignoring(entry) ataccama_one_term_suggestions_recommender__suggestions_confusion_matrix{entry=\"false_negative\", clusterName=~\"$cluster\", namespace=~\"$namespace\"})",
       "legendFormat": "Recall"
      }
     ]
    },
    {
     "title": "Confusion matrix",
     "type": "stat",
     "description": "Confusion matrix of the term suggestions process. false_negative: We should be suggesting (term is already assigned manually), but we are not.\n false_positive: We probably shouldn't be suggesting (no term was manually assigned), but we are [This number can be overestimated!]\ntrue_negative: We are probably correctly not suggesting as there are no terms assigned [This number can be underestimated!]\ntrue_positive: We are correctly suggesting and the term was manually confirmed = assigned.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ataccama_one_aicore_ai_ts_recommender_suggestions_confusion_matrix{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(entry) group_left sum(ataccama_one_aicore_ai_ts_recommender_suggestions_confusion_matrix{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(entry)) without(pod, instance)",
       "legendFormat": "{{entry}}"
      },
      {
       "expr": "sum(ataccama_one_aicore_recommender_suggestions_confusion_matrix{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(entry) group_left sum(ataccama_one_aicore_recommender_suggestions_confusion_matrix{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(entry)) without(pod, instance)",
       "legendFormat": "{{entry}}"
      },
      {
       "expr": "sum(ataccama_one_term_suggestions_recommender__suggestions_confusion_matrix{clusterName=~\"$cluster\", namespace=~\"$namespace\"} / ignoring(entry) group_left sum(ataccama_one_term_suggestions_recommender__suggestions_confusion_matrix{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(entry)) without(pod, instance)",
       "legendFormat": "{{entry}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Term Suggestions - Neighbors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance distribution for given neighbor over time",
     "type": "heatmap",
     "description": "Distribution of distances of the k-th neighbor in a recent batch of queries.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(increase(ataccama_one_aicore_ai_ts_neighbors_neighbors_distances_bucket{k=\"$neighbor\", clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])  / ignoring(le) group_left increase(ataccama_one_aicore_ai_ts_neighbors_neighbors_distances_count{k=\"$neighbor\", clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) without(pod, instance)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(ataccama_one_aicore_neighbors_neighbors_distances_bucket{k=\"$neighbor\", clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])  / ignoring(le) group_left increase(ataccama_one_aicore_neighbors_neighbors_distances_count{k=\"$neighbor\", clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) without(pod, instance)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(ataccama_one_term_suggestions_neighbors__neighbors_distances_bucket{k=\"$neighbor\", clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])  / ignoring(le) group_left increase(ataccama_one_term_suggestions_neighbors__neighbors_distances_count{k=\"$neighbor\", clusterName=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) without(pod, instance)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Cumulative (since last restart) distance distribution for given neighbor",
     "type": "bargauge",
     "description": "Distribution of distances of k-th neighbor since the last Neighbors service restart.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ataccama_one_aicore_ai_ts_neighbors_neighbors_distances_bucket{k=\"$neighbor\", clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(ataccama_one_aicore_neighbors_neighbors_distances_bucket{k=\"$neighbor\", clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(ataccama_one_term_suggestions_neighbors__neighbors_distances_bucket{k=\"$neighbor\", clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Term Suggestions - Feedback",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Feedbacks processed total",
     "type": "timeseries",
     "description": "How many feedbacks were processed since the last restart of the Feedback service.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "ataccama_one_aicore_ai_ts_feedback_feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "ataccama_one_aicore_feedback_feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "ataccama_one_term_suggestions_feedback__feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Accepted suggestions ratio",
     "type": "stat",
     "description": "Percentage of positive feedbacks (accepted suggestions) to all feedbacks (accepted + rejected).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ataccama_one_aicore_ai_ts_feedback_feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"positive\"} / ignoring(type) (ataccama_one_aicore_ai_ts_feedback_feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"positive\"} + ignoring(type) ataccama_one_aicore_ai_ts_feedback_feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"negative\"}) * 100"
      },
      {
       "expr": "ataccama_one_aicore_feedback_feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"positive\"} / ignoring(type) (ataccama_one_aicore_feedback_feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"positive\"} + ignoring(type) ataccama_one_aicore_feedback_feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"negative\"}) * 100"
      },
      {
       "expr": "ataccama_one_term_suggestions_feedback__feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"positive\"} / ignoring(type) (ataccama_one_term_suggestions_feedback__feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"positive\"} + ignoring(type) ataccama_one_term_suggestions_feedback__feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"negative\"}) * 100"
      }
     ]
    },
    {
     "title": "Rate of feedbacks processing",
     "type": "timeseries",
     "description": "Number of processed feedbacks per second (of real time). Note: This is an underestimation because the processing might not run all the time, but the time is still taken into account.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ataccama_one_aicore_ai_ts_feedback_feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"positive\"}[$__rate_interval]) + ignoring(type) rate(ataccama_one_aicore_ai_ts_feedback_feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"negative\"}[$__rate_interval])"
      },
      {
       "expr": "rate(ataccama_one_aicore_feedback_feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"positive\"}[$__rate_interval]) + ignoring(type) rate(ataccama_one_aicore_feedback_feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"negative\"}[$__rate_interval])"
      },
      {
       "expr": "rate(ataccama_one_term_suggestions_feedback__feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"positive\"}[$__rate_interval]) + ignoring(type) rate(ataccama_one_term_suggestions_feedback__feedbacks_total{clusterName=~\"$cluster\", namespace=~\"$namespace\", type=\"negative\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Cumulative (since last restart) distribution of thresholds",
     "type": "bargauge",
     "description": "Distribution of thresholds (aggregated over terms) since the last Feedback service restart.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ataccama_one_aicore_ai_ts_feedback_thresholds_bucket{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(ataccama_one_aicore_feedback_thresholds_bucket{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(ataccama_one_term_suggestions_feedback__thresholds_bucket{clusterName=~\"$cluster\", namespace=~\"$namespace\"}) without(pod, instance)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}