{
 "title": "Ataccama / Gen 2 - MMM Catalog Search",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{clusterName=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "rate_interval",
    "label": "rate interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d,7d"
   },
   {
    "name": "scrape_interval",
    "label": "scrape interval",
    "query": "10s,15s,30s,1m,2m,3m,5m,10m,15m,30m"
   }
  ]
 },
 "panels": [
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Search queries count per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_es_query_duration_seconds_count{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "Search queries duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_query_duration_seconds_sum{namespace=~\"$namespace\"}[5m])/rate(ataccama_one_mmm_catalogsearch_es_query_duration_seconds_count{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "Average Search duration"
    },
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_summary_duration_seconds_sum{namespace=\"$namespace\"}[5m])/rate(ataccama_one_mmm_catalogsearch_es_summary_query_duration_seconds_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Average Summary duration"
    }
   ]
  },
  { "title": "Indexing & Event queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Catalog search event queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ataccama_one_mmm_catalogsearch_events_pending{namespace=~\"$namespace\"}",
     "legendFormat": "Waiting in queue"
    },
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_total{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "Created per minute"
    },
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_processed_total{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "Processed per minute"
    }
   ]
  },
  {
   "title": "Mean processed events per minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_processed_total{namespace=~\"$namespace\"}[$rate_interval]) > 0",
     "legendFormat": "Processed per minute"
    }
   ]
  },
  {
   "title": "Pending events now",
   "type": "stat",
   "description": "How many events are pending now",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ataccama_one_mmm_catalogsearch_events_pending{namespace=~\"$namespace\"}",
     "legendFormat": "Pending events count"
    }
   ]
  },
  {
   "title": "Processed events in the interval",
   "type": "stat",
   "description": "How many events are processed in selected interval",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_processed_total{namespace=~\"$namespace\"}[$__range]) > 0",
     "legendFormat": "Processed events count"
    }
   ]
  },
  {
   "title": "Event end to end latency",
   "type": "timeseries",
   "description": "From created to processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_events_end_to_end_latency_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_events_end_to_end_latency_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Failed events per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Number of events" }
   ],
   "targets": [
    {
     "expr": "max(rate(ataccama_one_mmm_catalogsearch_events_failed{namespace=~\"$namespace\"}[10m])) * 60",
     "legendFormat": "Permanently failed events per minute"
    },
    {
     "expr": "max(rate(ataccama_one_mmm_catalogsearch_events_partly_failed{namespace=~\"$namespace\"}[10m])) * 60",
     "legendFormat": "Failed events to retry per minute"
    }
   ]
  },
  {
   "title": "Event queue consumer duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_events_consumer_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_events_consumer_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Event queue consumer per TASK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_events_consumer_tasks_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_events_consumer_tasks_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ consumer }} :: {{ task }}"
    }
   ]
  },
  {
   "title": "Event queue poll per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_outbox_poll_seconds_count{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "Poll"
    }
   ]
  },
  {
   "title": "Event queue poll duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_outbox_poll_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_outbox_poll_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Average poll time"
    }
   ]
  },
  {
   "title": "Poll bulk event count",
   "type": "timeseries",
   "description": "Count of events in one poll",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_outbox_poll_bulk_items_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_outbox_poll_bulk_items_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Count of events in one poll"
    }
   ]
  },
  {
   "title": "Deduplication of events",
   "type": "timeseries",
   "description": "Statistics how many core events are transformed to number of events to be processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_core_published_sum{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "Published by core per minute"
    },
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_core_published_deduplicated_sum{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "Deduplicated published by core per minute"
    },
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_total{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "Stored into queue per minute"
    }
   ]
  },
  {
   "title": "Event queue worker threadpool queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "ataccama_one_mmm_scheduler_queue_size{namespace=~\"$namespace\",name=\"PersistentEventQueue-worker\"}",
     "legendFormat": "Queue size"
    }
   ]
  },
  {
   "title": "Poll bulk event count",
   "type": "stat",
   "description": "Count of events in one poll",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_outbox_poll_bulk_items_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_outbox_poll_bulk_items_count{namespace=~\"$namespace\"}[$__rate_interval]) > 0",
     "legendFormat": "Count of events in one poll"
    }
   ]
  },
  {
   "title": "Elastic optimistic version control stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 }
  },
  {
   "title": "Getting index locks queries duration",
   "type": "timeseries",
   "description": "How fast getting locks during indexing items is.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_index_document_seconds_sum{namespace=~\"$namespace\",task=\"gettingLocks\"}[5m])/rate(ataccama_one_mmm_catalogsearch_es_index_document_seconds_count{namespace=~\"$namespace\",task=\"gettingLocks\"}[5m])",
     "legendFormat": "Average duration"
    }
   ]
  },
  {
   "title": "Distribution of reindex operation",
   "type": "timeseries",
   "description": "Ratio between operations during indexing of data:\n- outdated => ES holds newer data\n- up-to-date => index does not make sense\n- postponed => index again but later to avoid inconsistency\n- processed => just indexed in ES",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_events_reindex_stats_items_sum{namespace=~\"$namespace\"}[5m])/rate(ataccama_one_mmm_catalogsearch_events_reindex_stats_items_count{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Getting delete locks queries duration ",
   "type": "timeseries",
   "description": "How fast getting locks during deleting items is.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_delete_document_seconds_sum{namespace=~\"$namespace\",task=\"gettingLocks\"}[5m])/rate(ataccama_one_mmm_catalogsearch_es_delete_document_seconds_count{namespace=~\"$namespace\",task=\"gettingLocks\"}[5m])",
     "legendFormat": "Average duration"
    }
   ]
  },
  {
   "title": "Update by query operation duration",
   "type": "timeseries",
   "description": "Duration of update by query operation with optimistic locking.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_update_by_query_version_conflicts_sum{namespace=~\"$namespace\"}[5m])/rate(ataccama_one_mmm_catalogsearch_es_update_by_query_version_conflicts_count{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "update by query"
    }
   ]
  },
  { "title": "Core data fetching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Fetch service : docs for entity queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_fetch_service_docs_for_entity_seconds_count{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "{{ entityType }}"
    }
   ]
  },
  {
   "title": "Fetch service : docs for entity average duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_fetch_service_docs_for_entity_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_fetch_service_docs_for_entity_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ entityType }}"
    }
   ]
  },
  {
   "title": "Fetch service : ids for entity queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_fetch_service_ids_for_entity_seconds_count{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "{{ entityType }}"
    }
   ]
  },
  {
   "title": "Fetch service : ids for entity average duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_fetch_service_ids_for_entity_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_fetch_service_ids_for_entity_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ entityType }}"
    }
   ]
  },
  {
   "title": "Fetch service : nodes queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_fetch_service_nodes_seconds_count{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "{{ pivotNode }}"
    }
   ]
  },
  {
   "title": "Fetch service : nodes average duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_fetch_service_nodes_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_fetch_service_nodes_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ pivotNode }}"
    }
   ]
  },
  {
   "title": "Core event handlers",
   "type": "timeseries",
   "description": "Handlers for core events used for search synchronization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(ataccama_one_mmm_catalogsearch_core_entity_published_consumer_seconds_count{namespace=~\"$namespace\"}[10m]))/10",
     "legendFormat": "EntityPublished"
    },
    {
     "expr": "sum(increase(ataccama_one_mmm_catalogsearch_core_permission_change_consumer_seconds_count{namespace=~\"$namespace\"}[10m]))/10"
    }
   ]
  },
  {
   "title": "Core event handlers average duration",
   "type": "timeseries",
   "description": "Handlers for core events used for search synchronization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_core_entity_published_consumer_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_core_entity_published_consumer_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "EntityPublished {{ task }}"
    },
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_core_permission_change_consumer_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_core_permission_change_consumer_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "PermissionChange {{ task }}"
    }
   ]
  },
  { "title": "Elasticsearch requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Elasticsearch requests per minute",
   "type": "timeseries",
   "description": "Read queries - search using template",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_es_request_seconds_count{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Elasticsearch raw requests duration",
   "type": "timeseries",
   "description": "Read queries - search using template",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_request_seconds_sum{namespace=~\"$namespace\"}[5m])/rate(ataccama_one_mmm_catalogsearch_es_request_seconds_count{namespace=~\"$namespace\"}[5m]) > 0 ",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Elasticsearch index and delete queries",
   "type": "timeseries",
   "description": "Elastic queries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_index_document_seconds_sum{namespace=~\"$namespace\"}[5m])/rate(ataccama_one_mmm_catalogsearch_es_index_document_seconds_count{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "index: {{ task }}"
    },
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_delete_document_seconds_sum{namespace=~\"$namespace\"}[5m])/rate(ataccama_one_mmm_catalogsearch_es_delete_document_seconds_count{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "delete: {{ task }}"
    }
   ]
  },
  {
   "title": "Elasticsearch bulk index request items count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_index_bulk_items_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_es_index_bulk_items_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Elasticsearch bulk request items count"
    }
   ]
  },
  {
   "title": "Elasticsearch bulk request payload size in bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_index_bulk_length_bytes_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_es_index_bulk_length_bytes_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Payload size in bytes"
    }
   ]
  },
  {
   "title": "Elasticsearch bulk request payload size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_index_bulk_length_bytes_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_es_index_bulk_length_bytes_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Payload size in bytes"
    }
   ]
  },
  {
   "title": "Elasticsearch bulk request chunks count",
   "type": "stat",
   "description": "Number of chunks in which bulk is divided",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_index_bulk_chuks_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_es_index_bulk_chuks_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Elasticsearch bulk request chunks count"
    }
   ]
  },
  {
   "title": "Elasticsearch bulk delete request payload size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_delete_bulk_length_bytes_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_es_delete_bulk_length_bytes_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Payload size in bytes"
    }
   ]
  },
  {
   "title": "Elasticsearch bulk delete request items count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 133 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_delete_bulk_items_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_es_delete_bulk_items_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Elasticsearch bulk delete request items count"
    }
   ]
  },
  {
   "title": "Elasticsearch bulk delete request payload size in bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_delete_bulk_length_bytes_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_es_delete_bulk_length_bytes_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Payload size in bytes"
    }
   ]
  },
  { "title": "Event queue maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "Event queue compaction per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_outbox_compaction_seconds_count{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "Compaction"
    }
   ]
  },
  {
   "title": "Event queue compaction duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_outbox_compaction_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_outbox_compaction_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Average compaction time"
    }
   ]
  },
  {
   "title": "Deleted & compacted events",
   "type": "timeseries",
   "description": "Event queue maintenance - compacted / deleted ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_compacted_total{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "Compacted"
    },
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_maintenance_deleted_total{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "Deleted {{ state }}"
    },
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_read_repaired_document_count_total{namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "Read repaired"
    }
   ]
  }
 ]
}