{
 "title": "Ataccama / Gen 2 - Application",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "schedulers",
    "query": {
     "query": "label_values(ataccama_one_mmm_scheduler_task_completed,name)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{clusterName=~\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GraphQL queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total GraphQL queries per minute",
   "type": "graph",
   "description": "Number of GQL calls per  minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Number of calls" }
   ],
   "targets": [
    {
     "expr": "sum(rate(graphql_timer_query_seconds_count{namespace=~\"$namespace\"} [5m])) * 60",
     "legendFormat": "Number of GQLs"
    }
   ]
  },
  {
   "title": "Slowest GQL Queries",
   "type": "graph",
   "description": "GQL queries over 3 second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "graphql_timer_query_seconds_max{namespace=~\"$namespace\"} > 3",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  {
   "title": "Number of GQL Queries per minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    {
     "format": "short",
     "label": "Number of GQL queries per minute"
    }
   ],
   "targets": [
    {
     "expr": "rate (graphql_timer_query_seconds_count{namespace=~\"$namespace\"} [5m]) * 60 > 0",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  {
   "title": "Time consumption of GQL queries",
   "type": "graph",
   "description": "Time spent in the function per hour.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    {
     "format": "s",
     "label": "Time spent in GQL query per hour"
    }
   ],
   "targets": [
    {
     "expr": "rate (graphql_timer_query_seconds_sum{namespace=~\"$namespace\"} [5m]) / rate (graphql_timer_query_seconds_count{namespace=~\"$namespace\"} [5m]) ",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  { "title": "Schedulers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Scheduler $schedulers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "repeat": "schedulers",
   "targets": [
    {
     "expr": "ataccama_one_mmm_scheduler_queue_size{name=\"$schedulers\", namespace=~\"$namespace\"}",
     "legendFormat": "Queue size"
    },
    {
     "expr": "rate (ataccama_one_mmm_scheduler_task_scheduled{name=\"$schedulers\", namespace=~\"$namespace\"} [5m]) * 60",
     "legendFormat": "Scheduled per minute"
    },
    {
     "expr": "rate (ataccama_one_mmm_scheduler_task_completed{name=\"$schedulers\", namespace=~\"$namespace\"} [5m]) * 60",
     "legendFormat": "Completed  per minute"
    },
    {
     "expr": "ataccama_one_mmm_scheduler_active{name=\"$schedulers\", namespace=~\"$namespace\"}",
     "legendFormat": "Running"
    }
   ]
  },
  { "title": "Thread pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Active threads",
   "type": "graph",
   "description": "Number of active threads in thread pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ataccama_one_mmm_threadpool_active{namespace=~\"$namespace\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Thread pool queue size",
   "type": "graph",
   "description": "Number of tasks waiting for the thread assignation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ataccama_one_mmm_threadpool_queue_size{namespace=~\"$namespace\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Long running threads",
   "type": "timeseries",
   "description": "Number of long-running threads",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "ataccama_one_mmm_threadmonitor_longrunning_count{namespace=~\"$namespace\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Duration of longest running thread",
   "type": "timeseries",
   "description": "Duration of longest running thread",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ataccama_one_mmm_threadmonitor_longrunning_longest_seconds{namespace=~\"$namespace\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "MMM Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Number of operations per minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "number of invocations" }
   ],
   "targets": [
    {
     "expr": "delta(ataccama_one_mmm_mdoperations_time_seconds_count{namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Slow internal calls",
   "type": "bargauge",
   "description": "Show pluggable routines  more than 3 seconds",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ataccama_one_mmm_mdtransactions_listener_time_seconds_max{namespace=~\"$namespace\"} > 3",
     "legendFormat": "{{listener}}  in pod {{pod}}"
    },
    {
     "expr": "ataccama_one_mmm_domainevents_handler_time_seconds_max{namespace=~\"$namespace\"} > 3",
     "legendFormat": "{{handler}} in pod {{pod}}"
    },
    {
     "expr": "ataccama_one_mmm_mdoperations_time_seconds_max{namespace=~\"$namespace\"} > 3",
     "legendFormat": "{{operation}} in pod {{pod}}"
    },
    {
     "expr": "ataccama_one_mmm_flow_handler_seconds_max{namespace=~\"$namespace\"} > 3",
     "legendFormat": "{{handler}} in pod {{pod}}"
    }
   ]
  },
  {
   "title": "Slow internal calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ataccama_one_mmm_mdtransactions_listener_time_seconds_max{namespace=~\"$namespace\"} > 3",
     "legendFormat": "{{listener}}"
    },
    {
     "expr": "ataccama_one_mmm_domainevents_handler_time_seconds_max{namespace=~\"$namespace\"} > 3 ",
     "legendFormat": "{{handler}}"
    },
    {
     "expr": "ataccama_one_mmm_mdoperations_time_seconds_max{namespace=~\"$namespace\"} > 3",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "ataccama_one_mmm_flow_handler_seconds_max{namespace=~\"$namespace\"} > 3",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "MD Trasactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Number of active MD transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "ataccama_one_mmm_mdtransactions_active{namespace=~\"$namespace\"}",
     "legendFormat": "Active transactions"
    }
   ]
  },
  {
   "title": "Transactions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_mdtransactions_time_seconds_count{namespace=~\"$namespace\"}[1m])",
     "legendFormat": "transaction per second"
    }
   ]
  },
  {
   "title": "Duration of MMM transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate (ataccama_one_mmm_mdtransactions_time_seconds_sum{namespace=~\"$namespace\"}[1m]) / rate (ataccama_one_mmm_mdtransactions_time_seconds_count{namespace=~\"$namespace\"}[1m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Max duration of MMM transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ataccama_one_mmm_mdtransactions_time_seconds_max{namespace=~\"$namespace\"}",
     "legendFormat": "max duration"
    }
   ]
  },
  { "title": "MMM - Jobs plugin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Time between Job status change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate (ataccama_one_mmm_jobs_duration_partial_seconds_sum{namespace=~\"$namespace\"} [5m]) / rate (ataccama_one_mmm_jobs_duration_partial_seconds_count{namespace=~\"$namespace\"} [5m])",
     "legendFormat": "{{type}}-({{status}}->{{exitStatus}})"
    }
   ]
  },
  {
   "title": "Number of new jobs per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "increase(ataccama_one_mmm_jobs_duration_partial_seconds_count{status=\"ENQUEUED\", exitStatus=\"RUNNING\", namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Finished MMM jobs per minute",
   "type": "graph",
   "description": "Number of jobs processed per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ataccama_one_mmm_jobs_duration_total_seconds_count{namespace=~\"$namespace\"}[5m])) by (type) * 60",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(rate(ataccama_one_mmm_jobs_duration_total_seconds_count{namespace=~\"$namespace\"}[5m])) * 60",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Finish by status per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "increase (ataccama_one_mmm_jobs_duration_partial_seconds_count{namespace=~\"$namespace\", status=\"RUNNING\", exitStatus=~\"FAILED|FINISHED\"}[1m])",
     "legendFormat": "{{type}}-{{exitStatus}}"
    }
   ]
  },
  {
   "title": "MMM Failed jobs per minute",
   "type": "graph",
   "description": "Number of jobs failed ina  minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(ataccama_one_mmm_jobs_duration_total_seconds_count{namespace=~\"$namespace\", exitStatus=\"FAILED\"} [5m])) by (type)) * 60",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "DPM plugin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events recieved from DPM  per minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Number of events" }
     ],
     "targets": [
      {
       "expr": "rate(ataccama_one_mmm_dpm_events_total[1m]) * 60",
       "legendFormat": "{{status}} - {{type}}"
      }
     ]
    },
    {
     "title": "DPM message size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes", "label": "size of DPM message" }
     ],
     "targets": [
      {
       "expr": "ataccama_one_mmm_dpm_result_size_bytes_max",
       "legendFormat": "max {{type}}"
      },
      {
       "expr": "sum(rate(ataccama_one_mmm_dpm_result_size_bytes_sum[5m])) by (type) / sum(rate(ataccama_one_mmm_dpm_result_size_bytes_count[5m])) by (type)",
       "legendFormat": "avg {{type}}"
      }
     ]
    },
    {
     "title": "DPM Application Jobs per state",
     "type": "timeseries",
     "description": "Number of jobs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "rate(ataccama_one_dpm_plugin_executor_jobs_count[5m])",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "MMM -> DPM GRPC Calls",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s", "label": "call duration" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ataccama_one_mmm_grpc_call_seconds_sum[5m])) / sum(rate(ataccama_one_mmm_grpc_call_seconds_count[5m]))",
       "legendFormat": "duration"
      },
      {
       "expr": "sum(rate(ataccama_one_mmm_grpc_call_seconds_count[1m]))",
       "legendFormat": "call per  minute"
      }
     ]
    }
   ]
  },
  { "title": "Profiling and DQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Processing of profiling message",
   "type": "graph",
   "description": "Breakdown of processing profiling messages to  phases",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_profiling_duration_seconds_sum{namespace=~\"$namespace\"} [5m]) / rate(ataccama_one_mmm_profiling_duration_seconds_count{namespace=~\"$namespace\"} [5m])",
     "legendFormat": "{{phase}}."
    },
    {
     "expr": "sum(rate(ataccama_one_mmm_profiling_duration_seconds_sum{namespace=~\"$namespace\"} [5m]) / rate(ataccama_one_mmm_profiling_duration_seconds_count{namespace=~\"$namespace\"} [5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Numbers of entities involved in DQ evaluation per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_dq_eval_volume_total{namespace=~\"$namespace\"}[5m]) * 60",
     "legendFormat": "{{type}} ({{parameter}})"
    }
   ]
  },
  {
   "title": "Number of attributes profiled per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_profiling_count_total{namespace=~\"$namespace\"}[5m]) * 60",
     "legendFormat": "Number of attributes"
    }
   ]
  },
  { "title": "Documentation flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "Phases duration",
   "type": "bargauge",
   "description": "How long take the processing of job type from the user perspective",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(ataccama_one_mmm_jobs_duration_total_seconds_sum{namespace=~\"$namespace\"}[10m]) / rate(ataccama_one_mmm_jobs_duration_total_seconds_count{namespace=~\"$namespace\"}[10m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Maximum duration of  processing DPM messages  in MMM",
   "type": "graph",
   "description": "Extreme values of DPM message processing.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ataccama_one_mmm_dpm_result_handler_time_seconds_max{namespace=~\"$namespace\"}",
     "legendFormat": "{{type}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Average duration of  processing DPM messages  in MMM",
   "type": "graph",
   "description": "Average duration of storing and processing data from DPM message",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate (ataccama_one_mmm_dpm_result_handler_time_seconds_sum [5m] ) / rate (ataccama_one_mmm_dpm_result_handler_time_seconds_count [5m])",
     "legendFormat": "AVG {{type}}"
    }
   ]
  },
  {
   "title": "DPE jobs processing",
   "type": "graph",
   "description": "Number of jobs being processed by each DPE",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    {
     "format": "short",
     "label": "Number of jobs processed in parallel"
    }
   ],
   "targets": [
    {
     "expr": "ataccama_one_dpe_plugin_executor_jobs_running{namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(ataccama_one_dpe_plugin_executor_jobs_running{namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPM Queue size",
   "type": "graph",
   "description": "Number of jobs processing in DPM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "yaxes": [
    {
     "format": "short",
     "label": "Number of jobs waiting in DPM oueue"
    }
   ],
   "targets": [
    {
     "expr": "max(ataccama_one_dpm_plugin_executor_jobs_count{namespace=~\"$namespace\", status=\"queued\"} )",
     "legendFormat": "Number of DPM jobs"
    },
    {
     "expr": "ataccama_one_dpm_plugin_executor_queue_size{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Top prioritized DPM job starvation",
   "type": "graph",
   "description": "Elapsed time since the creation of the most-prioritized unfinished job in the queue.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max (ataccama_one_dpm_plugin_executor_queue_jobs_top_priority_job_age_millis)",
     "legendFormat": "Waiting in queue"
    }
   ]
  },
  { "title": "Smart search - indexing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 } },
  {
   "title": "Catalog search event queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ataccama_one_mmm_catalogsearch_events_pending{namespace=~\"$namespace\"}",
     "legendFormat": "Waiting in queue"
    },
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_total{namespace=~\"$namespace\"}[1m])",
     "legendFormat": "Created per minute"
    },
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_processed_total{namespace=~\"$namespace\"}[1m])",
     "legendFormat": "Processed per minute"
    }
   ]
  },
  {
   "title": "Failed events per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "yaxes": [
    { "format": "short", "label": "Number of events" }
   ],
   "targets": [
    {
     "expr": "max(rate(ataccama_one_mmm_catalogsearch_events_failed{namespace=~\"$namespace\"} [10m])) * 60",
     "legendFormat": "Permanently failed events per minute"
    },
    {
     "expr": "max(rate(ataccama_one_mmm_catalogsearch_events_partly_failed{namespace=~\"$namespace\"}[10m])) * 60",
     "legendFormat": "Failed events to retry per minute"
    }
   ]
  },
  {
   "title": "Event queue consumers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_events_consumer_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_events_consumer_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Event queue consumer per TASK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_events_consumer_tasks_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_events_consumer_tasks_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ consumer }} :: {{ task }}"
    }
   ]
  },
  {
   "title": "Event queue maintenance",
   "type": "timeseries",
   "description": "Event queue maintenance - compacted / deleted ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_compacted_total{namespace=~\"$namespace\"}[1m])",
     "legendFormat": "Compacted"
    },
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_maintenance_deleted_total{namespace=~\"$namespace\"}[1m])",
     "legendFormat": "Deleted {{ state }}"
    },
    {
     "expr": "increase(ataccama_one_mmm_catalogsearch_events_read_repaired_document_count_total{namespace=~\"$namespace\"}[1m])",
     "legendFormat": "Read repaired"
    }
   ]
  },
  {
   "title": "Event queue poll time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_outbox_poll_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_outbox_poll_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Average poll time"
    }
   ]
  },
  {
   "title": "Core event handlers",
   "type": "timeseries",
   "description": "Handlers for core events used for search synchronization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_core_entity_published_consumer_seconds_sum{namespace=~\"$namespace\"}[5m])/rate(ataccama_one_mmm_catalogsearch_core_entity_published_consumer_seconds_count{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "EntityPublished {{ task }}"
    },
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_core_permission_change_consumer_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_core_permission_change_consumer_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "PermissionChange {{ task }}"
    }
   ]
  },
  { "title": "Smart search - elasticsearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 } },
  {
   "title": "Elasticsearch index and refresh queires",
   "type": "timeseries",
   "description": "Read queries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_index_document_seconds_sum{namespace=~\"$namespace\"}[5m])/rate(ataccama_one_mmm_catalogsearch_es_index_document_seconds_count{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Elasticsearch raw requests",
   "type": "timeseries",
   "description": "Read queries - search using template",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_query_duration_seconds_sum{namespace=~\"$namespace\"}[$__rate_interval])/rate(ataccama_one_mmm_catalogsearch_es_query_duration_seconds_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Search using template"
    },
    {
     "expr": "rate(ataccama_one_mmm_catalogsearch_es_request_seconds_sum{namespace=~\"$namespace\"}[5m])/rate(ataccama_one_mmm_catalogsearch_es_request_seconds_count{namespace=~\"$namespace\"}[5m]) > 0 ",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  { "title": "External events plugin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 } },
  {
   "title": "External events queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ataccama_one_mmm_externalevents_events_pending{namespace=~\"$namespace\"}",
     "legendFormat": "Waiting in queue"
    },
    {
     "expr": "max(rate(ataccama_one_mmm_externalevents_events_total{namespace=~\"$namespace\"}[5m])) * 60",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ataccama_one_mmm_externalevents_subscribers_online{namespace=~\"$namespace\"}",
     "legendFormat": "substcribers online"
    },
    {
     "expr": "rate(ataccama_one_mmm_externalevents_subscribers_total{namespace=~\"$namespace\"}[1h])",
     "legendFormat": "total subscribers"
    }
   ]
  },
  { "title": "AI - Anomally detection plugin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 207 } },
  {
   "title": "Anomally detection job latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate (ataccama_one_mmm_anomaly_detection_job_seconds_sum{namespace=~\"$namespace\"}[5m]) / rate (ataccama_one_mmm_anomaly_detection_job_seconds_count{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "Job  AVG"
    },
    {
     "expr": "rate (ataccama_one_mmm_anomaly_detection_history_fetch_seconds_sum{namespace=~\"$namespace\"}[5m]) / rate (ataccama_one_mmm_anomaly_detection_history_fetch_seconds_count{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "History fetch AVG"
    },
    {
     "expr": "ataccama_one_mmm_anomaly_detection_job_seconds_max{namespace=~\"$namespace\"}",
     "legendFormat": "Job MAX"
    },
    {
     "expr": "ataccama_one_mmm_anomaly_detection_history_fetch_seconds_max{namespace=~\"$namespace\"}",
     "legendFormat": "History fetch MAX"
    }
   ]
  },
  {
   "title": "Anomaly detection jobs throughtput",
   "type": "timeseries",
   "description": "Number of jobs per minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
   "targets": [
    {
     "expr": "rate (ataccama_one_mmm_anomaly_detection_job_seconds_count{namespace=~\"$namespace\"}[5m])*60",
     "legendFormat": "Anomally detection jobs"
    },
    {
     "expr": "rate (ataccama_one_mmm_anomaly_detection_history_fetch_seconds_count{namespace=~\"$namespace\"}[5m])*60",
     "legendFormat": "Fetch history"
    }
   ]
  },
  {
   "title": "Anomaly detection - queue size",
   "type": "timeseries",
   "description": "Number of attributes waiting for anomaly detection processing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
   "targets": [
    {
     "expr": "ataccama_one_mmm_anomaly_detection_queue_size{namespace=~\"$namespace\"}",
     "legendFormat": "Number of attributes waiting for anomaly detection "
    }
   ]
  }
 ]
}