{
 "title": "DPE jobs JVM",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{clusterName=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "dpe_job_name",
    "label": "dpe_job_name",
    "query": {
     "query": "label_values(ataccama_one_dpe_plugin_executor_jobs_running{namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "jobId",
    "label": "jobId",
    "query": {
     "query": "label_values(dqc_process_start_time_seconds{namespace=~\"$namespace\", job=~\"$dpe_job_name\"}, jobId)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\",area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\",  area=\"nonheap\"},id)"
    }
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": {
     "query": "label_values(jvm_buffer_memory_used_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\"},id)"
    }
   },
   {
    "name": "storage_type",
    "label": "Storage type",
    "query": {
     "query": "label_values(dqc_disk_total_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\"}, type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dqc_process_start_time_seconds{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dqc_process_uptime_seconds{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}"
    }
   ]
  },
  {
   "title": "CPU  usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dqc_process_cpu_usage{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dqc_jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", area=\"heap\"}) by (jobId) *100/sum(dqc_jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", area=\"heap\"}) by (jobId)"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dqc_jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", area=\"nonheap\"}) by (jobId) *100 /sum(dqc_jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", area=\"nonheap\"}) by (jobId)"
    }
   ]
  },
  {
   "title": "Space used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (dqc_directory_size_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}) by (jobId)"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(dqc_jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", area=\"heap\"}) by (jobId)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(dqc_jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", area=\"heap\"}) by (jobId)",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(dqc_jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", area=\"heap\"}) by (jobId)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(dqc_jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", area=\"nonheap\"}) by (jobId)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(dqc_jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", area=\"nonheap\"}) by (jobId)",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(dqc_jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", area=\"nonheap\"}) by (jobId)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(dqc_jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}) by (jobId)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(dqc_jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"})  by (jobId)",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(dqc_jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"})  by (jobId)",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dqc_system_cpu_usage{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}",
     "legendFormat": "system"
    },
    {
     "expr": "dqc_process_cpu_usage{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(dqc_process_cpu_usage{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}[15m])",
     "legendFormat": "process-15m"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dqc_system_load_average_1m{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "dqc_system_cpu_count{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dqc_jvm_threads_live_threads{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}",
     "legendFormat": "live"
    },
    {
     "expr": "dqc_jvm_threads_daemon_threads{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "dqc_jvm_threads_peak_threads{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dqc_jvm_threads_states_threads{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GC Pressure",
   "type": "timeseries",
   "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(dqc_jvm_gc_pause_seconds_sum{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}[1m])) by (job, jobId) / on (job, jobId) dqc_system_cpu_count",
     "legendFormat": "CPU time spent on GC"
    }
   ]
  },
  {
   "title": "Disk  usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dqc_disk_total_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", type=~\"$storage_type\", jobId=~\"$jobId\"}",
     "legendFormat": "Disk size"
    },
    {
     "expr": "dqc_disk_total_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", type=~\"$storage_type\", jobId=~\"$jobId\"} - dqc_disk_free_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", type=~\"$storage_type\", jobId=~\"$jobId\"}",
     "legendFormat": "Used space"
    },
    {
     "expr": "dqc_disk_free_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", type=~\"$storage_type\", jobId=~\"$jobId\"}",
     "legendFormat": "Free space"
    },
    {
     "expr": "dqc_directory_size_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}",
     "legendFormat": "{{type}} - {{path}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dqc_process_files_open_files{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}",
     "legendFormat": "open"
    },
    {
     "expr": "dqc_process_files_max_files{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "repeat": "jvm_memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dqc_jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "dqc_jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "dqc_jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "repeat": "jvm_memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dqc_jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "dqc_jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "dqc_jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(dqc_jvm_gc_pause_seconds_count{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(dqc_jvm_gc_pause_seconds_sum{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}[1m]) /rate(dqc_jvm_gc_pause_seconds_count{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "dqc_jvm_gc_pause_seconds_max{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(dqc_jvm_gc_memory_allocated_bytes_total{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}[1m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(dqc_jvm_gc_memory_promoted_bytes_total{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}[1m])",
     "legendFormat": "promoted"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dqc_jvm_classes_loaded_classes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(dqc_jvm_classes_loaded_classes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\"}[1m])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "$jvm_buffer_pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "repeat": "jvm_buffer_pool",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "dqc_jvm_buffer_memory_used_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "used"
    },
    {
     "expr": "dqc_jvm_buffer_total_capacity_bytes{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "capacity"
    },
    {
     "expr": "dqc_jvm_buffer_count_buffers{namespace=~\"$namespace\", job=~\"$dpe_job_name\", jobId=~\"$jobId\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "buffers"
    }
   ]
  }
 ]
}