{
 "title": "Gen 2 - Export / Import",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{clusterName=~\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running imports / exports",
   "type": "gauge",
   "description": "Number of imports / exports running right now",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ataccama_one_mmm_export_concurrent{namespace=~\"$namespace\"})",
     "legendFormat": "Running exports"
    },
    {
     "expr": "sum(ataccama_one_mmm_import_concurrent{namespace=~\"$namespace\"})",
     "legendFormat": "Running imports"
    }
   ]
  },
  {
   "title": "Import / export success rate",
   "type": "gauge",
   "description": "Percentage of successful exports",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ataccama_one_mmm_export_count_total{result=\"SUCCESS\", namespace=~\"$namespace\"}) / sum(ataccama_one_mmm_export_count_total{namespace=~\"$namespace\"})",
     "legendFormat": "Export success rate"
    },
    {
     "expr": "sum(ataccama_one_mmm_import_count_total{result=\"SUCCESS\", namespace=~\"$namespace\"}) / sum(ataccama_one_mmm_import_count_total{namespace=~\"$namespace\"})",
     "legendFormat": "Import success rate"
    }
   ]
  },
  {
   "title": "Export / import records count",
   "type": "gauge",
   "description": "Number of records exported / imported since last restart",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ataccama_one_mmm_export_entities_total{namespace=~\"$namespace\"})",
     "legendFormat": "Records exported"
    },
    {
     "expr": "sum(ataccama_one_mmm_import_entities_total{namespace=~\"$namespace\"})",
     "legendFormat": "Records imported"
    }
   ]
  },
  {
   "title": "Number of files",
   "type": "gauge",
   "description": "Number of files exported / imported",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ataccama_one_mmm_export_plugin_file_total{namespace=~\"$namespace\"})",
     "legendFormat": "Files exported"
    },
    {
     "expr": "sum(ataccama_one_mmm_import_plugin_file_total{namespace=~\"$namespace\"})",
     "legendFormat": "Files imported"
    }
   ]
  },
  { "title": "Concurrent runs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Concurrent running exports",
   "type": "timeseries",
   "description": "Number of exports running concurrently",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ataccama_one_mmm_export_concurrent{namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "ataccama_one_mmm_export_concurrent{namespace=~\"$namespace\"}",
     "legendFormat": "Instance {{instance}}"
    }
   ]
  },
  {
   "title": "Concurrent running imports",
   "type": "timeseries",
   "description": "Number of imports running concurrently",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum (ataccama_one_mmm_import_concurrent{namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "ataccama_one_mmm_import_concurrent{namespace=~\"$namespace\"}",
     "legendFormat": "instance {{instance}}"
    }
   ]
  },
  {
   "title": "Export component duration breakdown",
   "type": "timeseries",
   "description": "Time spend in components during export",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(ataccama_one_mmm_export_time_seconds_sum{namespace=~\"$namespace\"}[1m])) / sum(rate(ataccama_one_mmm_export_time_seconds_count{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(ataccama_one_mmm_export_core_time_seconds_sum{namespace=~\"$namespace\"}[1m])) / sum(rate(ataccama_one_mmm_export_core_time_seconds_count{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Core"
    },
    {
     "expr": "sum by (plugin) (rate(ataccama_one_mmm_export_plugin_time_seconds_sum{namespace=~\"$namespace\"}[1m])) / sum by (plugin) (rate(ataccama_one_mmm_export_plugin_time_seconds_count{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Plugin  {{plugin}}"
    }
   ]
  },
  {
   "title": "Import component duration breakdown",
   "type": "timeseries",
   "description": "Time spend on components during import",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(ataccama_one_mmm_import_time_seconds_sum{namespace=~\"$namespace\"}[1m])) / sum(rate(ataccama_one_mmm_import_time_seconds_count{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(ataccama_one_mmm_import_core_time_seconds_sum{namespace=~\"$namespace\"}[1m])) / sum(rate(ataccama_one_mmm_import_core_time_seconds_count{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Core"
    },
    {
     "expr": "sum by (plugin) (rate(ataccama_one_mmm_import_plugin_time_seconds_sum{namespace=~\"$namespace\"}[1m])) / sum by (plugin) (rate(ataccama_one_mmm_import_plugin_time_seconds_count{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Plugin  {{plugin}}"
    }
   ]
  },
  {
   "title": "Object export throughput",
   "type": "timeseries",
   "description": "Number of objects exported per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(ataccama_one_mmm_export_entities_total{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "entities/s"
    },
    {
     "expr": "sum by (plugin) (rate(ataccama_one_mmm_export_plugin_file_total{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "files/s ({{plugin}})"
    }
   ]
  },
  {
   "title": "Object import throughput",
   "type": "timeseries",
   "description": "Number of objects imported per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum (rate(ataccama_one_mmm_import_entities_total{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "entities/s"
    },
    {
     "expr": "sum by (plugin) (rate(ataccama_one_mmm_export_plugin_file_total{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "files/s ({{plugin}})"
    }
   ]
  }
 ]
}