{
 "title": "Ataccama / Gen 2 - Transaction Data",
 "time": { "from": "2021-12-10T12:53:36.170Z", "to": "2021-12-10T13:53:36.170Z" },
 "panels": [
  { "title": "Transaction Data storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transaction data storage SQL operations",
   "type": "timeseries",
   "description": "Transaction data storage SQL operations",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_transaction_data_db_select_seconds_sum[1m])/rate(ataccama_one_mmm_transaction_data_db_select_seconds_count[1m])",
     "legendFormat": "{{ action}}"
    }
   ]
  },
  { "title": "Transaction data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Transaction Data fetch - max",
   "type": "timeseries",
   "description": "Maximum time it took to fetch transaction data results (used by FE for graph visualization)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "ataccama_one_mmm_anomaly_detection_history_fetch_seconds_max {type = \"transaction.data\"}"
    }
   ]
  },
  {
   "title": "Time to create and submit transaction data executor job - max",
   "type": "timeseries",
   "description": "Time taken to create and submit transaction data executor job",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "ataccama_one_mmm_transaction_data_execute_seconds_max"
    }
   ]
  },
  {
   "title": "Time to import results of transaction data analysis - max",
   "type": "timeseries",
   "description": "Time to import results returned from DPM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "ataccama_one_mmm_transaction_data_import_results_seconds_max"
    }
   ]
  },
  {
   "title": "Serialize transaction data job context - max",
   "type": "timeseries",
   "description": "Serialize transaction data job context",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "ataccama_one_mmm_transaction_data_context_serialize_seconds_max"
    }
   ]
  },
  { "title": "Anomalies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Execution of Transaction Data anomaly call - max",
   "type": "timeseries",
   "description": "Time to create requests, send them to AI Core, get results and persist them into a queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "ataccama_one_mmm_anomaly_detection_job_execute_seconds_max {type = \"transaction\"}"
    }
   ]
  },
  {
   "title": "Time to update Transaction Data anomalies - max",
   "type": "timeseries",
   "description": "Time to update Transaction Data anomalies",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "ataccama_one_mmm_anomaly_detection_transaction_data_update_seconds_max"
    }
   ]
  }
 ]
}