{
 "title": "ONE Data (DMM)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "service", "label": "Service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "GQL Query Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(gql_operation_name) (rate(gql_query_seconds_sum{gql_operation=\"QUERY\",namespace=\"$namespace\",service=\"$service\"}[$__rate_interval])) \n/ \navg by(gql_operation_name) (rate(gql_query_seconds_count{gql_operation=\"QUERY\",namespace=\"$namespace\",service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{gql_operation_name}}"
    }
   ]
  },
  {
   "title": "GQL Query Execution Time avg. (top)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, \n    sum by(gql_operation_name) (gql_query_seconds_sum{gql_operation=\"QUERY\",namespace=\"$namespace\",service=\"$service\"})\n    / \n    sum by(gql_operation_name) (gql_query_seconds_count{gql_operation=\"QUERY\",namespace=\"$namespace\",service=\"$service\"})\n)",
     "legendFormat": "{{gql_operation_name}}"
    }
   ]
  },
  {
   "title": "GQL Mutation Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(gql_operation_name) (rate(gql_query_seconds_sum{gql_operation=\"MUTATION\",namespace=\"$namespace\",service=\"$service\"}[$__rate_interval])) / \navg by(gql_operation_name) (rate(gql_query_seconds_count{gql_operation=\"MUTATION\",namespace=\"$namespace\",service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{gql_operation_name}}"
    }
   ]
  },
  {
   "title": "GQL Mutation Execution Time avg. (top)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, \n    sum by(gql_operation_name) (gql_query_seconds_sum{gql_operation=\"MUTATION\",namespace=\"$namespace\",service=\"$service\"}) \n    / sum by(gql_operation_name) (gql_query_seconds_count{gql_operation=\"MUTATION\",namespace=\"$namespace\",service=\"$service\"})\n)",
     "legendFormat": "{{gql_operation_name}}"
    }
   ]
  },
  {
   "title": "GQL Resolver Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(gql_field) (\n    rate(gql_resolver_seconds_sum{namespace=\"$namespace\",service=\"$service\"}[$__rate_interval]) /\n    rate(gql_resolver_seconds_count{namespace=\"$namespace\",service=\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GQL Resolver Execution Time avg. (top)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, \n    sum by(gql_operation_name, gql_field) (\n        gql_resolver_seconds_sum{namespace=\"$namespace\",service=\"$service\"}\n    ) \n    /\n    sum by(gql_operation_name, gql_field) (\n        gql_resolver_seconds_count{namespace=\"$namespace\",service=\"$service\"}\n    )\n)",
     "legendFormat": "{{gql_field}} ({{gql_operation_name}})"
    }
   ]
  },
  {
   "title": "DMM Query Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(name) (\nrate(dmm_query_execution_seconds_sum{namespace=\"$namespace\",service=\"$service\"}[$__rate_interval]) / \nrate(dmm_query_execution_seconds_count{namespace=\"$namespace\",service=\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DMM Query Execution Time avg. (top)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, \n    sum by(name) (dmm_query_execution_seconds_sum{namespace=\"$namespace\",service=\"$service\"}) \n    / sum by(name) (dmm_query_execution_seconds_count{namespace=\"$namespace\",service=\"$service\"})\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DMM Command Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(name) (\nrate(dmm_command_execution_seconds_sum{namespace=\"$namespace\",service=\"$service\"}[$__rate_interval]) / \nrate(dmm_command_execution_seconds_count{namespace=\"$namespace\",service=\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DMM Command Execution Time avg. (top)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, \n    sum by(name) (dmm_command_execution_seconds_sum{namespace=\"$namespace\",service=\"$service\"}) \n    / sum by(name) (dmm_command_execution_seconds_count{namespace=\"$namespace\",service=\"$service\"})\n)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}