{
 "title": "DPx facts",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{clusterName=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "queue",
    "query": "jobPreprocess,jobSubmit,jobPostprocess"
   },
   {
    "name": "dpm_job_name",
    "query": {
     "query": "label_values(ataccama_one_dpm_engines_count_connected, job)"
    }
   },
   {
    "name": "dpe_job_name",
    "query": {
     "query": "label_values(ataccama_one_dpe_plugin_executor_jobs_running, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DPx short facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queued Job Top Priority Age",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ataccama_one_dpm_plugin_executor_queue_jobs_top_priority_job_age_millis{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "Job age"
    }
   ]
  },
  {
   "title": "Queued jobs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ataccama_one_dpm_plugin_executor_jobs_count{status=\"queued\",namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Succeed jobs per minute",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deriv(ataccama_one_dpm_plugin_executor_jobs_count{status=\"success\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed jobs per minute",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(ataccama_one_dpm_plugin_executor_jobs_count{status=\"failure\",namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[1m]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Jobs running on engine(s)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ataccama_one_dpe_plugin_executor_jobs_running{namespace=~\"$namespace\", job=~\"$dpe_job_name\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total connectios",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ataccama_one_dpm_resource_allocation_datasource_connections{namespace=~\"$namespace\", job=~\"$dpm_job_name\"})",
     "legendFormat": "Total connectios"
    }
   ]
  },
  {
   "title": "Status engine check duration",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ataccama_one_dpm_engines_status_check_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connected engines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ataccama_one_dpm_engines_count_connected{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Jobs info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Unfinished jobs",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ataccama_one_dpm_plugin_executor_jobs_count{status!=\"killed\", status!=\"success\", status!=\"failure\", status!=\"unknown\", status!=\"unrecognized\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Finished jobs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ataccama_one_dpm_plugin_executor_jobs_count{status!=\"disconnected\", status!=\"killing\", status!=\"submitting\", status!=\"postprocessing\", status!=\"preprocessing\", status!=\"queued\", status!=\"running\", status!=\"starting\", status!=\"submitted\", status!=\"submitted_to_engine\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of jobs succeed in a minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "deriv(ataccama_one_dpm_plugin_executor_jobs_count{status=\"success\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval]) * 60",
     "legendFormat": "Succeed  jobs (avg per minute)"
    }
   ]
  },
  {
   "title": "Number of jobs failed in a minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "deriv(ataccama_one_dpm_plugin_executor_jobs_count{status=\"failure\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval]) * 60",
     "legendFormat": "Failed  jobs (avg per minute)"
    }
   ]
  },
  {
   "title": "Jobs running per engine",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(ataccama_one_dpe_plugin_executor_jobs_running{namespace=~\"$namespace\", job=~\"$dpe_job_name\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(ataccama_one_dpe_plugin_executor_jobs_running{namespace=~\"$namespace\", job=~\"$dpe_job_name\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Queued jobs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ataccama_one_dpm_plugin_executor_jobs_count{status=\"queued\",namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "Queued jobs"
    }
   ]
  },
  {
   "title": "DPM Queue Jobs Top Priority Job Age",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ataccama_one_dpm_plugin_executor_queue_jobs_top_priority_job_age_millis{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "Job age"
    }
   ]
  },
  {
   "title": "dpm_resource_allocation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "ataccama_one_dpm_resource_allocation_datasource_connections{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "{{access_type}} {{resource_info}}"
    },
    {
     "expr": "sum(ataccama_one_dpm_resource_allocation_datasource_connections{namespace=~\"$namespace\", job=~\"$dpm_job_name\"})",
     "legendFormat": "Total connections"
    }
   ]
  },
  {
   "title": "Job status transition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ataccama_one_dpm_plugin_executor_job_status_change_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "From {{status_old}} to {{status_new}} - max"
    }
   ]
  },
  {
   "title": "DPM GRPC client call",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ataccama_one_grpc_client_call_seconds_max{job=~\"dpm.*\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "{{job}} - {{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "Job preprocessing / postprocessing duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ataccama_one_dpm_plugin_executor_job_preprocess_plugin_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "{{ name }} preprocessing"
    },
    {
     "expr": "ataccama_one_dpm_plugin_executor_job_postprocess_plugin_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "{{ name }} postprocessing"
    }
   ]
  },
  {
   "title": "Processing file download/upload duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ataccama_one_dpm_plugin_executor_job_processing_file_download_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "Processing file download duration max"
    },
    {
     "expr": "rate(ataccama_one_dpm_plugin_executor_job_processing_file_download_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval]) / rate(ataccama_one_dpm_plugin_executor_job_processing_file_download_duration_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
     "legendFormat": "Processing file download duration average"
    },
    {
     "expr": "ataccama_one_dpm_plugin_executor_file_upload_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "Processing file upload duration max"
    },
    {
     "expr": "rate(ataccama_one_dpm_plugin_executor_file_upload_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval]) / rate(ataccama_one_dpm_plugin_executor_file_upload_duration_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
     "legendFormat": "Processing file upload duration average"
    },
    {
     "expr": "ataccama_one_dpm_plugin_executor_file_provider_download_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "Provider file download duration max"
    },
    {
     "expr": "rate(ataccama_one_dpm_plugin_executor_file_provider_download_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval]) / rate(ataccama_one_dpm_plugin_executor_file_provider_download_duration_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
     "legendFormat": "Provider file download duration average"
    }
   ]
  },
  {
   "title": "Size of incoming JobSubmit request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ataccama_one_dpm_plugin_executor_job_submit_message_size_bytes_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
     "legendFormat": "Max - {{type}}"
    },
    {
     "expr": "rate(ataccama_one_dpm_plugin_executor_job_submit_message_size_bytes_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval]) / rate(ataccama_one_dpm_plugin_executor_job_submit_message_size_bytes_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
     "legendFormat": "Average - {{type}}"
    }
   ]
  },
  {
   "title": "Job queue insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "In Memory Submit queue",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "ataccama_one_dpm_job_submit_queue_size{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "queue size ({{instance}}{{pod}})"
      },
      {
       "expr": "ataccama_one_dpm_job_submit_queue_job_constraints_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "job constraints count ({{instance}}{{pod}})"
      },
      {
       "expr": "ataccama_one_dpm_job_submit_queue_job_constraints_size{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "job constraints size ({{instance}}{{pod}})"
      },
      {
       "expr": "ataccama_one_dpm_job_submit_engines_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "engines count ({{instance}}{{pod}})"
      },
      {
       "expr": "ataccama_one_dpm_job_submit_engine_pools{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "engine pools ({{instance}}{{pod}})"
      },
      {
       "expr": "ataccama_one_dpm_job_submit_hashes_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "hashes count ({{instance}}{{pod}})"
      },
      {
       "expr": "ataccama_one_dpm_job_submit_constraints_size{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "constraints size ({{instance}}{{pod}})"
      }
     ]
    },
    {
     "title": "Scan and handle timers",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ataccama_one_dpm_job_queue_handle_seconds_sum{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_handle_seconds_count{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "handle ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_plan_seconds_sum{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_plan_seconds_count{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "plan ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_job_incremental_load_seconds_sum{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_job_incremental_load_seconds_count{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "job incremental load ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_engines_get_engines_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_engines_get_engines_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "get engines ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_snapshot_seconds_sum{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_snapshot_seconds_count{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "snapshot ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_pick_seconds_sum{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_pick_seconds_count{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "pick ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_allocate_resources_seconds_sum{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_allocate_resources_seconds_count{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "allocate resources ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_clean_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_clean_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "clean ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_clean_pick_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_clean_pick_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "clean-pick ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_clean_remove_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_clean_remove_seconds_count{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "clean-remove ({{instance}}{{pod}})"
      }
     ]
    },
    {
     "title": "Queue summaries",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "rate(ataccama_one_dpm_job_queue_engine_slots_empty_summary_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\", queue=\"$queue\"}[$__rate_interval])",
       "legendFormat": "queue run rate ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_jobs_analyzed_summary_sum{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_jobs_analyzed_summary_count{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "jobs analyzed ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_jobs_picked_summary_sum{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_jobs_picked_summary_count{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "jobs picked ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_jobs_notsubmitted_count_total{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_pick_success_count_total{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "not submitted ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_jobs_resources_notallocated_summary_sum{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_jobs_resources_notallocated_summary_count{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "resources not allocated ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_jobs_notsubmitted_error_count_total{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_pick_success_count_total{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "not submitted on error ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_engine_slots_empty_summary_sum{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_engine_slots_empty_summary_count{queue=\"$queue\", namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "empty engine slots ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_queue_clean_jobs_picked_summary_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_queue_clean_jobs_picked_summary_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "removed jobs ({{instance}}{{pod}})"
      }
     ]
    },
    {
     "title": "EngineSets timers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ataccama_one_dpm_job_submit_engine_find_matching_timer_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "find matching engine ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_submit_engine_set_timer_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval]) / rate(ataccama_one_dpm_job_submit_engine_set_timer_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "set engines ({{instance}}{{pod}})"
      }
     ]
    },
    {
     "title": "EngineSets counters",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "ataccama_one_dpm_job_submit_engine_constraints_changed_total{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "constraints changed ({{instance}}{{pod}})"
      },
      {
       "expr": "ataccama_one_dpm_job_submit_engine_find_matching_count_total{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "find matching engine ({{instance}}{{pod}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Job action",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Job Action Summaries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ataccama_one_dpm_job_action_insert_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_action_insert_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "insert {{action}} ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_action_read_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_action_read_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "read {{action}} ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_action_in_queue_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_action_in_queue_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "in queue {{action}} ({{instance}}{{pod}})"
      }
     ]
    },
    {
     "title": "Job action timers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ataccama_one_dpm_job_action_insert_timer_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_action_insert_timer_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "insert {{action}} ({{instance}}{{pod}})"
      },
      {
       "expr": "rate(ataccama_one_dpm_job_action_read_timer_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_job_action_read_timer_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "read {{action}} ({{instance}}{{pod}})"
      }
     ]
    }
   ]
  },
  {
   "title": "DPM info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Executor thread pool",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ataccama_one_dpm_plugin_executor_thread_pool_pool{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Current number of threads in the pool: {{thread_pool_name}}"
      },
      {
       "expr": "ataccama_one_dpm_plugin_executor_thread_pool_active{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Approximate number of threads that are actively executing tasks: {{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "Executor queue size / tasks completed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ataccama_one_dpm_plugin_executor_thread_pool_queued{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Approximate tasks in queue: {{thread_pool_name}}"
      },
      {
       "expr": "rate(ataccama_one_dpm_plugin_executor_thread_pool_completed_total{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "Approximate completed tasks:  {{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "Executor thread pool [s]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ataccama_one_dpm_plugin_executor_thread_pool_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Seconds max: {{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "GRPC server pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ataccama_one_grpc_server_pool_active{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "DPM server pool active"
      },
      {
       "expr": "ataccama_one_grpc_server_pool_queue_size{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "DPM server pool queue"
      },
      {
       "expr": "ataccama_one_grpc_server_pool_active{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "{{ pod}} server pool active"
      },
      {
       "expr": "ataccama_one_grpc_server_pool_queue_size{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "{{ pod}} server pool queue"
      }
     ]
    },
    {
     "title": "Duration of retrieving events from database",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ataccama_one_dpm_events_engine_pick_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "rate(ataccama_one_dpm_events_engine_pick_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_events_engine_pick_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Duration of job operations",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 10, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ataccama_one_dpm_plugin_executor_job_submit_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Duration of job submit operation max"
      },
      {
       "expr": "rate(ataccama_one_dpm_plugin_executor_job_submit_duration_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval]) / rate(ataccama_one_dpm_plugin_executor_job_submit_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "Duration of job submit operation average"
      },
      {
       "expr": "ataccama_one_dpm_plugin_executor_job_update_status_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Duration of update job process  max"
      },
      {
       "expr": "rate(ataccama_one_dpm_plugin_executor_job_create_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval]) / rate(ataccama_one_dpm_plugin_executor_job_create_duration_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "Duration of update job process  average"
      },
      {
       "expr": "ataccama_one_dpm_plugin_executor_job_kill_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Duration of job kill operation max"
      },
      {
       "expr": "rate(ataccama_one_dpm_plugin_executor_job_kill_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval]) / rate(ataccama_one_dpm_plugin_executor_job_kill_duration_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "Duration of job kill operation average"
      }
     ]
    },
    {
     "title": "Duration of queue operations",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ataccama_one_dpm_plugin_executor_job_to_submit_add_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Duration of add operation on submit job queue max"
      },
      {
       "expr": "rate(ataccama_one_dpm_plugin_executor_job_to_submit_add_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[1m]) / rate(ataccama_one_dpm_plugin_executor_job_to_submit_add_duration_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[1m])",
       "legendFormat": "Duration of add operation on submit job queue average"
      },
      {
       "expr": "ataccama_one_dpm_plugin_executor_job_to_kill_add_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Duration of add operation on kill job queue max"
      },
      {
       "expr": "rate(ataccama_one_dpm_plugin_executor_job_to_kill_add_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[1m]) / rate(ataccama_one_dpm_plugin_executor_job_to_kill_add_duration_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[1m])",
       "legendFormat": "Duration of add operation on kill job queue average"
      },
      {
       "expr": "ataccama_one_dpm_plugin_executor_job_killAsAdmin_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Duration of kill job as admin operation max"
      },
      {
       "expr": "rate(ataccama_one_dpm_plugin_executor_job_killAsAdmin_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[1m]) / rate(ataccama_one_dpm_plugin_executor_job_killAsAdmin_duration_seconds_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[1m])",
       "legendFormat": "Duration of kill job as admin operation average"
      }
     ]
    }
   ]
  },
  {
   "title": "Engines info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Jobs running per engine",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(ataccama_one_dpe_plugin_executor_jobs_running{namespace=~\"$namespace\", job=~\"$dpe_job_name\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(ataccama_one_dpe_plugin_executor_jobs_running{namespace=~\"$namespace\", job=~\"$dpe_job_name\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Status check duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 9, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ataccama_one_dpm_engines_status_check_duration_seconds{quantile=\"0.95\",namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Average"
      },
      {
       "expr": "ataccama_one_dpm_engines_status_check_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 15, "w": 4, "x": 20, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "ataccama_one_dpm_engines_status_check_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Constraints collector",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 9, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ataccama_one_dpe_constraints_collector_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpe_job_name\"}",
       "legendFormat": "Engine {{pod}} max"
      },
      {
       "expr": "ataccama_one_dpe_constraints_cached_data_source_session_digests_duration_seconds_max{namespace=~\"$namespace\", job=~\"$dpe_job_name\"}",
       "legendFormat": "Engine {{pod}}, cached source data"
      }
     ]
    },
    {
     "title": "Associated engines",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ataccama_one_dpm_engines_count_connected{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Connected engines"
      },
      {
       "expr": "ataccama_one_dpm_engines_count_disconnected{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Disconnected engines"
      },
      {
       "expr": "ataccama_one_dpm_engines_count_active{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Active engines "
      },
      {
       "expr": "rate(ataccama_one_dpm_engines_count_inactive{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[1d])",
       "legendFormat": "Inactive engines "
      }
     ]
    }
   ]
  },
  {
   "title": "Autoscaling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Autoscaling",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "ataccama_one_dpm_autoscaler_k8sEnginesCount{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "k8sEnginesCount"
      },
      {
       "expr": "ataccama_one_dpm_autoscaler_jobsInQueueCount{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "jobsInQueueCount"
      },
      {
       "expr": "ataccama_one_dpm_autoscaler_movingAverageJobsInQueueCount{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "movingAverageJobsInQueueCount"
      },
      {
       "expr": "ataccama_one_dpm_autoscaler_scaleUpSlotsCount{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "scaleUpSlotsCount"
      },
      {
       "expr": "ataccama_one_dpm_autoscaler_newEnginesCount{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "newEnginesCount"
      },
      {
       "expr": "ataccama_one_dpm_autoscaler_throttledJobsInQueueCount{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "throttledJobsInQueueCount"
      },
      {
       "expr": "ataccama_one_dpm_autoscaler_registeredEnginesNotScaledDownCount{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "registeredEnginesNotScaledDownCount"
      },
      {
       "expr": "ataccama_one_dpm_autoscaler_registeredEnginesCount{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "registeredEnginesCount"
      },
      {
       "expr": "ataccama_one_dpm_job_submit_queue_size{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "Jobs Queue Size"
      },
      {
       "expr": "ataccama_one_dpm_autoscaler_enginesIdsToReviveCount{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "enginesIdsToReviveCount"
      },
      {
       "expr": "ataccama_one_dpm_autoscaler_enginesIdsToStopCount{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}",
       "legendFormat": "enginesIdsToStopCount"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB locks per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "irate(ataccama_one_dpm_db_lock_total{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "{{counterName}} - {{instance}}{{pod}} - {{lock}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Published Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "rate(ataccama_one_dpm_events_published_summary_sum{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])/rate(ataccama_one_dpm_events_published_summary_count{namespace=~\"$namespace\", job=~\"$dpm_job_name\"}[$__rate_interval])",
       "legendFormat": "{{instance}}{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}