{
 "title": "Health checks",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "depender",
    "label": "Component",
    "query": {
     "query": "label_values(ataccama_one_dependency_health, depender)"
    }
   },
   {
    "name": "dpe",
    "label": "DPEs",
    "query": {
     "query": "label_values(ataccama_one_dependency_health, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dead dependencies",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ataccama_one_dependency_health{depender!=\"mmm-beXX\"} > 0",
     "legendFormat": "{{depender}} -> {{dependency}}"
    }
   ]
  },
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 17, "w": 11, "x": 13, "y": 0 },
   "options": {
    "content": "## How to use this dashboard: ##\n\n1. First panel `Dead dependencies` shows only health checks that are not OK. All **reported** problems will be visible there. Please note that if component from whatever reason does not report it's metrics you will not see it there.\n2. Other panels are dedicated to particular components. Each row in panel shows state of certain health check. You can filter displayed components in dashboard header.\n\n🐞 If you are not seeing any data/panels make sure that exposing of health checks as metrics is configured for all components. \nI.e `ataccama.one.mmm.health-checks.expose-as-metrics=true` for MMM-BE. 🐞\n\n\n## Questions that this dashboard show be able to answer: ##\n\n- Is certain component up and running?\n- Can component connect to all of it's dependencies? I.e. is MMM-BE connected to DPM?\n- Was there some infrastructure issue?\n- Was some component unavailable for some time?\n\n## Known limitations ⚠️ ##\n\n- Exposing of metrics is currently supported only by MMM-BE, DPM, DPE\n- Health checks are currently executed eagerly every time Prometheus is scraping metrics endpoint\n- Health checks are currently executed serially one-by-one so if any health checks waits unreasonably long for some timeout it will affect all other metrics gathering\n- customer Data Sources are not included\n- not all health checks are already implemented"
   }
  },
  {
   "title": "$depender - dependencies",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 8 },
   "repeat": "depender",
   "targets": [
    {
     "expr": "ataccama_one_dependency_health{depender=\"$depender\"}",
     "legendFormat": "{{dependency}}"
    }
   ]
  },
  {
   "title": "$dpe - dependencies",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 26 },
   "repeat": "dpe",
   "targets": [
    {
     "expr": "ataccama_one_dependency_health{pod=\"$dpe\"}",
     "legendFormat": "{{dependency}}"
    }
   ]
  }
 ]
}