{
 "title": "MDM",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{clusterName=~\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests per second", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Admin console",
   "type": "stat",
   "description": "Number of http requests to admin console per second",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "rate(ataccama_one_http_server_request_seconds_count{job=~\"mdm.*\", namespace=~\"$namespace\"}[$__interval])"
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "stat",
   "description": "Number of gRPC requests per second",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "rate(ataccama_one_grpc_server_request_seconds_count{job=~\"mdm.*\", namespace=~\"$namespace\"}[$__interval])"
    }
   ]
  },
  {
   "title": "SOAP",
   "type": "stat",
   "description": "Number of SOAP requests per second",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "rate(ataccama_one_http_server_request_seconds_count{job=~\"mdm.*\", namespace=~\"$namespace\"}[$__interval])"
    }
   ]
  },
  {
   "title": "MDA",
   "type": "stat",
   "description": "Number of MDA service layer requests per second",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "rate(ataccama_one_mda_service_request_seconds_count{namespace=~\"$namespace\"}[$__interval])"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "SOAP",
   "type": "stat",
   "description": "Number of SOAP requests per second",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "ataccama_one_http_server_request_seconds_count{job=~\"mdm.*\", namespace=~\"$namespace\"}"
    }
   ]
  },
  { "title": "Columns", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "HTTP avarage response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(ataccama_one_http_server_request_seconds_sum{job=~\"mdm.*\", namespace=~\"$namespace\"}[1m])) / sum(rate(ataccama_one_http_server_request_seconds_count{job=~\"mdm.*\", namespace=~\"$namespace\"}[1m]))*1000",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "MDA avarage response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(ataccama_one_mda_service_request_seconds_sum{job=~\"mdm.*\", namespace=~\"$namespace\"}[1m])) / sum(rate(ataccama_one_mda_service_request_seconds_count{job=~\"mdm.*\", namespace=~\"$namespace\"}[1m]))*1000",
     "legendFormat": "HTTP"
    }
   ]
  }
 ]
}