{
 "title": "MDE Lineage",
 "tags": [
  "component:mde",
  "spaceport:DG"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, namespace)"
    }
   },
   { "name": "component", "query": "${VAR_COMPONENT}" },
   {
    "name": "graphqlPath",
    "query": {
     "query": "label_values(graphql_datafetcher_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\"}, path)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Signs of trouble", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ERROR logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\", level=\"error\"}[$__rate_interval])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GraphQL errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(graphql_datafetcher_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\", outcome=\"ERROR\"}[$__rate_interval])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\", level=\"warn\"}[$__rate_interval])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "fail to scheduled import jobs",
   "type": "stat",
   "description": "no data is OK",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ataccama_one_mde_importjob_manta_scheduled_count_total{namespace=\"$namespace\", status=\"FAIL\"}[$__range])+1) by (status)",
     "legendFormat": "scheduled jobs"
    }
   ]
  },
  {
   "title": "failed MDE import job executions",
   "type": "timeseries",
   "description": "No data means noting failed",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ataccama_one_mde_importjob_manta_seconds_count{namespace=\"$namespace\", status=\"FAIL\"}) by (pod, status, operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Logs of component: $component in $namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\"}[$__rate_interval])) by(level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "lineage api - jvm heap usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app_kubernetes_io_component=\"$component\", namespace=\"$namespace\", area=\"heap\", ataccama_com_mde_workload=\"web\"}) / sum(jvm_memory_max_bytes{app_kubernetes_io_component=\"$component\", namespace=\"$namespace\", area=\"heap\", ataccama_com_mde_workload=\"web\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scheduled jobs import jobs",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ataccama_one_mde_importjob_manta_scheduled_count_total{namespace=\"$namespace\"}[$__range])+1) by (status, operation)",
     "legendFormat": "{{status}} - {{operation}}"
    }
   ]
  },
  {
   "title": "graphql request breakdown",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(graphql_datafetcher_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\"}[$__range])) by (path, outcome)",
     "legendFormat": "{{path}}-{{outcome}}"
    }
   ]
  },
  {
   "title": "GraphQL requests per interval by SUCC/ERROR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(graphql_request_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\"}[$__rate_interval])) by (outcome)",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "GraphQL duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(graphql_request_seconds_sum{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\"}[$__rate_interval])) by (outcome) / sum(increase(graphql_request_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\"}[$__rate_interval])) by (outcome)",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "max db connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_max{app_kubernetes_io_component=\"$component\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "currently used DB connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\"}) by (pod) / sum(hikaricp_connections_max{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\"}) by  (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC calls to other services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 35 },
   "targets": [
    {
     "expr": "increase(ataccama_one_grpc_client_call_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\"}[$__rate_interval])",
     "legendFormat": "{{serviceName}}.{{method}}"
    }
   ]
  },
  {
   "title": "active db connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{app_kubernetes_io_component=\"$component\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres DB size: $component",
   "type": "stat",
   "description": "source: pg_exporter",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{namespace=\"$namespace\", datname=\"$component\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hikari acquire connection time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(hikaricp_connections_acquire_seconds_sum{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\"}[$__rate_interval]) / irate(hikaricp_connections_acquire_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\"}[$__rate_interval])",
     "legendFormat": "{{pod}} ({{pool}})"
    }
   ]
  },
  {
   "title": "MDE import job executions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ataccama_one_mde_importjob_manta_seconds_count{namespace=\"$namespace\"}) by (status, operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average MDE import job duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ataccama_one_mde_importjob_manta_seconds_sum{namespace=\"$namespace\"}) by (status, operation)/ sum(ataccama_one_mde_importjob_manta_seconds_count{namespace=\"$namespace\"}) by (status, operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Lineage Catalog Matching (MMM)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Connection processing: average duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "rate(ataccama_one_lineage_integration_catalog_matching_processing_connection_seconds_sum{namespace=\"$namespace\"}[$__rate_interval]) /  rate(ataccama_one_lineage_integration_catalog_matching_processing_connection_seconds_count{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Processing connection duration (including upload): {{technology}}"
    },
    {
     "expr": "rate(ataccama_one_lineage_integration_catalog_matching_processing_result_upload_seconds_sum{namespace=\"$namespace\"}[$__rate_interval]) / rate(ataccama_one_lineage_integration_catalog_matching_processing_result_upload_seconds_count{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Upload to MinIO average duration"
    }
   ]
  },
  {
   "title": "Per-minute throughput of processed entities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(rate(ataccama_one_lineage_integration_catalog_matching_processing_entities_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Overall requests statuses",
   "type": "stat",
   "description": "Gauge reaching out to database to see number of requests, grouped by status.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ataccama_one_lineage_integration_catalog_matching_processing_request_success{namespace=\"$namespace\"}",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "ataccama_one_lineage_integration_catalog_matching_processing_request_failed{namespace=\"$namespace\"}",
     "legendFormat": "FAILED"
    },
    {
     "expr": "ataccama_one_lineage_integration_catalog_matching_processing_request_running{namespace=\"$namespace\"}",
     "legendFormat": "RUNNING"
    }
   ]
  },
  {
   "title": "Overall requests statuses",
   "type": "timeseries",
   "description": "Gauge reaching out to database to see number of requests, grouped by status.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 66 },
   "targets": [
    {
     "expr": "ataccama_one_lineage_integration_catalog_matching_processing_request_success{namespace=\"$namespace\"}",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "ataccama_one_lineage_integration_catalog_matching_processing_request_failed{namespace=\"$namespace\"}",
     "legendFormat": "FAILED"
    },
    {
     "expr": "ataccama_one_lineage_integration_catalog_matching_processing_request_running{namespace=\"$namespace\"}",
     "legendFormat": "RUNNING"
    }
   ]
  },
  {
   "title": "Request processing: duration (progress check every 10 sec)",
   "type": "timeseries",
   "description": "Duration of the whole processing that is currently worked on. 1 request can contain multiple connections. Check is executed every 10 seconds.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "ataccama_one_lineage_integration_catalog_matching_processing_current_duration{namespace=\"$namespace\"}",
     "legendFormat": "Processing duration checked periodically"
    }
   ]
  },
  {
   "title": "LineageExecutor pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 67 },
   "targets": [
    {
     "expr": "ataccama_one_mmm_threadpool_queue_size{namespace=~\"$namespace\", name=\"lineageExecutor\"}",
     "legendFormat": "Waiting requests"
    },
    {
     "expr": "ataccama_one_mmm_threadpool_active{namespace=~\"$namespace\", name=\"lineageExecutor\"}",
     "legendFormat": "Active threads"
    }
   ]
  },
  { "title": "resources $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }, "repeat": "pod" },
  {
   "title": "pod Memory Usage (WSS) $pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "JVM Heap $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=\"$pod\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{pod=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "pod CPU Usage $pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}[$__rate_interval]) ",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "pod CPU Throttling $pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}[$__rate_interval])) by (container) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "options": {
    "content": "All graphql paths are wrapped under:  \n* `Query.*` and `Mutation.*` and they can't be easily excluded from pie chart"
   }
  },
  {
   "title": "GraphQL path $graphqlPath",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
   "repeat": "graphqlPath",
   "collapsed": true,
   "panels": [
    {
     "title": "GraphQL requests per interval",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "sum(increase(graphql_datafetcher_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\", path=~\"$graphqlPath\"}[$__rate_interval])) by (outcome)",
       "legendFormat": "{{outcome}} $graphqlPath"
      }
     ]
    },
    {
     "title": "GraphQL average duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(graphql_datafetcher_seconds_sum{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\", path=~\"$graphqlPath\"}[$__rate_interval])) by (outcome) / sum(increase(graphql_datafetcher_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$component\", path=~\"$graphqlPath\"}[$__rate_interval])) by (outcome)",
       "legendFormat": "{{outcome}} $graphqlPath"
      }
     ]
    }
   ]
  }
 ]
}