{
 "title": "MDM usage",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(mdm_db_statistics_entities_entities, clusterName)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(mdm_db_statistics_entities_entities{clusterName=~\"$cluster\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Entity Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mdm_db_statistics_entities_entities{pod=~\"$pod\", clusterName=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Total record count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mdm_db_statistics_records_total_records{pod=~\"$pod\", clusterName=~\"$cluster\"}"
    }
   ]
  },
  { "title": "Users usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Distinct Users per day",
   "type": "stat",
   "description": "From MDA audit",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mdm_db_statistics_active_users_last_day_users_day{pod=~\"$pod\", clusterName=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Distinct Users per month",
   "type": "stat",
   "description": "From MDA audit",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mdm_db_statistics_active_users_last_month_users_month{pod=~\"$pod\", clusterName=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Drafts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mdm_db_statistics_drafts_drafts{pod=~\"$pod\", clusterName=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "History Drafts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mdm_db_statistics_drafts_history_drafts_h{pod=~\"$pod\", clusterName=~\"$cluster\"}"
    }
   ]
  },
  { "title": "Write operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Write ops per day",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(mdm_db_statistics_writes_last_day_writes_day{pod=~\"$pod\", clusterName=~\"$cluster\"}[$__range])"
    }
   ]
  },
  {
   "title": "Write ops per month",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(mdm_db_statistics_writes_last_month_writes_month{pod=~\"$pod\", clusterName=~\"$cluster\"}[$__range])"
    }
   ]
  },
  {
   "title": "Time of write ops - sum per last day",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mdm_db_statistics_writes_time_last_day_writes_time_day{pod=~\"$pod\", clusterName=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Time of write ops - sum per last month",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mdm_db_statistics_writes_time_last_month_writes_time_month{pod=~\"$pod\", clusterName=~\"$cluster\"}"
    }
   ]
  }
 ]
}