{
 "title": "MMM DB metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(mmm_db_statistics_catalog_items, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Sources",
   "type": "stat",
   "description": "Number of data sources",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_data_sources{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Catalog Items",
   "type": "stat",
   "description": "Number of catalog items",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_catalog_items{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Terms",
   "type": "stat",
   "description": "Number of terms",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_number_of_terms{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Attributes",
   "type": "stat",
   "description": "Number of attributes",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_attributes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max attributes per 1 catalog item",
   "type": "stat",
   "description": "Max attributes per single catalog item",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_max_attributes_per_catalog_item{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "description": "Number of jobs",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_jobs_number{instance=~\"$instance\"}",
     "legendFormat": "Number of jobs"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "% of profiled tables",
   "type": "gauge",
   "description": "Percentage of profiled tables",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_profiled_tables_percentage{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Profiled tables",
   "type": "stat",
   "description": "Number of profiled tables",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_number_of_profiled_tables{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Relationships",
   "type": "stat",
   "description": "Relationships between tables",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_relations_between_tables{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Terms on tables",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "mmm_db_statistics_number_of_terms_assigned_to_tables{instance=~\"$instance\"}",
     "legendFormat": "Total terms on tables"
    },
    {
     "expr": "mmm_db_statistics_average_terms_assigned_to_tables{instance=~\"$instance\"}",
     "legendFormat": "Average"
    },
    {
     "expr": "mmm_db_statistics_max_terms_assigned_to_table{instance=~\"$instance\"}",
     "legendFormat": "Max on 1 table"
    }
   ]
  },
  {
   "title": "Terms on tables",
   "type": "stat",
   "description": "Terms assigned to tables",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_number_of_terms_assigned_to_tables{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average terms on tables",
   "type": "stat",
   "description": "Average terms assigned to tables",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_average_terms_assigned_to_tables{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max terms on 1 table",
   "type": "stat",
   "description": "Max terms on single table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_max_terms_assigned_to_table{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Columns", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Terms on columns",
   "type": "stat",
   "description": "Number of terms assigned to columns",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_number_of_terms_assigned_to_columns{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average Columns",
   "type": "stat",
   "description": "Average columns per table",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_average_columns_per_table{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Terms on columns",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "mmm_db_statistics_number_of_terms_assigned_to_columns{instance=~\"$instance\"}",
     "legendFormat": "Total terms on columns"
    },
    {
     "expr": "mmm_db_statistics_average_assigned_terms_on_columns{instance=~\"$instance\"}",
     "legendFormat": "Average"
    },
    {
     "expr": "mmm_db_statistics_max_assigned_terms_on_column{instance=~\"$instance\"}",
     "legendFormat": "Max on 1 column"
    }
   ]
  },
  {
   "title": "Average terms on columns",
   "type": "stat",
   "description": "Number of average terms assigned to columns",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_average_assigned_terms_on_columns{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max terms on 1 column",
   "type": "stat",
   "description": "Max terms on 1 column",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_max_assigned_terms_on_column{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Deletion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Deleted rules",
   "type": "stat",
   "description": "Number of deleted rules",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_deleted_rules_number{instance=~\"$instance\"}",
     "legendFormat": "Number of deleted rules"
    }
   ]
  },
  {
   "title": "Deleted monitoring projects",
   "type": "stat",
   "description": "Number of deleted monitoring projects",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_deleted_monitoring_projects_number{instance=~\"$instance\"}",
     "legendFormat": "Number of deleted monitoring projects"
    }
   ]
  },
  {
   "title": "Deleted datasources",
   "type": "stat",
   "description": "Number of deleted datasources",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_deleted_sources_number{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Deleted catalog items",
   "type": "stat",
   "description": "Number of deleted catalog items",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_deleted_catalog_items_number{instance=~\"$instance\"}",
     "legendFormat": "Number of deleted catalog items"
    }
   ]
  },
  {
   "title": "Deleted profilings",
   "type": "stat",
   "description": "Number of deleted profilings",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmm_db_statistics_deleted_profilings_number{instance=~\"$instance\"}",
     "legendFormat": "Number of deleted profilings"
    }
   ]
  }
 ]
}