{
 "title": "Thanos / Modules Sizes on Cluster",
 "tags": [ "thanos-custom" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "environment", "label": "Environment", "query": "dev, test, prod" },
   {
    "name": "clusterName",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_container_info{environment=~\"$environment\"}, clusterName)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "product, default, twistlock, kube-system, gatekeeper-system"
   }
  ]
 },
 "panels": [
  {
   "title": "Sum of CPU (vCores) Requests",
   "type": "stat",
   "description": "Latest sum value of all Requested CPU capacity by all pods combined.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", environment=~\"$environment\", clusterName=~\"$clusterName\"} < 1000)"
    }
   ]
  },
  {
   "title": "Available Cluster CPU (vCores)",
   "type": "stat",
   "description": "Sum of CPU capacity on all nodes in the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(instance:node_num_cpu:sum{clusterName=\"$clusterName\"})"
    }
   ]
  },
  {
   "title": "Non-requested CPU",
   "type": "stat",
   "description": "Percentage of total cluster's CPU capacity that is not requested by any pod.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum(kube_pod_container_resource_requests{environment=~\"$environment\", clusterName=~\"$clusterName\"} < 1000)\r\n/sum(instance:node_num_cpu:sum{clusterName=\"$clusterName\"}))"
    }
   ]
  },
  {
   "title": "Sum of Memory Requests",
   "type": "stat",
   "description": "Latest sum value of all Requested Memory capacity by all pods combined.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", environment=~\"$environment\", clusterName=~\"$clusterName\"} > 1000)"
    }
   ]
  },
  {
   "title": "Available Cluster Memory",
   "type": "stat",
   "description": "Sum of available (not reserved) Memory capacity on all nodes in the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{clusterName=\"$clusterName\"})"
    }
   ]
  },
  {
   "title": "Non-requested Memory",
   "type": "stat",
   "description": "Percentage of total cluster's Memory capacity that is not requested by any pod.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(kube_pod_container_resource_requests{environment=~\"$environment\", clusterName=~\"$clusterName\"} > 1000)\r\n/sum(node_memory_MemTotal_bytes{clusterName=\"$clusterName\"}))"
    }
   ]
  },
  {
   "title": "Total CPU (vCores) Requests per Module type",
   "type": "bargauge",
   "description": "CPU Requests sum for all pods with same \"container\" label - assumed to be same module or representing one type group.",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", environment=~\"$environment\", clusterName=~\"$clusterName\"} < 1000) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total Memory Requests per Module type",
   "type": "bargauge",
   "description": "Memory Requests sum for all pods with same \"container\" label - assumed to be same module or representing one type group.",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", environment=~\"$environment\", clusterName=~\"$clusterName\"} > 1000) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total CPU (vCores) Limits per Module type",
   "type": "bargauge",
   "description": "CPU Limits sum for all pods with same \"container\" label - assumed to be same module or representing one type group.",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", environment=~\"$environment\", clusterName=~\"$clusterName\"} < 1000) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total Memory Limits per Module type",
   "type": "bargauge",
   "description": "Memory Limits sum for all pods with same \"container\" label - assumed to be same module or representing one type group.",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", environment=~\"$environment\", clusterName=~\"$clusterName\"} > 1000) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}