{
 "title": "Thanos / Pod Usage - Overview",
 "tags": [ "thanos-custom" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "environment", "label": "Environment", "query": "dev, test, prod" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "product, default, twistlock, kube-system, gatekeeper-system"
   },
   {
    "name": "podType",
    "label": "Pod Type",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", environment=~\"$environment\"}, container)"
    }
   },
   {
    "name": "clusterName",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", environment=~\"$environment\", container=\"$podType\"}, clusterName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod Max (peaks) per Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Max CPU Core Usage (vCPU time) per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"}) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"} < 1000) by (container)",
     "legendFormat": "CPU Requests Max"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"} < 1000) by (container)",
     "legendFormat": "CPU Limits Max"
    }
   ]
  },
  {
   "title": "Pod Max Memory Usage (MWS) per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"}) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"} > 1000) by (container)",
     "legendFormat": "Memory Requests Max"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"} > 1000) by (container)",
     "legendFormat": "Memory Limits Max"
    }
   ]
  },
  {
   "title": "Pod Max (peaks) per Cluster - Limits breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Max CPU Core Usage (vCPU time) per Cluster",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 23, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"}) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"} < 1000) by (container)",
       "legendFormat": "CPU Requests Max"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"} < 1000) by (container, clusterName)",
       "legendFormat": "CPU Limits Max - {{clusterName}}"
      }
     ]
    },
    {
     "title": "Pod Max Memory Usage (MWS) per Cluster",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 23, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"}) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"} > 1000) by (container)",
       "legendFormat": "Memory Requests Max"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"} > 1000) by (container, clusterName)",
       "legendFormat": "Memory Limits Max - {{clusterName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Avg per Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Avg CPU Core Usage (vCPU time) per Cluster",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 23, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"}) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"} < 1000) by (container)",
       "legendFormat": "CPU Requests Max"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"} < 1000) by (container)",
       "legendFormat": "CPU Limits Max"
      }
     ]
    },
    {
     "title": "Pod Avg Memory Usage (MWS) per Cluster",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 23, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"}) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"} > 1000) by (container)",
       "legendFormat": "Memory Requests Max"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\", clusterName=~\"$clusterName\"} > 1000) by (container)",
       "legendFormat": "Memory Limits Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Max per Cluster - Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Max CPU Core Usage (vCPU time) per Cluster",
     "type": "histogram",
     "gridPos": { "h": 13, "w": 23, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\"}) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      }
     ]
    },
    {
     "title": "Pod Max Memory Usage (RSS) per Cluster",
     "type": "histogram",
     "gridPos": { "h": 13, "w": 23, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\"}) by (clusterName)",
       "legendFormat": "{{clusterName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Sum per Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Sum CPU Core Usage (vCPU time) per Pod",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 23, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\"})",
       "legendFormat": "{{clusterName}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Pod Sum Memory Usage (MWS) per Pod",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 23, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$podType\", environment=~\"$environment\"}) by (clusterName, pod)",
       "legendFormat": "{{clusterName}}-{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}