{
 "title": "Reconciliation",
 "description": "Reconciliation monitoring metrics",
 "time": { "from": "2023-03-24T05:07:16.629Z", "to": "2023-03-24T17:07:16.629Z" },
 "panels": [
  {
   "title": "Mapping metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ataccama_one_mmm_reconciliation_mapping_seconds_max) by (method, class)",
     "legendFormat": "{{class}}-{{method}}"
    }
   ]
  },
  {
   "title": "Service metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ataccama_one_mmm_reconciliation_service_seconds_max) by (method, class)",
     "legendFormat": "{{class}}-{{method}}"
    }
   ]
  },
  {
   "title": "Fetcher metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ataccama_one_mmm_reconciliation_fetcher_seconds_max) by (method, class)",
     "legendFormat": "{{class}}-{{method}}"
    }
   ]
  },
  {
   "title": "Results metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ataccama_one_mmm_reconciliation_updater_seconds_max) by (method, class)",
     "legendFormat": "{{class}}-{{method}}"
    }
   ]
  },
  {
   "title": "Notification metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ataccama_one_mmm_reconciliation_notifications_seconds_max) by (method, class)",
     "legendFormat": "{{class}}-{{method}}"
    }
   ]
  }
 ]
}