---

- name: set monitoring rules
  include_role:
    name: monitoring_rules
  tags: monitoring
  vars:
    monitoring_ruleset:
      job_name: mmm-backend
      metrics_path: /actuator/prometheus
      basic_auth:
        username: "{{ keycloak_monitoring_user.username }}"
        password: "{{ keycloak_monitoring_user.password }}"
      scheme: http
      port: "{{ mmm_management_port }}"
      static_configs:
        - labels:
            namespace: onprem
            clusterName: onprem
            app_kubernetes_io_component: mmm-be

- name: install mmm db exporter
  include_role:
    name: ataccama_mmm_exporter
    apply:
      delegate_to: "{{ groups['monitoring_server'][0] }}"
  tags: monitoring
  vars:
    prometheus_exporter_service_name: ataccama_mmm_exporter
    inventory_hostname: "{{ groups['monitoring_server'][0] }}"
    mmm_exporter_queries: |-
      {{ lookup('file', '{{ playbook_dir }}/files/grafana-dashboards/ataccama-dashboards/sqlexporter/mmm/mmm-queries.yaml') }}
