---

- name: Add fluentbit apt-key on Debian
  apt_key:
    url: "{{ fluentbit_gpg_key }}"
    state: present

- name: Install Debian | Add td-agent-bit repository
  apt_repository:
    repo: '{{ fluentbit_apt_repo }}'
    state: present
    filename: td-agent-bit
    update_cache: true
