---

- name: set fluentbit monitoring rules
  include_role:
    name: monitoring_rules
  tags: monitoring
  vars:
    monitoring_ruleset_name: fluentbit
    monitoring_ruleset:
      metrics_path: /api/v1/metrics/prometheus
      port: "{{ fluentbit_service_metrics_listen_port }}"
