{
 "title": "Nginx",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nginx_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Nginx stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nginx requests per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(delta(nginx_http_requests_total{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "total requests - {{instance}}"
    },
    {
     "expr": "avg(delta(nginx_connections_accepted{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "accepted connections - {{instance}}"
    },
    {
     "expr": "avg(delta(nginx_connections_handled{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "handled connections - {{instance}}"
    }
   ]
  },
  {
   "title": "Nginx connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance\"}",
     "legendFormat": "active connections - {{instance}}"
    },
    {
     "expr": "nginx_connections_reading{instance=~\"$instance\"}",
     "legendFormat": "reading connections - {{instance}}"
    },
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance\"}",
     "legendFormat": "waiting connections - {{instance}}"
    },
    {
     "expr": "nginx_connections_writing{instance=~\"$instance\"}",
     "legendFormat": "writing connections - {{instance}}"
    }
   ]
  },
  {
   "title": "Nginx ups and downs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$instance\"}",
     "legendFormat": "status - {{instance}}"
    }
   ]
  }
 ]
}