{
 "title": "Prometheus Alerts",
 "description": "Dashboard showing Prometheus Alerts (both pending and firing) for alerts adjustment and debugging",
 "tags": [
  "prometheus",
  "alerts"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance:",
    "query": {
     "query": "label_values(ALERTS_FOR_STATE,instance)"
    }
   },
   {
    "name": "alertname",
    "label": "Alert:",
    "query": {
     "query": "label_values(ALERTS_FOR_STATE,alertname)"
    }
   },
   {
    "name": "alertstate",
    "label": "State:",
    "query": {
     "query": "label_values(ALERTS, alertstate)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Alerts History",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Firing (-)   /  Pending (+)  " }
   ],
   "targets": [
    {
     "expr": "ALERTS{instance=~\"$instance\", alertname=~\"$alertname\", alertstate=~\"$alertstate\"}",
     "legendFormat": "{{alertname}} {{instance}} {{alertstate}} {{datacenter}}"
    },
    { "expr": "1", "legendFormat": "help_series_x_axes_in_center" }
   ]
  },
  {
   "title": "Alerts Start List",
   "type": "table",
   "description": "Alerts list for all alerts in a selected time range. For filling this table `Alerts annotations` have to be switched on.",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ALERTS_FOR_STATE{instance=~\"$instance\", alertname=~\"$alertname\"} * 1000"
    }
   ]
  },
  {
   "title": "Total Alert Counts",
   "type": "table",
   "description": "Shows how many times was particular alert started in a defined time range. Alert can be started either directly as `firing` or as a `pending`. Pending alerts wait for a defined time before it flips to a `firing` alert. This is specified with the `FOR` clause in a Prometheus `rules` file.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes( ALERTS_FOR_STATE{instance=~\"$instance\",alertname=~\"$alertname\"}[$__range] ) + 1"
    }
   ]
  }
 ]
}