---
# Modify the following file with the correct hosts.
# Ansible should detect the version of python and python binary dir on the remote hosts.
# If there will be problems, and it is not detected (e.g. python was installed to some obscure location),
# add ansible_python_interpreter=<path-to-python> variable to each host (check with the official docs in case of problems).

all:
  children:
    processing:
      hosts:
        # Provide the hostname(s) or ip address(es) of the DPE server(s). You can specify one or multiple hosts.
        # For example (replace the <dpe-server-hostname> with the hostname, when preparing own inventory):
        <dpe-server-hostname>:
        <dpe-2-server-hostname>:

        # For each host, you can also specify host-specific variables. This can be handful e.g. when specifying
        # different license file for each DPE. For example as follows:
        <dpe-3-server-hostname>:
          dpe_license_file: /path/to/license-for-dpe-3.plf
