---
# tasks file for grafana - add repository
# workaround until https://github.com/cloudalchemy/ansible-grafana/pull/299 is merged

- name: Remove old Grafana GPG signing key [Debian/Ubuntu]
  ansible.builtin.apt_key:
    id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6
    state: absent
    validate_certs: false

- name: Remove old Grafana repository from sources [Debian/Ubuntu]
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: absent
    update_cache: true

- name: Import Grafana GPG signing key [Debian/Ubuntu]
  ansible.builtin.apt_key:
    url: "https://apt.grafana.com/gpg.key"
    state: present
    validate_certs: false
  register: _add_apt_key
  until: _add_apt_key is succeeded
  retries: 5
  delay: 2

- name: Add Grafana repository [Debian/Ubuntu]
  ansible.builtin.apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present
    update_cache: true
  register: _update_apt_cache
  until: _update_apt_cache is succeeded
  retries: 5
  delay: 2

- name: Disable repo management in cloudalchemy.grafana role
  ansible.builtin.set_fact:
    grafana_manage_repo: false
