---
# Modify the following file with the correct hosts.
# Ansible should detect the version of python and python binary dir on the remote hosts.
# If there will be problems, and it is not detected (e.g. python was installed to some obscure location),
# add ansible_python_interpreter=<path-to-python> variable to each host (check with the official docs in case of problems).
all:
  children:
    monitoring_server:
      hosts:
        <monitoring-hostname>:
    dependencies:
      hosts:
        <dependencies-hostname>:
    one_database:
      hosts:
        <one-database-hostname>:
    proxies:
      hosts:
        <proxy-hostname>:
    frontend:
      hosts:
        <frontend-hostname>:
    rdm_server:
      hosts:
        <rdm-hostname>:
    rdm_database:
      hosts:
        <rdm-database-hostname>:
    mdm_database:
      hosts:
        <mdm-database-hostname>:
    mdm_server:
      hosts:
        <mdm-hostname>:
    mdm_frontend:
      hosts:
        <mdm-frontend-hostname>:
# set bastion host only if we are using Azure or AWS database and remove the entries for one_database, dqit_database,
# mdm_database, rdm_database. The database endpoints (provided by the cloud service) will be supplied in vars.yml.
# Bastion is used to access the database instance during the installation.
#    bastion:
#      hosts:
#        <bastion_server_hostname>:
