---

- name: set monitoring rules
  include_role:
    name: monitoring_rules
  tags: monitoring
  vars:
    monitoring_ruleset:
      job_name: dpe
      metrics_path: /actuator/prometheus
      basic_auth:
        username: "{{ keycloak_monitoring_user.username }}"
        password: "{{ keycloak_monitoring_user.password }}"
      scheme: http
      port: "{{ dpe_http_port }}"
      static_configs:
        - labels:
            pod: dpe
            namespace: onprem
            clusterName: onprem
            app_kubernetes_io_component: dpe
