---
# handlers file for frontend

- name: Restart frontend service
  become: true
  service:
    name: "{{ item.name }}"
    state: restarted
  loop: "{{ module_services }}"
  listen: Add keycloak secret to application.properties
  no_log: true
