---
# this is default configuration for nginx proxy - orchestration server console

nginx_orchestration_proxy_config:
  template_file: http/default.conf.j2
  deployment_location: /etc/nginx/conf.d/orchestration-server.conf
  config:
    servers:
      - core:
          listen: "{{ nginx_listen_ssl }}"
          server_name: "{{ nginx_hosts.orchestration.hostname | default(omit) }}"
          error_page: "{{ nginx_default_http_error_pages }}"
        ssl:
          certificate: "{{ nginx_cert_dir }}/{{ nginx_hosts.orchestration.crt | default(omit) }}"
          certificate_key: "{{ nginx_cert_dir }}/{{ nginx_hosts.orchestration.crt_key | default(omit) }}"
        log:
          access:
            - path: "/var/log/nginx/{{ nginx_hosts.orchestration.hostname | default(omit) }}.access.log"
              format: main
        headers:
          add_headers: "{{ nginx_headers }}"
        locations: "{{ nginx_orchestration_proxy_default_locations + nginx_default_webserver }}"
    upstreams:
      - name: orchestration-server
        ip_hash: true
        servers:
          - address: "{{ orchestration_server.host }}:{{ orchestration_server.http_port }}"
            weight: 1

nginx_orchestration_proxy_default_locations:
  - location: /
    proxy:
      pass: http://orchestration-server
      set_header: "{{ nginx_proxy_headers }}"
