---
# this is default configuration for nginx proxy - dqit console (dqit server)

nginx_dqit_console_proxy_config:
  template_file: http/default.conf.j2
  deployment_location: /etc/nginx/conf.d/dqit-console.conf
  config:
    servers:
      - core:
          listen: "{{ nginx_listen_ssl }}"
          server_name: "{{ nginx_hosts.dqit_console.hostname | default(omit) }}"
          error_page: "{{ nginx_default_http_error_pages }}"
        ssl:
          certificate: "{{ nginx_cert_dir }}/{{ nginx_hosts.dqit_console.crt | default(omit) }}"
          certificate_key: "{{ nginx_cert_dir }}/{{ nginx_hosts.dqit_console.crt_key | default(omit) }}"
        log:
          access:
            - path: "/var/log/nginx/{{ nginx_hosts.dqit_console.hostname | default(omit) }}.access.log"
              format: main
        headers:
          add_headers: "{{ nginx_headers }}"
        locations: "{{ nginx_dqit_console_proxy_default_locations + nginx_default_webserver }}"
    upstreams:
      - name: dqit-server
        ip_hash: true
        servers:
          - address: "{{ dqit.server.host }}:{{ dqit.server.http_port }}"
            weight: 1

nginx_dqit_console_proxy_default_locations:
  - location: /
    proxy:
      pass: http://dqit-server
      set_header: "{{ nginx_proxy_headers }}"
