---
# this is default configuration for nginx proxy - alertmanager

nginx_audit_proxy_config:
  template_file: http/default.conf.j2
  deployment_location: /etc/nginx/conf.d/audit.conf
  config:
    servers:
      - core:
          listen: "{{ nginx_listen_ssl }}"
          server_name: "{{ nginx_hosts.audit.hostname | default(omit) }}"
          error_page: "{{ nginx_default_http_error_pages }}"
        ssl:
          certificate: "{{ nginx_cert_dir }}/{{ nginx_hosts.audit.crt | default(omit) }}"
          certificate_key: "{{ nginx_cert_dir }}/{{ nginx_hosts.audit.crt_key | default(omit) }}"
        log:
          access:
            - path: "/var/log/nginx/{{ nginx_hosts.audit.hostname | default(omit) }}.access.log"
              format: main
        headers:
          add_headers: "{{ nginx_headers }}"
        locations: "{{ nginx_audit_proxy_default_locations + nginx_default_webserver }}"
    upstreams:
      - name: audit
        ip_hash: true
        servers:
          - address: "{{ audit.host }}:{{ audit.port }}"
            weight: 1

nginx_audit_proxy_default_locations:
  - location: /
    proxy:
      pass: http://audit
      set_header: "{{ nginx_proxy_headers }}"
  - location: /actuator
    rewrite:
      return:
        code: 403
