---
# this is default configuration for nginx proxy - dpm

nginx_dpm_proxy_config:
  template_file: http/default.conf.j2
  deployment_location: /etc/nginx/conf.d/dpm.conf
  config:
    servers:
      - core:
          listen: "{{ nginx_listen_ssl }}"
          server_name: "{{ nginx_hosts.dpm.hostname | default(omit) }}"
          error_page: "{{ nginx_default_http_error_pages }}"
        ssl:
          certificate: "{{ nginx_cert_dir }}/{{ nginx_hosts.dpm.crt | default(omit)}}"
          certificate_key: "{{ nginx_cert_dir }}/{{ nginx_hosts.dpm.crt_key | default(omit)}}"
        log:
          access:
            - path: "/var/log/nginx/{{ nginx_hosts.dpm.hostname | default(omit) }}.access.log"
              format: main
        headers:
          add_headers: "{{ nginx_headers }}"
        locations: "{{ nginx_dpm_proxy_default_locations + nginx_default_webserver }}"
    upstreams:
      - name: dpm
        ip_hash: true
        servers:
          - address: "{{ dpm.host }}:{{ dpm.http_port }}"
            weight: 1

nginx_dpm_proxy_default_locations:
  - location: /
    proxy:
      pass: http://dpm
      set_header: "{{ nginx_proxy_headers }}"
  - location: /actuator
    rewrite:
      return:
        code: 403
