---
# tasks file for creating system groups

- name: Create system groups
  become: true
  group:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    gid: "{{ item.gid | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
  with_items: "{{ system_groups }}"
