---
- name: RedHat 8 - Replace system repositories with custom ones
  block:
    - name: Create backup directory
      file:
        path: /etc/yum.repos.d/bak
        state: directory
        mode: 0750

    - name: Get repositories configs
      find:
        paths: /etc/yum.repos.d/
        file_type: file
        patterns: "*.repo"
        excludes: "{{ system_custom_repos_exclude | default('') }}"
      register: system_repo_configs

    - name: Backup old repositories
      copy:
        src: "{{ backup_repo_item.path }}"
        dest: "/etc/yum.repos.d/bak/{{ backup_repo_item.path | regex_replace('.*/') }}"
        mode: 0644
        remote_src: yes
        backup: yes
      loop: "{{ system_repo_configs.files }}"
      loop_control:
        loop_var: backup_repo_item
        label: "{{ backup_repo_item.path | regex_replace('.*/') }}"

    - name: Remove old repositories
      file:
        path: "{{ remove_repo_item.path }}"
        state: absent
      loop: "{{ system_repo_configs.files }}"
      loop_control:
        loop_var: remove_repo_item
        label: "{{ remove_repo_item.path | regex_replace('.*/') }}"

    - name: Import rpm gpg keys
      rpm_key:
        state: present
        key: "{{ gpg_keys_item }}"
      loop: "{{ system_custom_repos_pgp_keys }}"
      loop_control:
        loop_var: gpg_keys_item
      when: system_custom_repos_pgp_keys is defined

    - name: Create custom repositories config
      copy:
        content: "{{ system_custom_repos_content }}"
        dest: "/etc/yum.repos.d/{{ ansible_distribution }}.repo"
        mode: 0644

  when: system_custom_repos_content is defined

- name: Update list of yum packages in repository
  yum:
    update_cache: yes

- name: RedHat 8 - package installation for Azure CLI 2.32
  yum:
    name:
      - gcc
      - python36-devel.x86_64
      - make
    state: present

- name: RedHat 8 - Upgrade pip3
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3
