---
# tasks file for creating system users

- name: Adding system users
  become: true
  user:
    name: "{{ item.username }}"
    state: "{{ item.state | default('present') }}"
    comment: "{{ item.name | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    home: "{{ item.home | default(users_home + '/' + item.username ) }}"
    create_home: '{{ item.create_home | default(omit) }}'
    system: "{{ item.system | default(omit) }}"
    group: "{{ item.group if (item.group is defined and item.group) else omit }}"
    groups: "{{ item.groups | default(users_groups) }}"
    append: "{{ item.append | default(omit) }}"
    password: "{{ item.password | default(lookup('password')) }}"
    generate_ssh_key: "{{ item.generate_ssh_key | default(omit) }}"
    ssh_key_file: ".ssh/id_{{ item.ssh_key_type | default(users_ssh_key_type) }}"
    ssh_key_passphrase: "{{ item.ssh_key_password | default(omit) }}"
    ssh_key_bits: "{{ item.ssh_key_bits | default(users_ssh_key_bits) }}"
    shell: "{{ item.shell | default(omit) }}"
    update_password: "{{ item.update_password | default(omit) }}"
  with_items: "{{ system_users }}"
  no_log: "{{ item.password is defined or item.ssh_authorized_keys is defined }}"

- name: Setting users home directory permissions
  become: true
  file:
    dest: "{{ item.home | default(users_home + '/' + item.username) }}"
    owner: "{{ item.username }}"
    group: "{{ item.group if item.group is defined else item.username }}"
    mode: "{{ item.home_mode if item.home_mode is defined else users_home_mode }}"
  when: item.create_home is not defined or item.create_home
  no_log: "{{ item.password is defined or item.ssh_authorized_keys is defined }}"
  with_items: "{{ system_users }}"

- name: Adding users .ssh directory
  become: true
  file:
    path: "{{ item.home | default(users_home + '/' + item.username) }}/.ssh"
    owner: "{{ item.username }}"
    group: "{{ item.group if item.group is defined else item.username }}"
    state: directory
    mode: "{{ item.ssh_dir_mode | default(users_ssh_dir_mode) }}"
  when: ( item.create_home is not defined or item.create_home ) and item.ssh_authorized_keys is defined
  no_log: "{{ item.password is defined or item.ssh_authorized_keys is defined }}"
  with_items: "{{ system_users }}"

- name: Adding users ssh authorized keys
  become: true
  authorized_key:
    key: "{{ item.ssh_authorized_keys | default([]) | join('\n') }}"
    user: "{{ item.username }}"
    exclusive: "{{ item.ssh_authorized_keys_exclusive | default(users_ssh_authorized_keys_exclusive) }}"
  when: ( item.create_home is not defined or item.create_home ) and item.ssh_authorized_keys is defined
  no_log: "{{ item.password is defined or item.ssh_authorized_keys is defined }}"
  with_items: "{{ system_users }}"
