---
# tasks file for rdm

- name: Configure firewall for RDM
  include: firewall.yml
  when: firewall_manage | bool
  tags:
    - firewall

- name: Install RDM
  include_role:
    name: "one_module"
  tags:
    - always
  vars:
    module_name: "{{ rdm_module_name }}"
    module_version: "{{ rdm_version }}"
    install_dir: "{{ rdm_install_dir }}"
    service_user: "{{ rdm_service_user }}"
    service_group: "{{ rdm_service_user }}"
    module_services: "{{ rdm_services }}"
    package_download_type: "{{ rdm_package_download_type }}"
    package_location: "{{ rdm_package_location }}"
    package_url: "{{ rdm_package_url }}"
    package_checksum: "{{ rdm_package_checksum }}"
    module_config: "{{ rdm_config }}"
    deploy_files: "{{ rdm_files }}"
    enable_java_heapdumps: "{{ rdm_java_heapdumps }}"
    java_temp_folder: "{{ rdm_java_temp_folder }}"
    logrotate_enabled: true

- name: Configure RDM logging
  include: logging.yml
  tags:
    - logging

- name: Wait for RDM to come up (check monitoring endpoint ready)
  uri:
    url: "http://{{ ansible_host }}:{{ rdm.http_port }}/actuator/health"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 5
  when: check_availability | default(false) | bool
  environment: "{{ (environment_vars | default({})) | combine({'http_proxy': '', 'https_proxy': ''}) }}"

- name: Configure RDM monitoring
  include: monitoring.yml
  when: monitoring_manage | bool
  tags:
    - monitoring

- name: Store a summary
  include_role:
    name: summary
  vars:
    group: Platform
    summary:
      name: RDM server
      description: "Ataccama platform module: reference data management"
      version: "{{ rdm_version }}"
      details:
        directories: "{{ [ rdm_install_dir ] }}"
        os_user: "{{ rdm_service_user }}"
        os_group: "{{ rdm_service_group }}"
        services: "{{ rdm_services | map(attribute='name') | list }}"
  tags: summary
