---
prometheus_exporter_name: nginx_exporter
prometheus_exporter_user: "{{ prometheus_exporter_name }}"
prometheus_exporter_user_manage: true
prometheus_exporter_group: "{{ prometheus_exporter_user }}"
prometheus_exporter_group_manage: true

prometheus_exporter_dist: "nginx-prometheus-exporter_{{ nginx_exporter_version }}_linux_amd64"
prometheus_exporter_create_dist: true
prometheus_exporter_download_url: "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v{{ nginx_exporter_version }}/{{ prometheus_exporter_dist }}.tar.gz"
prometheus_exporter_bin: nginx-prometheus-exporter

prometheus_exporter_service_dependency: "network.target nginx.service"
prometheus_exporter_config_file: "/etc/default/{{ prometheus_exporter_name }}"
prometheus_exporter_service_name: "{{ prometheus_exporter_name }}"
prometheus_exporter_log_path: "/var/log/{{ prometheus_exporter_service_name }}"
prometheus_exporter_service_execstart: "{{ prometheus_exporters_dir }}/{{ prometheus_exporter_name }}/{{ prometheus_exporter_bin }} $OPTIONS"
prometheus_exporter_service_description: "{{ prometheus_exporter_name }} - Exporter for nginx metrics."
prometheus_exporter_env_variables:
  OPTIONS: "{{ nginx_exporter_options | join(' ') }}"
