---
# tasks file for mdm

- name: Configure firewall for MDM
  include: firewall.yml
  when: firewall_manage | bool
  tags:
    - firewall

- name: Install MDM
  include_role:
    name: "one_module"
  tags:
    - always
  vars:
    module_name: "{{ mdm_module_name }}"
    module_version: "{{ mdm_version }}"
    install_dir: "{{ mdm_install_dir }}"
    service_user: "{{ mdm_service_user }}"
    service_group: "{{ mdm_service_group }}"
    module_services: "{{ mdm_services }}"
    package_download_type: "{{ mdm_package_download_type }}"
    package_location: "{{ mdm_package_location }}"
    package_url: "{{ mdm_package_url }}"
    package_checksum: "{{ mdm_package_checksum }}"
    module_config: "{{ mdm_config }}"
    deploy_files: "{{ mdm_files }}"
    enable_java_heapdumps: "{{ mdm_java_heapdumps }}"
    java_temp_folder: "{{ mdm_java_temp_folder }}"

- name: Configure MDM logging
  include: logging.yml
  tags:
    - logging

- name: Wait for MDM to come up (check monitoring endpoint ready)
  uri:
    url: "http://{{ ansible_host }}:{{ mdm.http_port }}/actuator/health"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 5
  when: check_availability | default(false) | bool
  environment: "{{ (environment_vars | default({})) | combine({'http_proxy': '', 'https_proxy': ''}) }}"

- name: Configure MDM monitoring
  include: monitoring.yml
  when: monitoring_manage | bool
  tags:
    - monitoring

# WORKAROUND: for unknown reason, variable (fact) ansible_domain is undefined here, unless we run setup, even if
# we explicitely say gather_facts: true in the playbook). This is true even if all the previous tasks are commented out.
# I have no idea what's happening here.
# (ansible_domain is used indirectly in definition of mdm_services)
- name: re-gather facts
  setup:
    gather_subset: min
  tags: summary

- name: Store a summary
  include_role:
    name: summary
  vars:
    group: Platform
    summary:
      name: MDM
      description: "Ataccama platform module: master data management (frontend component)"
      version: "{{ mdm_version }}"
      details:
        directories: "{{ [ mdm_install_dir ] }}"
        os_user: "{{ mdm_service_user }}"
        os_group: "{{ mdm_service_group }}"
        services: "{{ mdm_services | map(attribute='name') | list }}"
  tags: summary
