---
# default vars for nginx role - to override included galaxy roles
nginx_config_debug_output: false
nginx_config_main_template_enable: true
nginx_config_main_template:
  template_file: nginx.conf.j2
  deployment_location: /etc/nginx/nginx.conf
  config:
    main:
      user:
        username: nginx
      worker_processes: auto
      pid: /var/run/nginx.pid
      error_log:
        - file: /var/log/nginx/error.log
          level: warn
    events:
      worker_connections: 1024
    http:
      include:
        - /etc/nginx/mime.types
        - /etc/nginx/http_default.conf
        - /etc/nginx/conf.d/*.conf
    stream:
      include:
        - /etc/nginx/conf.d/stream/*.conf

## Proxy defaults
nginx_config_http_template_enable: true

## Status stub
nginx_config_status_port: "127.0.0.1:{{ nginx_status_stub_port }}"
nginx_config_status_access_log: false
