---

- name: Configure FluentBit
  include_role:
    name: fluentbit
    tasks_from: config_d.yml
  vars:
    fluentbit_conf_d:
      - name: prometheus.conf
        template: prometheus.fluentbit.conf.j2
    fluentbit_parsers_d:
      - name: prometheus.parser.conf
        fluentbit_parsers:
          - Name: logfmt
            Format: logfmt
