---
- name: Add td-agent GPG key.
  rpm_key:
    key: https://packages.treasuredata.com/GPG-KEY-td-agent
    state: present

- name: Add td-agent repository.
  template:
    src: td.repo.al2.j2
    dest: /etc/yum.repos.d/td.repo
    mode: 0644

- name: Create td-agent directory in /etc
  file:
    path: /etc/td-agent
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Install td-agent.
  yum:
    name: "td-agent-{{ fluentd_package_version }}*" # wildcard: support RHEL, Amazon Linux 2 and Ubuntu versioning schema using a single version number
    state: "{{ fluentd_package_state }}"
    allow_downgrade: true
