{
 "title": "Upgrade helper",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "DPM",
    "query": {
     "query": "label_values(ataccama_one_dpm_plugin_executor_jobs_count, pod)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MMM statistic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mmm_db_statistics_data_sources{namespace=~\"$namespace\"}",
     "legendFormat": "Data sources"
    },
    {
     "expr": "mmm_db_statistics_catalog_items{namespace=~\"$namespace\"}",
     "legendFormat": "Catalog items"
    },
    {
     "expr": "mmm_db_statistics_attributes{namespace=~\"$namespace\"}",
     "legendFormat": "Attributes"
    },
    {
     "expr": "mmm_db_statistics_number_of_terms{namespace=~\"$namespace\"}",
     "legendFormat": "Terms"
    },
    {
     "expr": "mmm_db_statistics_relations_between_tables{namespace=~\"$namespace\"}",
     "legendFormat": "Relationships"
    },
    {
     "expr": "mmm_db_statistics_number_of_profiled_tables{namespace=~\"$namespace\"}",
     "legendFormat": "Profiled tables"
    },
    {
     "expr": "mmm_db_statistics_number_of_terms_assigned_to_tables{namespace=~\"$namespace\"}",
     "legendFormat": "Terms on tables"
    },
    {
     "expr": "mmm_db_statistics_number_of_terms_assigned_to_columns{namespace=~\"$namespace\"}",
     "legendFormat": "Terms on columns"
    },
    {
     "expr": "mmm_db_statistics_rules_amount{namespace=~\"$namespace\"}",
     "legendFormat": "Rules"
    },
    {
     "expr": "mmm_db_statistics_monitoring_project_amount{namespace=~\"$namespace\"}",
     "legendFormat": "Monitoring projects"
    }
   ]
  },
  {
   "title": "Jobs in progress (DPx)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "ataccama_one_dpm_plugin_executor_jobs_count{status!=\"killed\", status!=\"success\", status!=\"failure\", status!=\"unknown\", status!=\"unrecognized\", namespace=~\"$namespace\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Associated engines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ataccama_one_dpm_engines_count_connected{namespace=~\"$namespace\"}",
     "legendFormat": "Connected engines"
    },
    {
     "expr": "ataccama_one_dpm_engines_count_disconnected{namespace=~\"$namespace\"}",
     "legendFormat": "Disconnected engines"
    },
    {
     "expr": "ataccama_one_dpm_engines_count_active{namespace=~\"$namespace\"}",
     "legendFormat": "Active engines"
    },
    {
     "expr": "rate(ataccama_one_dpm_engines_count_inactive{namespace=~\"$namespace\"}[1d])",
     "legendFormat": "Inactive engines"
    }
   ]
  },
  {
   "title": "Engine status check duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ataccama_one_dpm_engines_status_check_duration_seconds{quantile=\"0.95\", namespace=~\"$namespace\"}",
     "legendFormat": "Average"
    },
    {
     "expr": "ataccama_one_dpm_engines_status_check_duration_seconds_max{namespace=~\"$namespace\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Dependencies health",
   "type": "status-history",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 22 },
   "repeat": "depender",
   "targets": [
    {
     "expr": "ataccama_one_dependency_health{namespace=~\"$namespace\"}",
     "legendFormat": "{{depender}} -> {{dependency}}"
    }
   ]
  }
 ]
}