{
 "title": "Gen 2 - Healthiness",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "User activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active users",
   "type": "graph",
   "description": "A number of active users. An active user is everyone who called an application within the last 15 minutes.. User is defined as username. If multiple users sharing same credentials it is evaluated as signle user.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ataccama_one_mmm_activeusers{namespace=~\"$namespace\"}",
     "legendFormat": "Number of active users"
    }
   ]
  },
  {
   "title": "GQL Requests per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(graphql_timer_query_seconds_count{namespace=~\"$namespace\"} [1m]))",
     "legendFormat": "number of requests"
    }
   ]
  },
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of pods active",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (container) (kube_pod_container_status_running{container=~\"audit|cs|elasticsearch.*|keycloak|mantaflow|minio|mmm-.*|dpe|dpm|aicore-.*\", namespace=~\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Number of pods restarts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (delta(kube_pod_container_status_restarts_total{container=~\"audit|cs|elasticsearch.*|keycloak|mantaflow|minio|mmm-.*|dpe|dpm|aicore-.*\", namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Failed job percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ataccama_one_mmm_jobs_duration_total_seconds_count{exitStatus=\"FAILED\",namespace=~\"$namespace\"}[5m])) / sum(rate(ataccama_one_mmm_jobs_duration_total_seconds_count{namespace=~\"$namespace\"}[5m])) * 100",
     "legendFormat": "MMM"
    },
    {},
    {}
   ]
  },
  {
   "title": "DPM engine management ",
   "type": "graph",
   "description": "DPE engines status from DPM perspective",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "number of DPE" }
   ],
   "targets": [
    {
     "expr": "ataccama_one_dpm_engines_count_active{namespace=~\"$namespace\"}",
     "legendFormat": "active {{pod}}"
    },
    {
     "expr": "ataccama_one_dpm_engines_count_connected{namespace=~\"$namespace\"}",
     "legendFormat": "connected {{pod}}"
    },
    {
     "expr": "ataccama_one_dpm_engines_count_disconnected{namespace=~\"$namespace\"}",
     "legendFormat": "disconnected {{pod}}"
    }
   ]
  },
  {
   "title": "DPE saturation",
   "type": "graph",
   "description": "Number of jobs being processed by each DPE",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    {
     "format": "short",
     "label": "Number of jobs processed in parallel"
    }
   ],
   "targets": [
    {
     "expr": "ataccama_one_dpe_plugin_executor_jobs_running{namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(ataccama_one_dpe_plugin_executor_jobs_running{namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}