{
 "title": "Ataccama / Gen 2 - MMM Data Stories integration",
 "description": "Dashboard for Data Stories integration functionality in MMM backend.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Data Stories event consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processed event bulks rate",
   "type": "timeseries",
   "description": "Rate of processed event bulks of from queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_datastories_events_bulk_processed_total{namespace=~\"$namespace\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Processed events rate",
   "type": "timeseries",
   "description": "Rate of processed Data Stories events from queue, divided by event type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_datastories_events_processed_total{namespace=~\"$namespace\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Invalid events rate",
   "type": "timeseries",
   "description": "Rate of invalid events received from Data Stories found during processing. Possible reasons: no valid sharing token, no story, no story id (depending on event type)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_datastories_events_invalid_total{namespace=~\"$namespace\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Event queue size",
   "type": "timeseries",
   "description": "Amount of events sent from Data Stories, that are waiting in queue to be processed. Warning: processing may be too fast (because of wait/notify type mechanism) so it's very possible value will be only zero in normal use.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "ataccama_one_mmm_datastories_events_queue_size{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Deleted catalog items rate",
   "type": "timeseries",
   "description": "Rate of deleted catalog items by delete/retract event handling, that were representing report from Data Stories.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_datastories_events_delete_catalog_items_deleted_total{namespace=~\"$namespace\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Rate of deleted Usage relationships during import",
   "type": "timeseries",
   "description": "Rate of deleted Usage relationships during import - for those used catalog items that were removed from the report.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(ataccama_one_mmm_datastories_events_import_relationships_deleted_total{namespace=~\"$namespace\"}[$__rate_interval])"
    }
   ]
  }
 ]
}