{
 "title": "Runtime server",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{clusterName=~\"$cluster\"}, namespace)"
    }
   },
   { "name": "runtime_job_name", "query": "runtime-server-svc" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage{ namespace=~\"$namespace\", job=~\"$runtime_job_name\"} * 100",
     "legendFormat": "CPU Usage [%]"
    }
   ]
  },
  {
   "title": "JVM Memory used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by() (jvm_memory_used_bytes{ namespace=~\"$namespace\", job=~\"$runtime_job_name\"}) / 1048576",
     "legendFormat": "JVM Memory"
    }
   ]
  },
  {
   "title": "Disk free space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "disk_free_bytes{ namespace=~\"$namespace\", job=~\"$runtime_job_name\"} / 1048576",
     "legendFormat": "Disk free space"
    }
   ]
  }
 ]
}