{
 "title": "Task Service - operation overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(graphql_datafetcher_seconds_count{namespace=\"$namespace\"}, pod)"
    }
   },
   { "name": "application", "label": "Application", "query": "tasks" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<h1> Other Helpful dashboards</h1>\n\n\n<a href=\"/d/utAHHgJnkxxc\"> Spring boot statistics</a>\n"
   }
  },
  { "title": "GRPC server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "GRPC server pool",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "ataccama_one_grpc_server_pool_size{namespace=~\"$namespace\", app_kubernetes_io_component=~\"$application\"}",
     "legendFormat": "Pool size"
    },
    {
     "expr": "ataccama_one_grpc_server_pool_active{namespace=~\"$namespace\", app_kubernetes_io_component=~\"$application\"}",
     "legendFormat": "Pool active"
    },
    {
     "expr": "ataccama_one_grpc_server_pool_queue_size{namespace=~\"$namespace\", app_kubernetes_io_component=~\"$application\"}",
     "legendFormat": "Pool queue size"
    }
   ]
  },
  {
   "title": "GRPC server requests avg - PermissionService",
   "type": "graph",
   "gridPos": { "h": 14, "w": 7, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(ataccama_one_grpc_server_request_seconds_sum{namespace=\"$namespace\", app_kubernetes_io_component=\"$application\",serviceName=\"ataccama.commentsapi.permissionprovider.PermissionService\",status=\"OK\",type=\"UNARY\",})/increase(ataccama_one_grpc_server_request_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$application\",serviceName=\"ataccama.commentsapi.permissionprovider.PermissionService\",status=\"OK\",type=\"UNARY\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "GRPC server requests avg - CommentsNotificationService",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(ataccama_one_grpc_server_request_seconds_sum{namespace=\"$namespace\", app_kubernetes_io_component=\"$application\",serviceName=\"ataccama.commentsapi.notificationprovider.CommentsNotificationService\",status=\"OK\",type=\"UNARY\",})/increase(ataccama_one_grpc_server_request_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$application\",serviceName=\"ataccama.commentsapi.notificationprovider.CommentsNotificationService\",status=\"OK\",type=\"UNARY\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request seconds avg total - PermissionService",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ataccama_one_grpc_server_request_seconds_sum{namespace=\"$namespace\", app_kubernetes_io_component=\"$application\",serviceName=\"ataccama.commentsapi.permissionprovider.PermissionService\",status=\"OK\",type=\"UNARY\",})/(ataccama_one_grpc_server_request_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$application\",serviceName=\"ataccama.commentsapi.permissionprovider.PermissionService\",status=\"OK\",type=\"UNARY\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request seconds avg total - CommentsNotificationService",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ataccama_one_grpc_server_request_seconds_sum{namespace=\"$namespace\", app_kubernetes_io_component=\"$application\",serviceName=\"ataccama.commentsapi.notificationprovider.CommentsNotificationService\",status=\"OK\",type=\"UNARY\",})/(ataccama_one_grpc_server_request_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$application\",serviceName=\"ataccama.commentsapi.notificationprovider.CommentsNotificationService\",status=\"OK\",type=\"UNARY\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Client call seconds avg total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ataccama_one_grpc_client_call_seconds_sum{namespace=\"$namespace\", app_kubernetes_io_component=\"$application\"})/(ataccama_one_grpc_client_call_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$application\"})",
     "legendFormat": "Client call seconds avg"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "pod CPU throtling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"tasks-.*\", container!=\"\"}[1m])) by (pod,container) /sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"tasks-.*\", container!=\"\"}[1m])) by (pod,container)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "task service keycloak client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "keycloak requests from $pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "c/s" } },
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"$application\", name=\"keycloak\", pod=\"$pod\"}[1m]) ",
     "legendFormat": "{{kind}} - {{pod}}"
    }
   ]
  },
  {
   "title": "keycloak response time from $pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{namespace=\"$namespace\", app_kubernetes_io_component=\"tasks\", name=\"keycloak\", pod=\"$pod\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"tasks\", name=\"keycloak\", pod=\"$pod\"}[1m]) ",
     "legendFormat": "{{kind}} - {{pod}}"
    }
   ]
  },
  { "title": "MMM calls to task service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "resilience4j task-service client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"mmm-be\",  name=\"task-service\"})) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Graphql request / error count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "OK graphql requests by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "increase(graphql_request_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"tasks\", outcome=\"SUCCESS\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ERROR graphql requests by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 58 },
   "targets": [
    {
     "expr": "increase(graphql_request_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"tasks\", outcome=\"ERROR\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "errors by path",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 58 },
   "targets": [
    {
     "expr": "sum(increase(graphql_error_total{app_kubernetes_io_component=\"tasks\", namespace=\"$namespace\"}[1m])) by (error_path)",
     "legendFormat": "{{error_path}}"
    }
   ]
  },
  {
   "title": "avg response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "rate(graphql_request_seconds_sum{app_kubernetes_io_component=\"tasks\", outcome=\"SUCCESS\", namespace=\"$namespace\"}[1m]) /\nrate(graphql_request_seconds_count{app_kubernetes_io_component=\"tasks\", outcome=\"SUCCESS\", namespace=\"$namespace\"}[1m]) "
    }
   ]
  },
  {
   "title": "playground - not finished",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "used JVM memory",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 14, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", app_kubernetes_io_component=\"tasks\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "OK graphql requests by pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "increase(graphql_request_seconds_sum{namespace=\"$namespace\", app_kubernetes_io_component=\"tasks\", outcome=\"SUCCESS\"}[1m]) / increase(graphql_request_seconds_count{namespace=\"$namespace\", app_kubernetes_io_component=\"tasks\", outcome=\"SUCCESS\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "playground - Pod - $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "requests per graphql field",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "increase(graphql_datafetcher_seconds_count{namespace=\"$namespace\", pod=\"$pod\", outcome=\"SUCCESS\"}[1m])",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  }
 ]
}