---

- name: set firewall rules
  include_role:
    name: firewall_rules
  vars:
    iptables:
      allowed_tcp_ports:
        - port: 9187 # port is hardcoded in the exporter
          source: "{{ groups['monitoring_server'] }}"
