---
- hosts: all
  any_errors_fatal: true
  gather_facts: true
  gather_subset: os_family
  roles:
    - role: fluentbit
      vars:
        fluentbit_outputs:
          - Name: 'forward'
            Match: "*"
            Host: "{{ groups['monitoring_server'][0] }}"
            Port: "{{ fluentd_port }}"
  environment: "{{ environment_vars | default({}) }}"

- hosts: monitoring_server
  any_errors_fatal: true
  gather_facts: true
  gather_subset: os_family
  pre_tasks:
    - name: Stop Elasticsearch if running     # for the sake of upgrades
      service:
        name: elasticsearch
        state: stopped
        enabled: no
      failed_when: false
  roles:
    - role: firewall_rules
      vars:
        ansible_parent_role_names: ['logging']
        iptables:
          allowed_tcp_ports:
            - port: "{{ opensearch_api_port }}"
              source: "{{ groups['frontend'] }}"
            - port: "{{ fluentd_port }}"
              source: "{{ groups['all']  }}"
            - port: "{{ fluentd_http_metrics_port }}"
              source: "{{ groups['monitoring_server'] }}"
      when: firewall_manage | bool
      tags:
        - firewall
        - summary
    - role: opensearch
      vars:
        opensearch_version: "{{ opensearch_version_logging }}"
        opensearch_cluster_name: logging
        opensearch_index_templates:
          - name: default-index-template
            template:
              index_patterns: ['console-*', 'accesslog-*']
              template:
                settings:
                  number_of_shards: 1
                  number_of_replicas: 0
        opensearch_ism_policies:
          - policy:
              policy_id: delete-after-30-days
              description: 'Deletes index after 30 days'
              default_state: default
              states:
                - name: default
                  actions:
                    - replica_count:
                        number_of_replicas: 0
                  transitions:
                    - state_name: cold
                      conditions:
                        min_index_age: 30d
                - name: cold
                  actions:
                    - delete: { }
              ism_template:
                - index_patterns:
                    - 'console-*'
                    - 'accesslog-*'
                  priority: 1
    - role: fluentd
  environment: "{{ environment_vars | default({}) }}"

- hosts: frontend
  any_errors_fatal: true
  gather_facts: true
  gather_subset: os_family
  pre_tasks:
    - name: Stop Kibana if running     # for the sake of upgrades
      service:
        name: kibana
        state: stopped
        enabled: no
      failed_when: false
  roles:
    - role: opensearch_dashboards
      vars:
        opensearch_hosts: "{{ 'http://' ~ groups['monitoring_server'][0] ~ ':' ~ opensearch_api_port }}"
  environment: "{{ environment_vars | default({}) }}"
