---

- name: Configure FluentBit
  include_role:
    name: fluentbit
    tasks_from: config_d.yml
  vars:
    fluentbit_conf_d:
      - name: dqit.conf
        template: dqit.fluentbit.conf.j2
      - name: console-filter.conf
        template: fluentbit/filters/console-filter.conf.j2
    fluentbit_parsers_d:
      - name: dqit-parsers.conf
        template: dqit-parsers.fluentbit.conf.j2
