---
## Modify the following file with the correct hosts
# Ansible should detect the version of python and python binary dir on the remote hosts.
# If there will be problems and it is not detected (e.g. python was installed to some obscure location),
# add ansible_python_interpreter=<path-to-python> to each host (check with the official docs in case of problems).
all:
  children:
    monitoring_server:
      hosts:
        <monitoring-hostname>:
    frontend:
      hosts:
        <frontend-hostname>:
    proxies:
      hosts:
        <proxy-hostname>:
    ai_server:
      hosts:
        <ai-server-hostname>:
    one_app:
      hosts:
        <one-application-server-hostname>:
    processing:
      hosts:
        <processing-server-hostname>:
    dependencies:
      hosts:
        <dependency-server-hostname>:
    one_database:
      hosts:
        <one-database-server-hostname>:
    dqit_server:
      hosts:
        <dqit-server-hostname>:
    dqit_database:
      hosts:
        <dqit-database-server-hostname>:
    orchestration_server:
      hosts:
        <orchestration-server-hostname>:
    mde_lineage:
      hosts:
        <mde-lineage-hostname>:
    dqf_server:
      hosts:
        <orchestration-server-hostname>:
# set bastion host only if we are using Azure or AWS database and remove the entries for one_database, dqit_database,
# mdm_database, rdm_database. The database endpoints (provided by the cloud service) will be supplied in vars.yml.
# Bastion is used to access the database instance during the installation.
#    bastion:
#      hosts:
#        <bastion_server_hostname>:
