---
# setup tasks for non default versions of Postgres on RHEL / CentOS

- name: Install Postgresql repo and key
  block:
    - name: Check pgdg repository package | RedHat
      yum:
        name: "{{ postgresql_yum_repo_package }}"
      register: __postgresql_repo_pkg_installed_result
      ignore_errors: yes

    - name: Install pgdg repositories yum package | RedHat
      yum:
        name: "{{ postgresql_yum_repo_url }}"
        state: present
        disable_gpg_check: yes
      register: __postgresql_yum_result
      until: __postgresql_yum_result is succeeded
      retries: 5
      delay: 5
      when: __postgresql_repo_pkg_installed_result is failed

    - name: Update pgdg repositories | RedHat
      yum:
        update_cache: yes
      when: __postgresql_repo_pkg_installed_result is failed

    - name: Disable postgres module from default app streams | RedHat
      command:
        cmd: 'yum -qy module disable postgresql'  # noqa command-instead-of-module
      when:
        - __postgresql_repo_pkg_installed_result is failed
        - ansible_distribution_major_version is version('7', '!=')
        - ansible_distribution_major_version is version('9', '!=')

  when: postgresql_enablerepo is defined
