---
prometheus_exporter_name: ataccama_mmm_exporter
prometheus_exporter_user: "{{ mmm_exporter_user }}"
prometheus_exporter_group: "{{ mmm_exporter_group }}"
prometheus_exporter_user_manage: true
prometheus_exporter_group_manage: true

prometheus_exporter_dist: "postgres_exporter-{{ mmm_exporter_version }}.linux-amd64"
prometheus_exporter_download_url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ mmm_exporter_version }}/{{ prometheus_exporter_dist }}.tar.gz"

prometheus_exporter_bin: postgres_exporter

prometheus_exporter_config_file: "/etc/default/{{ prometheus_exporter_name }}"
prometheus_exporter_log_path: "/var/log/{{ prometheus_exporter_service_name }}"
prometheus_exporter_service_execstart: "{{ prometheus_exporters_dir }}/{{ prometheus_exporter_name }}/{{ prometheus_exporter_bin }} $FLAGS"
prometheus_exporter_service_description: "{{ prometheus_exporter_name }} - Exporter for PostgreSQL metrics."
prometheus_exporter_env_variables:
  DATA_SOURCE_NAME: "{{ mmm_exporter_datasource }}"
  FLAGS: "{{ mmm_exporter_flags | join(' ') }}"
