---
- name: set firewall rules
  include_role:
    name: firewall_rules
  vars:
    iptables:
      allowed_tcp_ports:
        - port: "{{ comment_port }}"
          source: "{{ groups['one_app'] | default([]) }}"
        - port: "{{ comment_management_port }}"
          source: "{{ groups['monitoring_server'] }}"
