---

- name: Configure FluentBit
  include_role:
    name: fluentbit
    tasks_from: config_d.yml
  vars:
    fluentbit_conf_d:
      - name: task.conf
        template: task.fluentbit.conf.j2
      - name: console-filter.conf
        template: fluentbit/filters/console-filter.conf.j2
    fluentbit_parsers_d:
      - name: task-parser.conf
        template: task-parser.fluentbit.conf.j2
